"""Patch 20_tables.sql: convert 10 identity columns to sequence-backed defaults.

Why this exists
----------------
This bug has broken every migration so far (BL_ID/ALERT_ID on 2026-07-23, CHECK_ID
later, CALL_ID/LOG_ID this week): Snowflake does not adjust an autoincrement counter
when a table is loaded with explicit ids, does not enforce the primary key, and
`autoincrement ... noorder` allocates from non-monotonic cached ranges anyway (two
consecutive single-row inserts were measured this week receiving id 313 then 651).
So instead of loading data and discovering the collision later, one procedure per
table, every autoincrement identity column that will be loaded with explicit ids is
converted to `DEFAULT <seq>.NEXTVAL` before a single row is loaded.

AI_CALL_LOG.CALL_ID/LOG_ID are already sequence-backed from an earlier fix and are
left untouched. PARSED_DOCUMENTS.DOC_ID is left as plain autoincrement: the table is
empty and not being loaded, so there is nothing to collide with.

Why the patch is table-scoped, not a global text replace
----------------------------------------------------------
Column names collide across tables -- DOC_ID exists on both
BILL_OF_LADING_EXTRACTED (start 500) and PARSED_DOCUMENTS (start 1) -- so this first
splits the file into one block per CREATE TABLE statement and only edits the block
for the named table, rather than replacing every occurrence of a column name in the
file.
"""

import re
import sys
from pathlib import Path

CHUNKS = Path(r"C:\Users\phuochoa\Mendix\VF_Logistics_Portal-main_2\snowflake-backend"
              r"\backup_2026-08-19\ddl\chunks")
SRC = CHUNKS / "20_tables.sql"

# table -> (column, sequence name)
TARGETS = {
    "AI_ANOMALY_REPORT":        ("REPORT_ID",       "AI_ANOMALY_REPORT_REPORT_ID_SEQ"),
    "BILL_OF_LADING":           ("BL_ID",           "BILL_OF_LADING_BL_ID_SEQ"),
    "BILL_OF_LADING_EXTRACTED": ("DOC_ID",          "BILL_OF_LADING_EXTRACTED_DOC_ID_SEQ"),
    "CHAT_MESSAGE":             ("MESSAGE_ID",      "CHAT_MESSAGE_MESSAGE_ID_SEQ"),
    "COMPLIANCE_CHECK_RESULT":  ("CHECK_ID",        "COMPLIANCE_CHECK_RESULT_CHECK_ID_SEQ"),
    "FRAUD_ALERT":              ("ALERT_ID",        "FRAUD_ALERT_ALERT_ID_SEQ"),
    "NOTIFICATION_LOG":         ("NOTIFICATION_ID", "NOTIFICATION_LOG_NOTIFICATION_ID_SEQ"),
    "SAP_FI_DOCUMENT":          ("FI_DOC_ID",       "SAP_FI_DOCUMENT_FI_DOC_ID_SEQ"),
    "VESSEL_REGISTRY":          ("VESSEL_ID",       "VESSEL_REGISTRY_VESSEL_ID_SEQ"),
    "WORKFLOW_AUDIT_LOG":       ("AUDIT_ID",        "WORKFLOW_AUDIT_LOG_AUDIT_ID_SEQ"),
}

SEQ_START = 100000  # every historical max id is under 15000; large round margin


def main() -> int:
    text = SRC.read_text(encoding="utf-8")

    table_starts = [m.start() for m in
                     re.finditer(r"create or replace TABLE MENDIX_APP\.AGENTS\.(\w+)",
                                 text)]
    table_names = [re.match(r"create or replace TABLE MENDIX_APP\.AGENTS\.(\w+)",
                             text[s:]).group(1) for s in table_starts]
    bounds = table_starts + [len(text)]
    blocks = {name: (bounds[i], bounds[i + 1])
              for i, name in enumerate(table_names)}

    missing = [t for t in TARGETS if t not in blocks]
    if missing:
        print(f"FAIL: tables not found in {SRC.name}: {missing}")
        return 1

    patched = text
    offset_delta = 0
    seq_ddl = []

    for table, (col, seq) in TARGETS.items():
        start, end = blocks[table]
        start += offset_delta
        end += offset_delta
        block = patched[start:end]

        pattern = re.compile(
            rf"(\b{col}\s+NUMBER\(38,0\)\s*(?:NOT NULL\s*)?)"
            rf"autoincrement\s+start\s+\d+\s+increment\s+1\s+noorder",
            re.I)
        new_block, n = pattern.subn(
            rf"\1DEFAULT MENDIX_APP.AGENTS.{seq}.NEXTVAL", block)

        if n != 1:
            print(f"FAIL: {table}.{col} pattern matched {n} times, expected 1")
            return 1

        patched = patched[:start] + new_block + patched[end:]
        offset_delta += len(new_block) - len(block)
        seq_ddl.append(
            f"create or replace sequence MENDIX_APP.AGENTS.{seq} "
            f"start with {SEQ_START} increment by 1 order "
            f"comment = 'Backs {table}.{col}. Was autoincrement noorder, which "
            f"allocates from non-monotonic cached ranges and collided with "
            f"explicit ids loaded from the migration CSV.';"
        )

    header = (
        "-- 15_migration_sequences: 10 new sequences, generated by "
        "tools/patch_identity_columns.py\n"
        "-- Backs the identity columns patched into 20_tables.sql below. Must run\n"
        "-- BEFORE 20_tables.sql, since the table DEFAULT expressions reference them.\n\n"
        "USE DATABASE MENDIX_APP;\nUSE SCHEMA AGENTS;\n\n"
        + "\n".join(seq_ddl) + "\n"
    )
    (CHUNKS / "15_migration_sequences.sql").write_text(header, encoding="utf-8")
    SRC.write_text(patched, encoding="utf-8")

    print(f"wrote {CHUNKS / '15_migration_sequences.sql'} ({len(TARGETS)} sequences)")
    print(f"patched {SRC} in place ({len(TARGETS)} columns)")
    for table, (col, seq) in TARGETS.items():
        print(f"  {table}.{col} -> DEFAULT {seq}.NEXTVAL")
    return 0


if __name__ == "__main__":
    sys.exit(main())
