-- 05_tags: TAG (4 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

create or replace tag MENDIX_APP.AGENTS.DATA_DOMAIN COMMENT='Business domain classification';

create or replace tag MENDIX_APP.AGENTS.DATA_OWNER COMMENT='Team or person responsible for data quality';

create or replace tag MENDIX_APP.AGENTS.DATA_SENSITIVITY COMMENT='Data sensitivity level: PUBLIC, INTERNAL, CONFIDENTIAL, RESTRICTED';

create or replace tag MENDIX_APP.AGENTS.PII_FLAG COMMENT='Contains Personally Identifiable Information: YES/NO';
