-- 10_sequences_and_formats: SEQUENCE, FILE FORMAT (4 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

create or replace sequence MENDIX_APP.AGENTS.AI_CALL_LOG_CALL_SEQ start with 100000 increment by 1 order;

create or replace sequence MENDIX_APP.AGENTS.AI_CALL_LOG_LOG_SEQ start with 100000 increment by 1 order;

create or replace sequence MENDIX_APP.AGENTS.CHAT_SESSION_SEQ start with 1000 increment by 1 noorder;

CREATE OR REPLACE FILE FORMAT MENDIX_APP.AGENTS.RAW_TEXT
	RECORD_DELIMITER = 'NONE'
	FIELD_DELIMITER = 'NONE';
