-- 15_migration_sequences: 10 new sequences, generated by tools/patch_identity_columns.py
-- Backs the identity columns patched into 20_tables.sql below. Must run
-- BEFORE 20_tables.sql, since the table DEFAULT expressions reference them.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

create or replace sequence MENDIX_APP.AGENTS.AI_ANOMALY_REPORT_REPORT_ID_SEQ start with 100000 increment by 1 order comment = 'Backs AI_ANOMALY_REPORT.REPORT_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.BILL_OF_LADING_BL_ID_SEQ start with 100000 increment by 1 order comment = 'Backs BILL_OF_LADING.BL_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED_DOC_ID_SEQ start with 100000 increment by 1 order comment = 'Backs BILL_OF_LADING_EXTRACTED.DOC_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.CHAT_MESSAGE_MESSAGE_ID_SEQ start with 100000 increment by 1 order comment = 'Backs CHAT_MESSAGE.MESSAGE_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.COMPLIANCE_CHECK_RESULT_CHECK_ID_SEQ start with 100000 increment by 1 order comment = 'Backs COMPLIANCE_CHECK_RESULT.CHECK_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.FRAUD_ALERT_ALERT_ID_SEQ start with 100000 increment by 1 order comment = 'Backs FRAUD_ALERT.ALERT_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.NOTIFICATION_LOG_NOTIFICATION_ID_SEQ start with 100000 increment by 1 order comment = 'Backs NOTIFICATION_LOG.NOTIFICATION_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.SAP_FI_DOCUMENT_FI_DOC_ID_SEQ start with 100000 increment by 1 order comment = 'Backs SAP_FI_DOCUMENT.FI_DOC_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.VESSEL_REGISTRY_VESSEL_ID_SEQ start with 100000 increment by 1 order comment = 'Backs VESSEL_REGISTRY.VESSEL_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
create or replace sequence MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG_AUDIT_ID_SEQ start with 100000 increment by 1 order comment = 'Backs WORKFLOW_AUDIT_LOG.AUDIT_ID. Was autoincrement noorder, which allocates from non-monotonic cached ranges and collided with explicit ids loaded from the migration CSV.';
