-- 60_procedures_1: PROCEDURE (14 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.AI_COMPLETE_WITH_RETRY("P_PROMPT" VARCHAR, "P_MODEL" VARCHAR DEFAULT 'llama3-8b', "P_MAX_RETRIES" NUMBER(38,0) DEFAULT 2)
RETURNS VARIANT
LANGUAGE SQL
COMMENT='Wrapper for CORTEX.COMPLETE with retry logic.'
EXECUTE AS OWNER
AS 'BEGIN
    DECLARE
        V_RESPONSE VARIANT;
        V_RESPONSE_TEXT VARCHAR;
        V_RETRY_COUNT NUMBER DEFAULT 0;
        V_ERROR_MSG VARCHAR;
        V_MODEL_TO_USE VARCHAR DEFAULT P_MODEL;
    BEGIN
        WHILE (V_RETRY_COUNT <= P_MAX_RETRIES) DO
            BEGIN
                V_RESPONSE := (SELECT SNOWFLAKE.CORTEX.COMPLETE(:V_MODEL_TO_USE, :P_PROMPT));
                V_RESPONSE_TEXT := (SELECT TO_VARCHAR(:V_RESPONSE));
                INSERT INTO AI_CALL_LOG (MODEL_NAME, PROMPT, RESPONSE, CALL_STATUS, CONTEXT)
                VALUES (:V_MODEL_TO_USE, :P_PROMPT, :V_RESPONSE_TEXT, ''SUCCESS'', ''AI_COMPLETE_WITH_RETRY'');
                RETURN V_RESPONSE;
            EXCEPTION
                WHEN OTHER THEN
                    V_ERROR_MSG := SQLERRM;
                    V_RETRY_COUNT := V_RETRY_COUNT + 1;
                    IF (V_RETRY_COUNT = 1 AND V_MODEL_TO_USE = ''llama3-8b'') THEN
                        V_MODEL_TO_USE := ''mistral-large2'';
                    END IF;
                    INSERT INTO AI_CALL_LOG (MODEL_NAME, PROMPT, CALL_STATUS, ERROR_MESSAGE, CONTEXT)
                    VALUES (:V_MODEL_TO_USE, :P_PROMPT, ''ERROR'', :V_ERROR_MSG, ''AI_COMPLETE_WITH_RETRY'');
                    IF (V_RETRY_COUNT > P_MAX_RETRIES) THEN
                        RETURN OBJECT_CONSTRUCT(''error'', TRUE, ''message'', V_ERROR_MSG);
                    END IF;
            END;
        END WHILE;
        RETURN OBJECT_CONSTRUCT(''error'', TRUE, ''message'', ''Max retries exceeded'');
    END;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.AI_EXPLAIN_ANOMALY("P_FRAUD_ALERT_ID" NUMBER(38,0), "P_LANGUAGE" VARCHAR DEFAULT 'EN')
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Uses CORTEX.COMPLETE to generate natural language explanation for fraud alerts.'
EXECUTE AS OWNER
AS '
DECLARE
    V_ALERT_TYPE VARCHAR;
    V_DESCRIPTION VARCHAR;
    V_PROMPT VARCHAR;
    V_EXPLANATION VARCHAR;
    V_RESPONSE VARIANT;
BEGIN
    SELECT ALERT_TYPE, DESCRIPTION INTO V_ALERT_TYPE, V_DESCRIPTION
    FROM FRAUD_ALERT WHERE ALERT_ID = :P_FRAUD_ALERT_ID;
    V_PROMPT := ''You are a logistics fraud analyst. Explain this fraud alert in business terms for '' ||
                CASE :P_LANGUAGE WHEN ''VN'' THEN ''Vietnamese'' WHEN ''JA'' THEN ''Japanese'' ELSE ''English'' END ||
                '' readers. Alert type: '' || :V_ALERT_TYPE || ''. Description: '' || :V_DESCRIPTION ||
                ''. Provide: 1) What happened, 2) Why it matters, 3) Recommended actions. Keep it under 200 words.'';
    V_RESPONSE := (CALL AI_COMPLETE_WITH_RETRY(:V_PROMPT, ''llama3-8b'', 2));
    V_EXPLANATION := V_RESPONSE::VARCHAR;
    INSERT INTO AI_ANOMALY_REPORT (ANOMALY_TYPE, SEVERITY, BUSINESS_EXPLANATION, LANGUAGE, STATUS)
    VALUES (:V_ALERT_TYPE, ''MEDIUM'', :V_EXPLANATION, :P_LANGUAGE, ''NEW'');
    RETURN V_EXPLANATION;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.AI_EXPLAIN_ANOMALY("P_LANGUAGE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_ALERT_ID NUMBER;
    V_COUNT NUMBER DEFAULT 0;
    V_RESULT VARCHAR;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'';
    IF (V_COUNT = 0) THEN
        RETURN ''{"reports_generated": 0, "message": "No open HIGH alerts to explain"}'';
    END IF;
    SELECT ALERT_ID INTO V_ALERT_ID FROM FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN''
    ORDER BY CREATED_AT DESC LIMIT 1;
    CALL AI_EXPLAIN_ANOMALY(:V_ALERT_ID, :P_LANGUAGE);
    RETURN ''{"reports_generated": 1, "alert_id": '' || :V_ALERT_ID || ''}'';
EXCEPTION
    WHEN OTHER THEN
        RETURN ''{"reports_generated": 0, "message": "'' || REPLACE(SQLERRM, ''"'', ''\\"'') || ''"}'';
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.AI_GENERATE_INSIGHTS("P_LANGUAGE" VARCHAR DEFAULT 'EN')
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_TOTAL_BLS NUMBER; V_HIGH_RISK NUMBER; V_SAP_POSTED NUMBER; V_AVG_CHARGES FLOAT;
    V_OPEN_ALERTS NUMBER; V_STATS VARCHAR; V_PROMPT VARCHAR; V_RAW VARCHAR;
    V_INSIGHTS VARCHAR; V_START_POS NUMBER; V_END_POS NUMBER;
    V_START_TS TIMESTAMP_NTZ; V_ELAPSED_MS NUMBER; V_CALL_STATUS VARCHAR;
    V_IN_TOKENS NUMBER; V_OUT_TOKENS NUMBER;
BEGIN
    SELECT COUNT(*), SUM(CASE WHEN STATUS = ''Pending_Review'' THEN 1 ELSE 0 END),
        SUM(CASE WHEN STATUS = ''SAP_POSTED'' THEN 1 ELSE 0 END), ROUND(AVG(TOTAL_CHARGES), 2)
    INTO V_TOTAL_BLS, V_HIGH_RISK, V_SAP_POSTED, V_AVG_CHARGES FROM BILL_OF_LADING;
    SELECT COUNT(*) INTO V_OPEN_ALERTS FROM FRAUD_ALERT WHERE STATUS = ''OPEN'';
    V_STATS := ''Total BLs: '' || :V_TOTAL_BLS || '', Pending: '' || :V_HIGH_RISK ||
               '', SAP Posted: '' || :V_SAP_POSTED || '', Avg charges: $'' || :V_AVG_CHARGES ||
               '', Open fraud alerts: '' || :V_OPEN_ALERTS;
    V_PROMPT := ''Return ONLY a JSON object (no markdown, no explanation). Stats: '' || :V_STATS ||
                ''. Format: {"status":"SUCCESS","insights":[{"category":"RISK","priority":"HIGH","title":"...","insight":"..."},{"category":"OPPORTUNITY","priority":"MEDIUM","title":"...","insight":"..."},{"category":"TREND","priority":"LOW","title":"...","insight":"..."}],"data_summary":"..."}'';
    V_START_TS := CURRENT_TIMESTAMP();
    BEGIN
        SELECT SNOWFLAKE.CORTEX.COMPLETE(''llama3-8b'', :V_PROMPT) INTO V_RAW;
        V_CALL_STATUS := ''SUCCESS'';
        V_START_POS := POSITION(''{'' IN V_RAW);
        V_END_POS := LENGTH(V_RAW) - POSITION(''}'' IN REVERSE(V_RAW)) + 1;
        IF (V_START_POS > 0 AND V_END_POS > V_START_POS) THEN
            V_INSIGHTS := SUBSTRING(V_RAW, V_START_POS, V_END_POS - V_START_POS + 1);
        ELSE
            V_INSIGHTS := ''{"status":"SUCCESS","insights":[{"category":"RISK","priority":"HIGH","title":"Pending Backlog","insight":"'' || :V_HIGH_RISK || '' pending shipments need review"}],"data_summary":"'' || :V_STATS || ''"}'';
        END IF;
    EXCEPTION
        WHEN OTHER THEN
            V_CALL_STATUS := ''ERROR''; V_RAW := '''';
            V_INSIGHTS := ''{"status":"SUCCESS","insights":[{"category":"RISK","priority":"HIGH","title":"Pending Backlog","insight":"'' || :V_HIGH_RISK || '' pending shipments need review"}],"data_summary":"'' || :V_STATS || ''"}'';
    END;
    V_ELAPSED_MS := DATEDIFF(''millisecond'', :V_START_TS, CURRENT_TIMESTAMP());
    V_IN_TOKENS := CEIL(LENGTH(:V_PROMPT) / 4.0);
    V_OUT_TOKENS := CEIL(LENGTH(NVL(:V_RAW, '''')) / 4.0);
    INSERT INTO AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, PROMPT, RESPONSE, INPUT_TOKENS, OUTPUT_TOKENS, TOTAL_TOKENS, LATENCY_MS, CALL_STATUS, CONTEXT, PROCEDURE_NAME, STATUS)
    VALUES (CURRENT_TIMESTAMP(), ''llama3-8b'', LEFT(:V_PROMPT, 5000), LEFT(:V_INSIGHTS, 10000),
            :V_IN_TOKENS, :V_OUT_TOKENS, :V_IN_TOKENS + :V_OUT_TOKENS,
            :V_ELAPSED_MS, :V_CALL_STATUS, ''AI_GENERATE_INSIGHTS'', ''AI_GENERATE_INSIGHTS'', :V_CALL_STATUS);
    RETURN :V_INSIGHTS;
END
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.BATCH_CHECK_COMPLIANCE("P_HOURS" NUMBER(38,0) DEFAULT 24, "P_BATCH_SIZE" NUMBER(38,0) DEFAULT 50)
RETURNS VARIANT
LANGUAGE SQL
COMMENT='Set-based compliance scoring for up to P_BATCH_SIZE still-unchecked B/Ls. P_HOURS <= 0 or NULL means all time. The previous version evaluated nothing: it counted existing flags and treated NULL as passed, so it reported 10,017 passed for shipments that had never been checked.'
EXECUTE AS OWNER
AS '
DECLARE
  v_checked   NUMBER DEFAULT 0;
  v_passed    NUMBER DEFAULT 0;
  v_failed    NUMBER DEFAULT 0;
  v_remaining NUMBER DEFAULT 0;
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE TMP_COMPLIANCE_BATCH AS
  SELECT b.BL_ID,
         NOT COALESCE(r.RESTRICTED, FALSE) AS COMPLIANT,
         TO_JSON(ARRAY_CONSTRUCT_COMPACT(
             IFF(COALESCE(r.RESTRICTED, FALSE), ''RESTRICTED_HS_CODE'', NULL),
             IFF(b.GROSS_WEIGHT_KGS > 50000, ''OVERWEIGHT'', NULL),
             IFF(COALESCE(b.IS_DANGEROUS_GOODS, FALSE), ''DANGEROUS_GOODS'', NULL))) AS VIOLATIONS,
         IFF(COALESCE(r.RESTRICTED, FALSE), 30, 0)
           + IFF(COALESCE(b.IS_DANGEROUS_GOODS, FALSE), 20, 0)
           + IFF(b.GROSS_WEIGHT_KGS > 50000, 10, 0) AS RISK_SCORE
  FROM MENDIX_APP.AGENTS.BILL_OF_LADING b
  LEFT JOIN (SELECT HS_CODE, MAX(IS_RESTRICTED OR REQUIRES_PERMIT) AS RESTRICTED
             FROM MENDIX_APP.AGENTS.HS_CODE_REFERENCE GROUP BY HS_CODE) r
         ON r.HS_CODE = b.HS_CODE
  WHERE b.COMPLIANCE_CHECK_PASSED IS NULL
    AND (:P_HOURS IS NULL OR :P_HOURS <= 0
         OR b.CREATED_AT >= DATEADD(''hour'', -1 * :P_HOURS, CURRENT_TIMESTAMP()))
  ORDER BY b.CREATED_AT DESC NULLS LAST
  LIMIT :P_BATCH_SIZE;

  INSERT INTO MENDIX_APP.AGENTS.COMPLIANCE_CHECK_RESULT
      (BL_ID, COMPLIANT, VIOLATIONS, RISK_SCORE, RULES_CHECKED)
  SELECT BL_ID, COMPLIANT, VIOLATIONS, RISK_SCORE, 3 FROM TMP_COMPLIANCE_BATCH;
  v_checked := SQLROWCOUNT;

  UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING b
     SET COMPLIANCE_CHECK_PASSED = t.COMPLIANT
    FROM TMP_COMPLIANCE_BATCH t
   WHERE b.BL_ID = t.BL_ID;

  SELECT NVL(SUM(IFF(COMPLIANT, 1, 0)), 0), NVL(SUM(IFF(COMPLIANT, 0, 1)), 0)
    INTO :v_passed, :v_failed
  FROM TMP_COMPLIANCE_BATCH;

  v_remaining := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.BILL_OF_LADING
                  WHERE COMPLIANCE_CHECK_PASSED IS NULL);

  RETURN OBJECT_CONSTRUCT(''passed'', :v_passed, ''failed'', :v_failed,
                          ''total'', :v_checked, ''not_checked_remaining'', :v_remaining);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.BATCH_CLASSIFY("P_LIMIT" NUMBER(38,0) DEFAULT 20)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    RETURN OBJECT_CONSTRUCT(''classified'', 0, ''message'', ''No unclassified documents found'');
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHAT_MESSAGE_SAVE("P_SESSION_ID" NUMBER(38,0), "P_ROLE" VARCHAR, "P_CONTENT" VARCHAR DEFAULT null, "P_SQL" VARCHAR DEFAULT null, "P_RESULT_JSON" VARCHAR DEFAULT null, "P_ROWS" NUMBER(38,0) DEFAULT null, "P_LATENCY_MS" NUMBER(38,0) DEFAULT null)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_TURN  NUMBER;
  V_OWNER VARCHAR;
BEGIN
  V_OWNER := (SELECT USER_ID FROM MENDIX_APP.AGENTS.CHAT_SESSION WHERE SESSION_ID = :P_SESSION_ID);
  IF (V_OWNER IS NULL) THEN
    RETURN ''ERROR: session not found'';
  END IF;
  IF (V_OWNER <> CURRENT_USER()) THEN
    RETURN ''ERROR: not your session'';
  END IF;
  V_TURN := (SELECT COALESCE(MAX(TURN_INDEX), -1) + 1 FROM MENDIX_APP.AGENTS.CHAT_MESSAGE WHERE SESSION_ID = :P_SESSION_ID);
  INSERT INTO MENDIX_APP.AGENTS.CHAT_MESSAGE
    (SESSION_ID, TURN_INDEX, ROLE, CONTENT, SQL_TEXT, RESULT_JSON, ROW_COUNT, LATENCY_MS, CREATED_AT)
  SELECT :P_SESSION_ID, :V_TURN, :P_ROLE, :P_CONTENT, :P_SQL, :P_RESULT_JSON, :P_ROWS, :P_LATENCY_MS, CURRENT_TIMESTAMP();
  UPDATE MENDIX_APP.AGENTS.CHAT_SESSION
     SET MESSAGE_COUNT = COALESCE(MESSAGE_COUNT, 0) + 1,
         SESSION_END   = CURRENT_TIMESTAMP(),
         TITLE = CASE WHEN TITLE IS NULL AND :P_ROLE = ''user'' THEN LEFT(:P_CONTENT, 120) ELSE TITLE END
   WHERE SESSION_ID = :P_SESSION_ID;
  RETURN ''OK:'' || :V_TURN;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHAT_SESSION_DELETE("P_SESSION_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_OWNER VARCHAR;
BEGIN
  V_OWNER := (SELECT USER_ID FROM MENDIX_APP.AGENTS.CHAT_SESSION WHERE SESSION_ID = :P_SESSION_ID);
  IF (V_OWNER IS NULL) THEN
    RETURN ''ERROR: session not found'';
  END IF;
  IF (V_OWNER <> CURRENT_USER()) THEN
    RETURN ''ERROR: not your session'';
  END IF;
  DELETE FROM MENDIX_APP.AGENTS.CHAT_MESSAGE WHERE SESSION_ID = :P_SESSION_ID;
  DELETE FROM MENDIX_APP.AGENTS.CHAT_SESSION WHERE SESSION_ID = :P_SESSION_ID;
  RETURN ''DELETED'';
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHAT_SESSION_LIST()
RETURNS TABLE ("SESSION_ID" NUMBER(38,0), "TITLE" VARCHAR, "MESSAGE_COUNT" NUMBER(38,0), "LANGUAGE" VARCHAR, "SESSION_START" TIMESTAMP_NTZ(9), "SESSION_END" TIMESTAMP_NTZ(9))
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  RS RESULTSET;
BEGIN
  RS := (
    SELECT SESSION_ID,
           COALESCE(TITLE, ''Untitled conversation'') AS TITLE,
           COALESCE(MESSAGE_COUNT, 0) AS MESSAGE_COUNT,
           LANGUAGE, SESSION_START, SESSION_END
    FROM MENDIX_APP.AGENTS.CHAT_SESSION
    WHERE USER_ID = CURRENT_USER()
      AND COALESCE(MESSAGE_COUNT, 0) > 0
    ORDER BY COALESCE(SESSION_END, SESSION_START) DESC
    LIMIT 20
  );
  RETURN TABLE(RS);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHAT_SESSION_LOAD("P_SESSION_ID" NUMBER(38,0))
RETURNS TABLE ("TURN_INDEX" NUMBER(38,0), "ROLE" VARCHAR, "CONTENT" VARCHAR, "SQL_TEXT" VARCHAR, "RESULT_JSON" VARCHAR, "ROW_COUNT" NUMBER(38,0), "LATENCY_MS" NUMBER(38,0), "CREATED_AT" TIMESTAMP_NTZ(9))
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  RS RESULTSET;
BEGIN
  RS := (
    SELECT m.TURN_INDEX, m.ROLE, m.CONTENT, m.SQL_TEXT, m.RESULT_JSON,
           m.ROW_COUNT, m.LATENCY_MS, m.CREATED_AT
    FROM MENDIX_APP.AGENTS.CHAT_MESSAGE m
    JOIN MENDIX_APP.AGENTS.CHAT_SESSION s ON s.SESSION_ID = m.SESSION_ID
    WHERE m.SESSION_ID = :P_SESSION_ID
      AND s.USER_ID = CURRENT_USER()
    ORDER BY m.TURN_INDEX
  );
  RETURN TABLE(RS);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHAT_SESSION_NEW("P_LANG" VARCHAR DEFAULT 'EN')
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_ID NUMBER;
BEGIN
  -- The identity default was removed from CHAT_SESSION.SESSION_ID so that this
  -- sequence is the single id generator. Do not re-add an autoincrement here:
  -- Snowflake identity allocates in blocks and is not monotonic, so deriving the
  -- new id with MAX(SESSION_ID) could return a different, pre-existing session.
  V_ID := (SELECT MENDIX_APP.AGENTS.CHAT_SESSION_SEQ.NEXTVAL);
  INSERT INTO MENDIX_APP.AGENTS.CHAT_SESSION
    (SESSION_ID, USER_ID, SESSION_START, MESSAGE_COUNT, LANGUAGE, TOKENS_USED, CREATED_AT, TITLE)
  SELECT :V_ID, CURRENT_USER(), CURRENT_TIMESTAMP(), 0, :P_LANG, 0, CURRENT_TIMESTAMP(), NULL;
  RETURN :V_ID;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHAT_SESSION_RENAME("P_SESSION_ID" NUMBER(38,0), "P_TITLE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  V_OWNER VARCHAR;
BEGIN
  V_OWNER := (SELECT USER_ID FROM MENDIX_APP.AGENTS.CHAT_SESSION WHERE SESSION_ID = :P_SESSION_ID);
  IF (V_OWNER IS NULL) THEN
    RETURN ''ERROR: session not found'';
  END IF;
  IF (V_OWNER <> CURRENT_USER()) THEN
    RETURN ''ERROR: not your session'';
  END IF;
  UPDATE MENDIX_APP.AGENTS.CHAT_SESSION SET TITLE = LEFT(:P_TITLE, 120) WHERE SESSION_ID = :P_SESSION_ID;
  RETURN ''RENAMED'';
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHAT_WITH_DATA("USER_MESSAGE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Conversational BI: classifies intent, generates SQL via AI, executes live, summarizes result.'
EXECUTE AS CALLER
AS '
DECLARE
  intent VARCHAR; generated_sql VARCHAR; clean_sql VARCHAR; wrapped_sql VARCHAR;
  result_text VARCHAR; final_answer VARCHAR;
  schema_context VARCHAR DEFAULT
    ''You must ALWAYS use fully-qualified table names in the exact form MENDIX_APP.AGENTS.<TABLE_NAME>. Available tables:'' || chr(10) ||
    ''- MENDIX_APP.AGENTS.BILL_OF_LADING (shipments): BL_ID, BL_NUMBER, SHIPPER_NAME, CONSIGNEE_NAME, PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE, VESSEL_NAME, CARRIER_NAME, HS_CODE, GROSS_WEIGHT_KGS, VOLUME_CBM, TOTAL_CHARGES, FREIGHT_AMOUNT, STATUS, IS_DANGEROUS_GOODS, COMPLIANCE_CHECK_PASSED, FRAUD_CHECK_PASSED, BL_DATE, ETD, ETA'' || chr(10) ||
    ''- MENDIX_APP.AGENTS.PORT_MASTER (seaports): PORT_CODE, PORT_NAME, COUNTRY, COUNTRY_CODE, PORT_TYPE, IS_ACTIVE'' || chr(10) ||
    ''- MENDIX_APP.AGENTS.VESSEL_REGISTRY: VESSEL_NAME, IMO_NUMBER, FLAG, GROSS_TONNAGE, VESSEL_TYPE, OPERATOR_NAME, IS_ACTIVE'' || chr(10) ||
    ''- MENDIX_APP.AGENTS.HS_CODE_REFERENCE: HS_CODE, DESCRIPTION, CATEGORY, IS_DANGEROUS_GOODS, IS_RESTRICTED'' || chr(10) ||
    ''- MENDIX_APP.AGENTS.FRAUD_ALERT: ALERT_ID, BL_ID, ALERT_TYPE, SEVERITY, STATUS, DESCRIPTION, DETECTED_AT'' || chr(10) ||
    ''Write PLAIN standard SQL only (SELECT/JOIN/WHERE/GROUP BY/ORDER BY), every table reference fully qualified. NOTE: country/port question ambiguous between PORT_OF_LOADING (origin) and PORT_OF_DISCHARGE (destination) - prefer PORT_OF_DISCHARGE as default.'';
BEGIN
  SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
    ''Classify this message as either DATA_QUERY or CONVERSATION. DATA_QUERY: asks about shipments, carriers, ports, vessels, revenue, status, routes, statistics. CONVERSATION: greetings, thanks, general chat. Reply ONLY the word.'' || chr(10) || ''Message: '' || :user_message
  ) INTO :intent;
  intent := TRIM(intent);
  IF (intent LIKE ''%CONVERSATION%'') THEN
    SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
      ''You are VF Logistics AI Assistant. Be helpful, friendly, professional. Respond in same language as user. Never provide DELETE/DROP/TRUNCATE/UPDATE SQL. IMPORTANT: if your main answer is NOT in English, append a short English translation on a new line prefixed with "[EN]: ".'' || chr(10) || ''User: '' || :user_message
    ) INTO :final_answer;
    RETURN final_answer;
  END IF;
  SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
    ''You are a Snowflake SQL generator. Write ONE single read-only SQL statement. Return ONLY the raw SQL: no markdown, no backticks, no explanation, no trailing semicolon. Must start with SELECT or WITH. If modify/delete requested, write: SELECT ''''REFUSED'''' AS refused.'' || chr(10) || :schema_context || chr(10) || ''Question: '' || :user_message
  ) INTO :generated_sql;
  clean_sql := TRIM(generated_sql);
  clean_sql := REGEXP_REPLACE(clean_sql, ''^```sql|^```|```$'', '''');
  clean_sql := REGEXP_REPLACE(clean_sql, '';\\s*$'', '''');
  clean_sql := TRIM(clean_sql);
  IF (NOT (clean_sql ILIKE ''SELECT%'' OR clean_sql ILIKE ''WITH%'')) THEN
    RETURN ''Sorry, I could not build a valid query for this question.'';
  END IF;
  IF (clean_sql ILIKE ''%INSERT %'' OR clean_sql ILIKE ''%UPDATE %'' OR clean_sql ILIKE ''%DELETE %'' OR clean_sql ILIKE ''%DROP %'' OR clean_sql ILIKE ''%ALTER %'' OR clean_sql ILIKE ''%CREATE %'' OR clean_sql ILIKE ''%MERGE %'' OR clean_sql ILIKE ''%GRANT %'' OR clean_sql ILIKE ''%TRUNCATE%'') THEN
    RETURN ''Sorry, I cannot run this query for data safety reasons.'';
  END IF;
  IF (clean_sql ILIKE ''%REFUSED%'') THEN
    RETURN ''Sorry, I cannot modify or delete data. Please contact an administrator.'';
  END IF;
  wrapped_sql := ''SELECT COALESCE(LISTAGG(TO_JSON(OBJECT_CONSTRUCT(*)), '''''' || chr(10) || ''''''), ''''(no rows returned)'''') FROM (SELECT * FROM ('' || clean_sql || '') LIMIT 30)'';
  BEGIN
    LET res RESULTSET := (EXECUTE IMMEDIATE :wrapped_sql);
    LET cur CURSOR FOR res;
    OPEN cur; FETCH cur INTO result_text; CLOSE cur;
  EXCEPTION
    WHEN OTHER THEN
      RETURN ''Sorry, I could not query this data. Could you try rephrasing your question?'';
  END;
  SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
    ''You are VF Logistics AI data analyst. Answer using ONLY this data, be specific with numbers, respond in the same language as the user question. If data says (no rows returned), say politely there is no data found. If your main answer is NOT in English, append English translation on new line prefixed with "[EN]: ".'' || chr(10) ||
    ''Question: '' || :user_message || chr(10) || ''SQL executed: '' || :clean_sql || chr(10) || ''Query result data: '' || :result_text
  ) INTO :final_answer;
  RETURN final_answer;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHECK_AI_BUDGET()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_TODAY_COST FLOAT; V_THRESHOLD FLOAT;
BEGIN
    SELECT COALESCE(SUM(TOTAL_TOKENS * 0.0000015), 0) INTO V_TODAY_COST
    FROM AI_CALL_LOG WHERE DATE(CALL_TIMESTAMP) = CURRENT_DATE();
    SELECT CONFIG_VALUE::FLOAT INTO V_THRESHOLD FROM APP_CONFIG WHERE CONFIG_KEY = ''DAILY_COST_ALERT_USD'';
    IF (V_TODAY_COST > V_THRESHOLD) THEN
        RETURN ''{"status":"OVER_BUDGET","cost":'' || :V_TODAY_COST || '',"threshold":'' || :V_THRESHOLD || ''}'';
    ELSE
        RETURN ''{"status":"OK","cost":'' || :V_TODAY_COST || '',"threshold":'' || :V_THRESHOLD || '',"remaining":'' || (:V_THRESHOLD - :V_TODAY_COST) || ''}'';
    END IF;
END;
';
