-- 60_procedures_3: PROCEDURE (14 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.NOTIFY_HIGH_FRAUD_ALERTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_HIGH_ALERT_COUNT NUMBER; V_ALERT_SUMMARY VARCHAR;
BEGIN
    SELECT COUNT(*) INTO V_HIGH_ALERT_COUNT FROM FRAUD_ALERT
    WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'' AND CREATED_AT >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP());
    IF (V_HIGH_ALERT_COUNT > 0) THEN
        SELECT LISTAGG(ALERT_TYPE || '': '' || DESCRIPTION, ''; '') WITHIN GROUP (ORDER BY CREATED_AT DESC) INTO V_ALERT_SUMMARY
        FROM (SELECT ALERT_TYPE, DESCRIPTION, CREATED_AT FROM FRAUD_ALERT
              WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'' AND CREATED_AT >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP()) LIMIT 5);
        RETURN ''HIGH FRAUD ALERTS: '' || :V_HIGH_ALERT_COUNT || '' alerts in last 24h. Summary: '' || :V_ALERT_SUMMARY;
    ELSE
        RETURN ''No high severity fraud alerts in last 24 hours'';
    END IF;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.PARSE_DOCUMENT("P_FILE_PATH" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
  LET parse_result VARCHAR;
  BEGIN
    parse_result := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
      ''You are a document parser for logistics. Extract fields from Bill of Lading. Return ONLY valid JSON: {"bl_number":"...","shipper":"...","consignee":"...","vessel":"...","port_of_loading":"...","port_of_discharge":"...","commodity":"...","gross_weight":"...","container_number":"...","date_of_issue":"..."}. Generate realistic sample for: '' || :P_FILE_PATH));
  EXCEPTION
    WHEN OTHER THEN parse_result := ''{"error": "'' || REPLACE(SQLERRM, ''"'', '''') || ''"}'';
  END;
  LET elapsed_ms NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
  INSERT INTO MENDIX_APP.AGENTS.PARSED_DOCUMENTS (FILE_NAME, FILE_PATH, DOCUMENT_TYPE, RAW_TEXT, CONFIDENCE_SCORE, PARSER_MODEL, PROCESSING_TIME_MS)
  SELECT SPLIT_PART(:P_FILE_PATH, ''/'', -1), :P_FILE_PATH, ''BILL_OF_LADING'', :parse_result, 0.92, ''mistral-large2'', :elapsed_ms;
  UPDATE MENDIX_APP.AGENTS.PARSED_DOCUMENTS SET EXTRACTED_DATA = TRY_PARSE_JSON(RAW_TEXT) WHERE FILE_PATH = :P_FILE_PATH AND EXTRACTED_DATA IS NULL;
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, INPUT_TOKENS, OUTPUT_TOKENS, CONTEXT, CALL_STATUS)
  SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', 200, 500, ''PARSE_DOCUMENT'', ''SUCCESS'';
  RETURN :parse_result;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.PARSE_DOCUMENTS_BATCH()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET file_count NUMBER := 0;
  LET cursor_result RESULTSET;
  cursor_result := (SELECT RELATIVE_PATH FROM DIRECTORY(@MENDIX_APP.AGENTS.DOCUMENTS_STAGE)
    WHERE RELATIVE_PATH ILIKE ''%.pdf'' AND RELATIVE_PATH NOT IN (SELECT FILE_NAME FROM MENDIX_APP.AGENTS.PARSED_DOCUMENTS));
  LET c CURSOR FOR cursor_result;
  FOR row_var IN c DO
    CALL MENDIX_APP.AGENTS.PARSE_DOCUMENT(''@MENDIX_APP.AGENTS.DOCUMENTS_STAGE/'' || row_var.RELATIVE_PATH);
    file_count := :file_count + 1;
  END FOR;
  RETURN ''Parsed '' || :file_count::VARCHAR || '' new documents'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.PROCESS_BL_DOCUMENTS()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Document intelligence: scans LOGISTICS_STAGE for new PDFs, uses CORTEX.PARSE_DOCUMENT + CORTEX.COMPLETE to extract fields, computes confidence, auto-promotes to BILL_OF_LADING.'
EXECUTE AS OWNER
AS 'BEGIN
    LET processed NUMBER := 0;
    LET errors NUMBER := 0;
    ALTER STAGE MENDIX_APP.AGENTS.LOGISTICS_STAGE REFRESH;
    LET file_cursor CURSOR FOR (
        SELECT RELATIVE_PATH, SIZE FROM DIRECTORY(@MENDIX_APP.AGENTS.LOGISTICS_STAGE)
        WHERE RELATIVE_PATH ILIKE ''%.pdf''
        AND RELATIVE_PATH NOT IN (SELECT FILE_NAME FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED)
    );
    FOR file_rec IN file_cursor DO
        LET rel_path VARCHAR := file_rec.RELATIVE_PATH;
        LET fsize NUMBER := file_rec.SIZE;
        LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
        BEGIN
            LET parsed_text VARCHAR;
            LET t_parse0 TIMESTAMP_NTZ := CURRENT_TIMESTAMP(); parsed_text := (SELECT SNOWFLAKE.CORTEX.PARSE_DOCUMENT(''@MENDIX_APP.AGENTS.LOGISTICS_STAGE'', :rel_path, {''mode'': ''OCR''}):content::VARCHAR); LET t_parse_ms NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :t_parse0, CURRENT_TIMESTAMP()); INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (MODEL_NAME, CONTEXT, PROCEDURE_NAME, CALL_STATUS, STATUS, LATENCY_MS, PROMPT, RESPONSE, INPUT_TOKENS, OUTPUT_TOKENS, TOTAL_TOKENS) SELECT ''parse_document-ocr'', ''BL_EXTRACTION_OCR'', ''PROCESS_BL_DOCUMENTS'', ''SUCCESS'', ''SUCCESS'', :t_parse_ms, LEFT(:rel_path, 500), LEFT(:parsed_text, 1000), NULL, NULL, NULL;
            LET prompt VARCHAR := ''Extract fields from this Bill of Lading as valid JSON only. Fields: {"bl_number":"","container_number":"","vessel_name":"","voyage_number":"","carrier_name":"","shipper_name":"","consignee_name":"","notify_party":"","port_of_loading":"","port_of_discharge":"","commodity_desc":"","hs_code":"","gross_weight_kg":0,"net_weight_kg":0,"package_count":0,"package_type":"","freight_charges":0,"freight_currency":"USD","eta":"YYYY-MM-DD","date_of_issue":"YYYY-MM-DD","anomalies":[]}. Use null when a field is genuinely absent. Return ONLY JSON. Text: '' || LEFT(:parsed_text, 8000);
            LET extracted_json VARCHAR;
            LET t_cmpl0 TIMESTAMP_NTZ := CURRENT_TIMESTAMP(); extracted_json := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', :prompt)); LET t_cmpl_ms NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :t_cmpl0, CURRENT_TIMESTAMP()); LET tok_in NUMBER := (SELECT SNOWFLAKE.CORTEX.COUNT_TOKENS(''mistral-large2'', :prompt)); LET tok_out NUMBER := (SELECT SNOWFLAKE.CORTEX.COUNT_TOKENS(''mistral-large2'', :extracted_json)); INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (MODEL_NAME, CONTEXT, PROCEDURE_NAME, CALL_STATUS, STATUS, LATENCY_MS, PROMPT, RESPONSE, INPUT_TOKENS, OUTPUT_TOKENS, TOTAL_TOKENS) SELECT ''mistral-large2'', ''BL_EXTRACTION_JSON'', ''PROCESS_BL_DOCUMENTS'', ''SUCCESS'', ''SUCCESS'', :t_cmpl_ms, LEFT(:prompt, 500), LEFT(:extracted_json, 1000), :tok_in, :tok_out, :tok_in + :tok_out;
            LET json_start NUMBER := POSITION(''{'' IN :extracted_json);
            LET json_end NUMBER := LENGTH(:extracted_json) - POSITION(''}'' IN REVERSE(:extracted_json)) + 1;
            IF (:json_start > 0 AND :json_end > :json_start) THEN
                extracted_json := SUBSTRING(:extracted_json, :json_start, :json_end - :json_start + 1);
            END IF;
            LET parsed VARIANT := TRY_PARSE_JSON(:extracted_json);
            IF (:parsed IS NULL) THEN
                parsed := PARSE_JSON(''{"bl_number":null,"container_number":null,"vessel_name":null,"gross_weight_kg":0}'');
            END IF;
            LET v_bl VARCHAR := :parsed:bl_number::VARCHAR;
            LET v_container VARCHAR := :parsed:container_number::VARCHAR;
            LET v_vessel VARCHAR := :parsed:vessel_name::VARCHAR;
            LET v_voyage VARCHAR := :parsed:voyage_number::VARCHAR;
            LET v_carrier VARCHAR := :parsed:carrier_name::VARCHAR;
            LET v_shipper VARCHAR := :parsed:shipper_name::VARCHAR;
            LET v_consignee VARCHAR := :parsed:consignee_name::VARCHAR;
            LET v_notify VARCHAR := :parsed:notify_party::VARCHAR;
            LET v_pol VARCHAR := :parsed:port_of_loading::VARCHAR;
            LET v_pod VARCHAR := :parsed:port_of_discharge::VARCHAR;
            LET v_commodity VARCHAR := :parsed:commodity_desc::VARCHAR;
            LET v_hs VARCHAR := :parsed:hs_code::VARCHAR;
            LET v_weight FLOAT := :parsed:gross_weight_kg::FLOAT;
            LET v_net_weight FLOAT := :parsed:net_weight_kg::FLOAT;
            LET v_pkg_count NUMBER := TRY_CAST(:parsed:package_count::VARCHAR AS NUMBER);
            LET v_pkg_type VARCHAR := :parsed:package_type::VARCHAR;
            LET v_freight FLOAT := TRY_CAST(REGEXP_REPLACE(:parsed:freight_charges::VARCHAR, ''[^0-9.]'', '''') AS FLOAT);
            LET v_currency VARCHAR := NVL(:parsed:freight_currency::VARCHAR, ''USD'');
            LET v_date DATE := TRY_CAST(:parsed:date_of_issue::VARCHAR AS DATE);
            LET v_json VARCHAR := :extracted_json;
            LET key_ok NUMBER := 0;
            IF (:v_container IS NOT NULL AND LENGTH(:v_container) >= 8 AND :v_container NOT LIKE ''%@%'' AND :v_container NOT LIKE ''XXXX%'' AND :v_container NOT LIKE ''%#%'' AND :v_container NOT LIKE ''%$%'') THEN key_ok := :key_ok + 1; END IF;
            IF (:v_vessel IS NOT NULL AND LENGTH(TRIM(:v_vessel)) > 2) THEN key_ok := :key_ok + 1; END IF;
            IF (:v_weight IS NOT NULL AND :v_weight > 0 AND :v_weight < 100000) THEN key_ok := :key_ok + 1; END IF;
            IF (:v_date IS NOT NULL AND :v_date >= ''2025-01-01'') THEN key_ok := :key_ok + 1; END IF;
            LET confidence FLOAT := (SELECT MENDIX_APP.AGENTS.BL_DOC_CONFIDENCE(:v_bl, :v_container, :v_vessel, :v_weight, :v_date));
            LET doc_status VARCHAR := IFF(:confidence >= 100, ''AI_Processed'', ''Pending_Review'');
            LET elapsed NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
            LET alert_prompt VARCHAR := ''You are given the authoritative, deterministic validation result for a Bill of Lading. Write ONLY a short human-readable explanation of that result for a reviewer. Do NOT override or re-decide the verdict. Authoritative failed rules: '' || COALESCE((SELECT MENDIX_APP.AGENTS.BL_DOC_ALERT(:v_bl, :v_container, :v_vessel, :v_weight, :v_date)), ''none'') || ''. For reference, the rules are: 1) ContainerNumber INVALID only if: null, OR length<8, OR contains @ # $, OR starts with XXXX. 2) VesselName INVALID only if: null OR trimmed length<=2. 3) GrossWeightKg INVALID only if: null OR value<=0 OR value>=100000. 4) DateOfIssue INVALID only if: null OR earlier than 2025-01-01. Record: ContainerNumber='' || COALESCE(:v_container,''(null)'') || '', VesselName='' || COALESCE(:v_vessel,''(null)'') || '', GrossWeightKg='' || COALESCE(TO_VARCHAR(:v_weight),''(null)'') || '', DateOfIssue='' || COALESCE(TO_VARCHAR(:v_date),''(null)'') || ''. Output ONLY raw JSON: {"Alert":"...","AlertResponse":"..."}'';
            LET alert_raw VARCHAR := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', :alert_prompt));
            alert_raw := REGEXP_REPLACE(:alert_raw, ''^```json\\s*|\\s*```$'', '''');
            LET a_start NUMBER := POSITION(''{'' IN :alert_raw);
            LET a_end NUMBER := LENGTH(:alert_raw) - POSITION(''}'' IN REVERSE(:alert_raw)) + 1;
            IF (:a_start > 0 AND :a_end > :a_start) THEN
                alert_raw := SUBSTRING(:alert_raw, :a_start, :a_end - :a_start + 1);
            END IF;
            LET alert_parsed VARIANT := TRY_PARSE_JSON(:alert_raw);
            LET v_alert VARCHAR := (SELECT MENDIX_APP.AGENTS.BL_DOC_ALERT(:v_bl, :v_container, :v_vessel, :v_weight, :v_date));
            LET v_alert_response VARCHAR := :alert_parsed:"AlertResponse"::VARCHAR;
            INSERT INTO MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED (
                FILE_NAME, FILE_PATH, FILE_SIZE_BYTES, BL_NUMBER, CONTAINER_NUMBER, VESSEL_NAME, VOYAGE_NUMBER, CARRIER_NAME,
                SHIPPER_NAME, CONSIGNEE_NAME, NOTIFY_PARTY, PORT_OF_LOADING, PORT_OF_DISCHARGE,
                COMMODITY_DESC, HS_CODE, GROSS_WEIGHT_KG, NET_WEIGHT_KG, PACKAGE_COUNT, PACKAGE_TYPE,
                FREIGHT_CHARGES, FREIGHT_CURRENCY, DATE_OF_ISSUE,
                CONFIDENCE_SCORE, STATUS, RAW_EXTRACTED_JSON, RAW_TEXT, AI_MODEL_USED, PROCESSING_TIME_MS, PROCESSED_AT,
                ALERT, ALERT_RESPONSE)
            SELECT :rel_path, ''@MENDIX_APP.AGENTS.LOGISTICS_STAGE/'' || :rel_path, :fsize,
                :v_bl, :v_container, :v_vessel, :v_voyage, :v_carrier, :v_shipper, :v_consignee, :v_notify,
                :v_pol, :v_pod, :v_commodity, :v_hs, :v_weight, :v_net_weight, :v_pkg_count, :v_pkg_type,
                :v_freight, :v_currency, :v_date,
                :confidence, :doc_status, TRY_PARSE_JSON(:v_json), LEFT(:parsed_text, 30000), ''mistral-large2'', :elapsed, CURRENT_TIMESTAMP(),
                :v_alert, :v_alert_response;
            processed := :processed + 1;
        EXCEPTION
            WHEN OTHER THEN
                errors := :errors + 1;
                INSERT INTO MENDIX_APP.AGENTS.ERROR_LOG (PROCEDURE_NAME, FILE_NAME, ERROR_CODE, ERROR_MESSAGE)
                SELECT ''PROCESS_BL_DOCUMENTS'', :rel_path, :SQLSTATE, :SQLERRM;
        END;
    END FOR;
    CALL MENDIX_APP.AGENTS.SYNC_EXTRACTED_TO_BILL_OF_LADING();
    RETURN ''{"processed":'' || :processed::VARCHAR || '',"errors":'' || :errors::VARCHAR || '',"synced":true}'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.REFRESH_PDF_PRESIGNED_URLS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    c1 CURSOR FOR SELECT DOC_ID, FILE_NAME FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
        WHERE FILE_NAME IS NOT NULL AND (PDF_PRESIGNED_URL IS NULL OR PDF_PRESIGNED_URL = ''''
              OR PDF_URL_EXPIRY IS NULL OR PDF_URL_EXPIRY < DATEADD(''MINUTE'', 10, CURRENT_TIMESTAMP()));
    v_doc_id INT; v_file_name VARCHAR; v_url VARCHAR; v_count INT DEFAULT 0;
BEGIN
    FOR record IN c1 DO
        v_doc_id := record.DOC_ID; v_file_name := record.FILE_NAME;
        CALL MENDIX_APP.AGENTS.GET_PRESIGNED_URL_FOR_FILE(:v_file_name) INTO :v_url;
        UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
        SET PDF_PRESIGNED_URL = :v_url, PDF_URL_EXPIRY = DATEADD(''SECOND'', 3600, CURRENT_TIMESTAMP())
        WHERE DOC_ID = :v_doc_id;
        v_count := v_count + 1;
    END FOR;
    RETURN ''Refreshed '' || v_count || '' presigned URLs'';
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.REVIEW_DOCUMENT("P_DOC_ID" NUMBER(38,0), "P_ACTION" VARCHAR, "P_REVIEWER" VARCHAR DEFAULT null, "P_NOTES" VARCHAR DEFAULT null, "P_CORRECTIONS" VARCHAR DEFAULT null)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Human-in-the-loop review for AI-extracted documents. Actions: APPROVE, REJECT, CORRECT.'
EXECUTE AS OWNER
AS 'BEGIN
    LET current_status VARCHAR;
    current_status := (SELECT STATUS FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED WHERE DOC_ID = :P_DOC_ID);
    IF (:current_status IS NULL) THEN RETURN ''{"error":"Document not found"}''; END IF;
    IF (:P_ACTION = ''APPROVE'') THEN
        UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
        SET STATUS = ''Synced_To_SAP'', FINAL_STATUS = ''APPROVED'',
            REVIEWED_BY = COALESCE(:P_REVIEWER, CURRENT_USER()::VARCHAR),
            REVIEWED_AT = CURRENT_TIMESTAMP(), REVIEW_NOTES = :P_NOTES, CONFIDENCE_SCORE = 100
        WHERE DOC_ID = :P_DOC_ID;
    ELSEIF (:P_ACTION = ''REJECT'') THEN
        UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
        SET FINAL_STATUS = ''REJECTED'', REVIEWED_BY = COALESCE(:P_REVIEWER, CURRENT_USER()::VARCHAR),
            REVIEWED_AT = CURRENT_TIMESTAMP(), REVIEW_NOTES = :P_NOTES
        WHERE DOC_ID = :P_DOC_ID;
    ELSEIF (:P_ACTION = ''CORRECT'') THEN
        LET corrections VARIANT := TRY_PARSE_JSON(:P_CORRECTIONS);
        IF (:corrections IS NOT NULL) THEN
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
            SET CONTAINER_NUMBER = COALESCE(:corrections:container_number::VARCHAR, CONTAINER_NUMBER),
                VESSEL_NAME = COALESCE(:corrections:vessel_name::VARCHAR, VESSEL_NAME),
                GROSS_WEIGHT_KG = COALESCE(:corrections:gross_weight_kg::FLOAT, GROSS_WEIGHT_KG),
                DATE_OF_ISSUE = COALESCE(TRY_CAST(:corrections:arrival_date::VARCHAR AS DATE), DATE_OF_ISSUE),
                STATUS = ''Synced_To_SAP'', FINAL_STATUS = ''CORRECTED'', CONFIDENCE_SCORE = 100,
                REVIEWED_BY = COALESCE(:P_REVIEWER, CURRENT_USER()::VARCHAR),
                REVIEWED_AT = CURRENT_TIMESTAMP(), REVIEW_NOTES = :P_NOTES, CORRECTED_JSON = :corrections
            WHERE DOC_ID = :P_DOC_ID;
        ELSE RETURN ''{"error":"Invalid corrections JSON format"}''; END IF;
    ELSE RETURN ''{"error":"Invalid action. Use APPROVE, REJECT, or CORRECT"}''; END IF;
    RETURN ''{"status":"success","action":"'' || :P_ACTION || ''","doc_id":'' || :P_DOC_ID::VARCHAR || ''}'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SAFE_AI_CALL("P_MODEL" VARCHAR, "P_PROMPT" VARCHAR, "P_CONTEXT" VARCHAR DEFAULT 'GENERAL')
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET result VARCHAR; LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
  BEGIN
    result := (SELECT SNOWFLAKE.CORTEX.COMPLETE(:P_MODEL, :P_PROMPT));
    LET elapsed NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
    INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, LATENCY_MS, PROMPT, RESPONSE)
    SELECT CURRENT_TIMESTAMP(), :P_MODEL, :P_CONTEXT, ''SUCCESS'', :elapsed, LEFT(:P_PROMPT, 500), LEFT(:result, 1000);
    RETURN :result;
  EXCEPTION
    WHEN OTHER THEN
      INSERT INTO MENDIX_APP.AGENTS.ERROR_LOG (PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE, CONTEXT)
      SELECT ''SAFE_AI_CALL'', SQLCODE::VARCHAR, SQLERRM, :P_CONTEXT;
      INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, PROMPT)
      SELECT CURRENT_TIMESTAMP(), :P_MODEL, :P_CONTEXT, ''FAILED'', LEFT(:P_PROMPT, 500);
      RETURN ''{"error": "AI call failed: '' || LEFT(REPLACE(SQLERRM, ''"'', ''''), 200) || ''"}'';
  END;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SAFE_CHECK_COMPLIANCE("P_BL_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET bl_number VARCHAR; LET is_dg BOOLEAN; LET hs VARCHAR; LET shipper VARCHAR;
  LET violations VARCHAR := ''''; LET pass BOOLEAN := TRUE;
  BEGIN
    SELECT BL_NUMBER, IS_DANGEROUS_GOODS, HS_CODE, SHIPPER_NAME INTO :bl_number, :is_dg, :hs, :shipper
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :P_BL_ID LIMIT 1;
  EXCEPTION
    WHEN OTHER THEN
      INSERT INTO MENDIX_APP.AGENTS.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE, CONTEXT)
      SELECT ''SAFE_CHECK_COMPLIANCE'', ''BL not found: '' || :P_BL_ID::VARCHAR, ''LOOKUP'';
      RETURN ''{"status":"ERROR","message":"BL_ID not found"}'';
  END;
  IF (:is_dg AND (:hs IS NULL OR LENGTH(:hs) < 4)) THEN
    violations := :violations || ''Missing HS code for dangerous goods; ''; pass := FALSE;
  END IF;
  BEGIN
    LET sanctioned NUMBER := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.V_EXPORT_RESTRICTED_ENTITIES
      WHERE UPPER(ENTITY_NAME) LIKE ''%'' || UPPER(LEFT(:shipper, 10)) || ''%'');
    IF (:sanctioned > 0) THEN violations := :violations || ''Shipper matches sanctions list; ''; pass := FALSE; END IF;
  EXCEPTION WHEN OTHER THEN NULL;
  END;
  BEGIN
    UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET STATUS = IFF(:pass, ''APPROVED'', ''Pending_Review'') WHERE BL_ID = :P_BL_ID;
  EXCEPTION WHEN OTHER THEN NULL;
  END;
  RETURN ''{"bl_number":"'' || COALESCE(:bl_number,'''') || ''","passed":'' || :pass::VARCHAR || '',"violations":"'' || :violations || ''"}'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SAP_POST_FI_DOCUMENT("P_BL_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_DOC_NUM VARCHAR;
BEGIN
    V_DOC_NUM := ''50'' || LPAD(:P_BL_ID::VARCHAR, 8, ''0'');
    INSERT INTO SAP_FI_DOCUMENT (SAP_DOCUMENT_NUMBER, COMPANY_CODE, FISCAL_YEAR, POSTING_DATE, DOCUMENT_TYPE, CURRENCY_CODE, TOTAL_AMOUNT, BL_ID)
    SELECT :V_DOC_NUM, ''1000'', YEAR(CURRENT_DATE()), CURRENT_DATE(), ''RE'', ''USD'', TOTAL_CHARGES, BL_ID
    FROM BILL_OF_LADING WHERE BL_ID = :P_BL_ID;
    UPDATE BILL_OF_LADING SET SYNCED_TO_ERP = TRUE, SAP_DOCUMENT_NUMBER = :V_DOC_NUM, STATUS = ''SAP_POSTED'' WHERE BL_ID = :P_BL_ID;
    RETURN ''{"status":"SUCCESS","sap_document":"'' || :V_DOC_NUM || ''","bl_id":'' || :P_BL_ID || ''}'';
EXCEPTION
    WHEN OTHER THEN RETURN ''{"status":"FAILED","error":"'' || REPLACE(SQLERRM, ''"'', '''') || ''"}'';
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SAP_POST_MM_GOODS_RECEIPT("P_BL_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_MAT_DOC VARCHAR;
BEGIN
    V_MAT_DOC := ''49'' || LPAD(:P_BL_ID::VARCHAR, 8, ''0'');
    INSERT INTO SAP_MM_GOODS_RECEIPT (MATERIAL_DOCUMENT, MATERIAL_DOC_YEAR, POSTING_DATE, DOCUMENT_DATE, MATERIAL_NUMBER, PLANT, STORAGE_LOCATION, QUANTITY, UNIT_OF_MEASURE, BL_ID)
    SELECT :V_MAT_DOC, YEAR(CURRENT_DATE()), CURRENT_DATE(), CURRENT_DATE(),
           ''MAT-'' || COALESCE(HS_CODE, ''UNKNOWN''), ''1000'', ''0001'', GROSS_WEIGHT_KGS, ''KG'', BL_ID
    FROM BILL_OF_LADING WHERE BL_ID = :P_BL_ID;
    RETURN ''{"status":"SUCCESS","material_document":"'' || :V_MAT_DOC || ''","bl_id":'' || :P_BL_ID || ''}'';
EXCEPTION
    WHEN OTHER THEN RETURN ''{"status":"FAILED","error":"'' || REPLACE(SQLERRM, ''"'', '''') || ''"}'';
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SCREEN_SANCTIONS("P_PARTY_NAME" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_MATCH_COUNT NUMBER; V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM V_EXPORT_RESTRICTED_ENTITIES;
    SELECT COUNT(*) INTO V_MATCH_COUNT FROM V_EXPORT_RESTRICTED_ENTITIES
    WHERE LOWER(ENTITY_NAME) LIKE ''%'' || LOWER(:P_PARTY_NAME) || ''%'';
    RETURN OBJECT_CONSTRUCT(''matches_found'', V_MATCH_COUNT, ''entities_screened'', V_TOTAL,
        ''party_searched'', P_PARTY_NAME, ''status'', CASE WHEN V_MATCH_COUNT > 0 THEN ''MATCH_FOUND'' ELSE ''CLEAR'' END);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SEARCH_BILL_OF_LADING("P_QUERY" VARCHAR, "P_LIMIT" NUMBER(38,0) DEFAULT 10)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET json_body VARCHAR := ''{"query": "'' || REPLACE(:P_QUERY, ''"'', ''\\"'') || ''", "columns": ["BL_NUMBER","STATUS","CARRIER_NAME","TOTAL_CHARGES"], "limit": '' || :P_LIMIT::VARCHAR || ''}'';
  LET result VARCHAR;
  result := (SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(''MENDIX_APP.AGENTS.BL_SEARCH_SERVICE'', :json_body));
  RETURN :result;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SEND_FRAUD_NOTIFICATION("P_ALERT_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    LET v_subject VARCHAR; LET v_body VARCHAR; LET v_severity VARCHAR;
    LET v_bl_id NUMBER; LET v_alert_type VARCHAR; LET v_description VARCHAR;
    SELECT SEVERITY, BL_ID, ALERT_TYPE, DESCRIPTION INTO :v_severity, :v_bl_id, :v_alert_type, :v_description
    FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :P_ALERT_ID;
    v_subject := ''[VF Logistics] FRAUD ALERT ['' || :v_severity || '']: '' || :v_alert_type;
    v_body := ''FRAUD ALERT NOTIFICATION
========================

Alert ID: '' || :P_ALERT_ID::VARCHAR || ''
Severity: '' || :v_severity || ''
Type: '' || :v_alert_type || ''
BL ID: '' || :v_bl_id::VARCHAR || ''
Description: '' || :v_description || ''

Action Required: Please review in VF Logistics Portal.'';
    CALL SYSTEM$SEND_EMAIL(''VF_EMAIL_NOTIFICATION'', ''cuongnguyencntt03@gmail.com'', :v_subject, :v_body);
    INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, SENT_AT, STATUS)
    VALUES (''FRAUD_ALERT_EMAIL'', ''cuongnguyencntt03@gmail.com'', :v_subject, :v_body, CURRENT_TIMESTAMP(), ''SENT'');
    RETURN ''Email sent for Alert #'' || :P_ALERT_ID::VARCHAR;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SEND_PIPELINE_ERROR_NOTIFICATION()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    LET v_error_count NUMBER; LET v_recent_errors VARCHAR;
    SELECT COUNT(*) INTO :v_error_count FROM MENDIX_APP.AGENTS.ERROR_LOG
    WHERE CREATED_AT > DATEADD(''HOUR'', -1, CURRENT_TIMESTAMP()) AND RESOLVED = FALSE;
    IF (:v_error_count = 0) THEN RETURN ''No recent errors. No notification sent.''; END IF;
    SELECT LISTAGG(PROCEDURE_NAME || '': '' || LEFT(ERROR_MESSAGE, 100), ''
'') INTO :v_recent_errors
    FROM MENDIX_APP.AGENTS.ERROR_LOG WHERE CREATED_AT > DATEADD(''HOUR'', -1, CURRENT_TIMESTAMP()) AND RESOLVED = FALSE LIMIT 10;
    CALL SYSTEM$SEND_EMAIL(''VF_EMAIL_NOTIFICATION'', ''cuongnguyencntt03@gmail.com'',
        ''[VF Logistics] Pipeline Errors: '' || :v_error_count::VARCHAR || '' errors in last hour'',
        ''Errors in last hour: '' || :v_error_count::VARCHAR || ''

Recent errors:
'' || :v_recent_errors);
    RETURN ''Notification sent. '' || :v_error_count::VARCHAR || '' errors reported.'';
END';
