-- 60_procedures_2: PROCEDURE (14 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CHECK_COMPLIANCE("P_BL_ID" NUMBER(38,0))
RETURNS VARIANT
LANGUAGE SQL
COMMENT='Rule-based compliance scoring for one B/L. Writes COMPLIANCE_CHECK_RESULT and, unlike the previous version, also persists BILL_OF_LADING.COMPLIANCE_CHECK_PASSED so the check is observable afterwards.'
EXECUTE AS OWNER
AS '
DECLARE
  v_bl_number  VARCHAR;
  v_restricted BOOLEAN;
  v_dangerous  BOOLEAN;
  v_weight     FLOAT;
  v_issues     ARRAY;
  v_risk       NUMBER;
  v_compliant  BOOLEAN;
BEGIN
  SELECT b.BL_NUMBER,
         COALESCE(r.RESTRICTED, FALSE),
         COALESCE(b.IS_DANGEROUS_GOODS, FALSE),
         b.GROSS_WEIGHT_KGS
    INTO :v_bl_number, :v_restricted, :v_dangerous, :v_weight
  FROM MENDIX_APP.AGENTS.BILL_OF_LADING b
  LEFT JOIN (SELECT HS_CODE, MAX(IS_RESTRICTED OR REQUIRES_PERMIT) AS RESTRICTED
             FROM MENDIX_APP.AGENTS.HS_CODE_REFERENCE GROUP BY HS_CODE) r
         ON r.HS_CODE = b.HS_CODE
  WHERE b.BL_ID = :P_BL_ID;

  -- A SELECT ... INTO over zero rows leaves the variables NULL rather than
  -- raising, so this guard is reachable and is the only signal that the id
  -- does not exist.
  IF (v_bl_number IS NULL) THEN
    RETURN OBJECT_CONSTRUCT(''status'', ''NOT_FOUND'', ''bl_id'', :P_BL_ID);
  END IF;

  v_issues := ARRAY_CONSTRUCT_COMPACT(
      IFF(:v_restricted, ''RESTRICTED_HS_CODE'', NULL),
      IFF(:v_weight > 50000, ''OVERWEIGHT'', NULL),
      IFF(:v_dangerous, ''DANGEROUS_GOODS'', NULL));

  v_risk := IFF(:v_restricted, 30, 0)
          + IFF(:v_dangerous, 20, 0)
          + IFF(:v_weight > 50000, 10, 0);

  -- Dangerous goods raise the risk score but are lawful to ship when declared,
  -- so they are reported as an issue without failing the check. A restricted
  -- HS code is the only hard failure.
  v_compliant := NOT :v_restricted;

  INSERT INTO MENDIX_APP.AGENTS.COMPLIANCE_CHECK_RESULT
      (BL_ID, COMPLIANT, VIOLATIONS, RISK_SCORE, RULES_CHECKED)
  SELECT :P_BL_ID, :v_compliant, TO_JSON(:v_issues), :v_risk, 3;

  UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING
     SET COMPLIANCE_CHECK_PASSED = :v_compliant
   WHERE BL_ID = :P_BL_ID;

  -- ''status'' and ''issues'' exist because the Streamlit page reads those keys.
  -- The old version returned only ''compliant'' and ''violations'', so the page fell
  -- through to its else branch and displayed every result as FAILED, and never
  -- rendered the violation list at all.
  RETURN OBJECT_CONSTRUCT(
      ''status'',     IFF(:v_compliant, ''PASS'', ''FAIL''),
      ''bl_number'',  :v_bl_number,
      ''compliant'',  :v_compliant,
      ''risk_score'', :v_risk,
      ''issues'',     :v_issues,
      ''violations'', :v_issues,
      ''rules_checked'', 3);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CLASSIFY_BATCH("P_LIMIT" NUMBER(38,0) DEFAULT 100)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET classified_count NUMBER := 0;
  UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING t
  SET CONTAINER_TYPE = SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
    ''Classify into ONE word (Electronics/Textiles/Food/Chemicals/Machinery/Automotive/Metals/Consumer/Pharma/Other): '' || t.COMMODITY_DESCRIPTION
  )
  WHERE t.BL_ID IN (
    SELECT BL_ID FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE CONTAINER_TYPE IS NULL OR CONTAINER_TYPE = '''' LIMIT :P_LIMIT
  );
  classified_count := SQLROWCOUNT;
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, RESPONSE)
  SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', ''CLASSIFY_BATCH'', ''SUCCESS'', :classified_count::VARCHAR || '' classified'';
  RETURN :classified_count::VARCHAR || '' commodities classified'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CLASSIFY_COMMODITY("P_BL_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET commodity VARCHAR;
  LET classification VARCHAR;
  commodity := (SELECT COMMODITY_DESCRIPTION FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :P_BL_ID AND COMMODITY_DESCRIPTION IS NOT NULL AND COMMODITY_DESCRIPTION != '''' LIMIT 1);
  IF (:commodity IS NULL) THEN
    RETURN ''No commodity description found for BL_ID '' || :P_BL_ID::VARCHAR;
  END IF;
  BEGIN
    classification := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
      ''Classify into ONE category (Electronics/Textiles/Food/Chemicals/Machinery/Automotive/Raw_Materials/Consumer_Goods/Pharmaceuticals/Other). Return ONLY the category. Commodity: '' || :commodity));
  EXCEPTION
    WHEN OTHER THEN classification := ''Other'';
  END;
  classification := TRIM(REPLACE(REPLACE(:classification, ''"'', ''''), ''.'', ''''));
  UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET CONTAINER_TYPE = :classification WHERE BL_ID = :P_BL_ID;
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, PROMPT, RESPONSE)
  SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', ''CLASSIFY_COMMODITY'', ''SUCCESS'', :commodity, :classification;
  RETURN :classification;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CLASSIFY_DOCUMENT_TEXT("P_DOC_TEXT" VARCHAR)
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_PROMPT VARCHAR; V_RESPONSE VARIANT; V_DOC_TYPE VARCHAR; V_CONFIDENCE FLOAT;
BEGIN
    V_PROMPT := ''You are a document classifier for logistics. Classify this document into one of these types: BILL_OF_LADING, COMMERCIAL_INVOICE, PACKING_LIST, CERTIFICATE_OF_ORIGIN, CUSTOMS_DECLARATION, OTHER. Return JSON with "doc_type" and "confidence" (0-100). Document text: '' || P_DOC_TEXT;
    V_RESPONSE := (CALL AI_COMPLETE_WITH_RETRY(V_PROMPT, ''llama3-8b'', 2));
    V_DOC_TYPE := V_RESPONSE:doc_type::VARCHAR;
    V_CONFIDENCE := V_RESPONSE:confidence::FLOAT;
    INSERT INTO AI_CLASSIFICATION_CACHE (DOC_TEXT, DOC_TYPE, CONFIDENCE_SCORE, MODEL_NAME)
    VALUES (SUBSTRING(P_DOC_TEXT, 1, 5000), V_DOC_TYPE, V_CONFIDENCE, ''llama3-8b'');
    RETURN OBJECT_CONSTRUCT(''doc_type'', V_DOC_TYPE, ''confidence'', V_CONFIDENCE);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.CROSS_CHECK_DOCUMENTS("P_BL_ID" NUMBER(38,0))
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_DISCREPANCY_COUNT NUMBER DEFAULT 0;
BEGIN
    V_DISCREPANCY_COUNT := 0;
    RETURN OBJECT_CONSTRUCT(''discrepancies_found'', V_DISCREPANCY_COUNT, ''status'', ''OK'');
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.DETECT_DUPLICATES("P_BL_ID" NUMBER(38,0) DEFAULT null)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_DUPLICATE_COUNT NUMBER; V_ALERT_COUNT NUMBER DEFAULT 0;
BEGIN
    IF (:P_BL_ID IS NULL) THEN
        CREATE OR REPLACE TEMPORARY TABLE TEMP_DUPLICATES AS
        SELECT BL_NUMBER, COUNT(*) as DUPLICATE_COUNT,
            ARRAY_TO_STRING(ARRAY_AGG(BL_ID), '','') as AFFECTED_BL_IDS
        FROM BILL_OF_LADING WHERE BL_NUMBER IS NOT NULL GROUP BY BL_NUMBER HAVING COUNT(*) > 1;
        SELECT COUNT(*) INTO V_DUPLICATE_COUNT FROM TEMP_DUPLICATES;
        IF (V_DUPLICATE_COUNT > 0) THEN
            INSERT INTO FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, DOCUMENT_IDS, STATUS)
            SELECT ''DUPLICATE_BL_NUMBER'', ''HIGH'', ''Duplicate BL number detected: '' || BL_NUMBER, AFFECTED_BL_IDS, ''OPEN''
            FROM TEMP_DUPLICATES;
            V_ALERT_COUNT := V_DUPLICATE_COUNT;
        END IF;
    ELSE
        SELECT COUNT(*) INTO V_DUPLICATE_COUNT FROM BILL_OF_LADING
        WHERE BL_NUMBER = (SELECT BL_NUMBER FROM BILL_OF_LADING WHERE BL_ID = :P_BL_ID) AND BL_ID != :P_BL_ID;
        IF (V_DUPLICATE_COUNT > 0) THEN V_ALERT_COUNT := 1; END IF;
    END IF;
    RETURN OBJECT_CONSTRUCT(''duplicates_found'', V_DUPLICATE_COUNT, ''alerts_found'', V_ALERT_COUNT);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.ENRICH_DOCUMENT("P_BL_ID" NUMBER(38,0))
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_PORT_LOADING VARCHAR; V_PORT_DISCHARGE VARCHAR; V_DISTANCE FLOAT; V_ENRICHED_FIELDS NUMBER DEFAULT 0;
BEGIN
    SELECT PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE INTO V_PORT_LOADING, V_PORT_DISCHARGE
    FROM BILL_OF_LADING WHERE BL_ID = :P_BL_ID;
    V_DISTANCE := 5000.0; V_ENRICHED_FIELDS := 1;
    RETURN OBJECT_CONSTRUCT(''enriched_fields'', V_ENRICHED_FIELDS, ''calculated_distance_km'', V_DISTANCE);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.EVALUATE_AI_DECISIONS()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Measures AI decision quality as policy adherence against documented rubric.'
EXECUTE AS CALLER
AS '
DECLARE
    v_evaluated NUMBER; v_matches NUMBER; v_accuracy FLOAT;
    v_missed_blocks NUMBER; v_critical_fn NUMBER; v_false_pos NUMBER; v_over_escalate NUMBER;
    v_matrix VARCHAR DEFAULT '''';
BEGIN
    SELECT COUNT(*), SUM(IFF(IS_MATCH, 1, 0)),
           ROUND(100.0 * SUM(IFF(IS_MATCH, 1, 0)) / NULLIF(COUNT(*), 0), 1),
           SUM(IFF(EXPECTED_DECISION = ''BLOCK'' AND ACTUAL_DECISION <> ''BLOCK'', 1, 0)),
           SUM(IFF(EXPECTED_DECISION = ''BLOCK'' AND ACTUAL_DECISION = ''CLEAR'', 1, 0)),
           SUM(IFF(EXPECTED_DECISION = ''CLEAR'' AND ACTUAL_DECISION = ''BLOCK'', 1, 0)),
           SUM(IFF(EXPECTED_DECISION = ''ESCALATE'' AND ACTUAL_DECISION = ''BLOCK'', 1, 0))
    INTO :v_evaluated, :v_matches, :v_accuracy, :v_missed_blocks, :v_critical_fn, :v_false_pos, :v_over_escalate
    FROM MENDIX_APP.AGENTS.V_AI_DECISION_EVAL;
    SELECT LISTAGG(''{"expected":"'' || EXPECTED_DECISION || ''","actual":"'' || ACTUAL_DECISION || ''","count":'' || CNT || ''}'', '','')
    INTO :v_matrix FROM (SELECT EXPECTED_DECISION, ACTUAL_DECISION, COUNT(*) AS CNT FROM MENDIX_APP.AGENTS.V_AI_DECISION_EVAL GROUP BY 1, 2 ORDER BY 1, 2);
    RETURN ''{"evaluation":"AI_DECISION_POLICY_ADHERENCE","ground_truth":"rule-derived","decisions_evaluated":'' || NVL(:v_evaluated, 0)
        || '',"decisions_matching_policy":'' || NVL(:v_matches, 0)
        || '',"accuracy_pct":'' || NVL(:v_accuracy, 0)
        || '',"critical_false_negatives_block_treated_as_clear":'' || NVL(:v_critical_fn, 0)
        || '',"missed_blocks_any_direction":'' || NVL(:v_missed_blocks, 0)
        || '',"false_positives_clear_blocked":'' || NVL(:v_false_pos, 0)
        || '',"over_blocked_from_escalate_band":'' || NVL(:v_over_escalate, 0)
        || '',"confusion_matrix":['' || NVL(:v_matrix, '''') || '']"}'';
END
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.EXTRACT_BL_ENTITIES("P_BL_ID" NUMBER(38,0))
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET bl_text VARCHAR;
  LET extracted VARIANT;
  bl_text := (SELECT BL_NUMBER || '' | Shipper: '' || SHIPPER_NAME || '' | Consignee: '' || CONSIGNEE_NAME
      || '' | Commodity: '' || COALESCE(COMMODITY_DESCRIPTION,'''')
      || '' | Port: '' || PORT_OF_LOADING_LOCODE || '' -> '' || PORT_OF_DISCHARGE_LOCODE
      || '' | Carrier: '' || CARRIER_NAME || '' | HS: '' || COALESCE(HS_CODE,'''')
      || '' | Weight: '' || GROSS_WEIGHT_KGS::VARCHAR || ''kg | Charges: $'' || TOTAL_CHARGES::VARCHAR
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :P_BL_ID);
  IF (:bl_text IS NULL) THEN RETURN PARSE_JSON(''{"error": "BL not found"}''); END IF;
  BEGIN
    extracted := (SELECT SNOWFLAKE.CORTEX.EXTRACT_ANSWER(:bl_text,
      ''What are the key entities: shipper country, consignee country, commodity type, trade route, and risk level?''));
  EXCEPTION
    WHEN OTHER THEN
      extracted := (SELECT TRY_PARSE_JSON(SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
        ''Extract JSON from this BL: {"shipper_country":"..","consignee_country":"..","commodity_type":"..","trade_route":"..","risk_level":"LOW/MEDIUM/HIGH"}. BL: '' || :bl_text)));
  END;
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, PROMPT)
  SELECT CURRENT_TIMESTAMP(), ''extract_answer'', ''EXTRACT_BL_ENTITIES'', ''SUCCESS'', :bl_text;
  RETURN :extracted;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.GET_EXCHANGE_RATE("P_FROM" VARCHAR, "P_TO" VARCHAR, "P_AMOUNT" FLOAT)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE V_FROM_RATE FLOAT DEFAULT 1.0; V_TO_RATE FLOAT DEFAULT 1.0; V_CONVERTED FLOAT; V_RATE_DATE DATE;
BEGIN
    IF (:P_FROM != ''USD'') THEN
        SELECT EXCHANGE_RATE, RATE_DATE INTO V_FROM_RATE, V_RATE_DATE FROM V_EXCHANGE_RATES WHERE QUOTE_CURRENCY_ID = :P_FROM LIMIT 1;
    ELSE
        SELECT MAX(RATE_DATE) INTO V_RATE_DATE FROM V_EXCHANGE_RATES;
    END IF;
    IF (:P_TO != ''USD'') THEN
        SELECT EXCHANGE_RATE INTO V_TO_RATE FROM V_EXCHANGE_RATES WHERE QUOTE_CURRENCY_ID = :P_TO LIMIT 1;
    END IF;
    V_CONVERTED := (:P_AMOUNT / V_FROM_RATE) * V_TO_RATE;
    RETURN OBJECT_CONSTRUCT(''from'', P_FROM, ''to'', P_TO, ''amount'', P_AMOUNT, ''rate'', ROUND(V_TO_RATE / V_FROM_RATE, 6), ''converted'', ROUND(V_CONVERTED, 2), ''rate_date'', V_RATE_DATE::VARCHAR);
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.GET_OR_REFRESH_PDF_URL("P_DOC_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE v_file_name VARCHAR; v_expiry TIMESTAMP_NTZ; v_existing_url VARCHAR; v_new_url VARCHAR;
BEGIN
    SELECT FILE_NAME, PDF_URL_EXPIRY, PDF_PRESIGNED_URL INTO :v_file_name, :v_expiry, :v_existing_url
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED WHERE DOC_ID = :P_DOC_ID;
    IF (v_file_name IS NULL) THEN RETURN NULL; END IF;
    IF (v_existing_url IS NOT NULL AND v_expiry IS NOT NULL AND v_expiry > DATEADD(''MINUTE'', 2, CURRENT_TIMESTAMP())) THEN
        RETURN v_existing_url;
    END IF;
    CALL MENDIX_APP.AGENTS.GET_PRESIGNED_URL_FOR_FILE(:v_file_name) INTO :v_new_url;
    UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
    SET PDF_PRESIGNED_URL = :v_new_url, PDF_URL_EXPIRY = DATEADD(''SECOND'', 3600, CURRENT_TIMESTAMP())
    WHERE DOC_ID = :P_DOC_ID;
    RETURN v_new_url;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.GET_PDF_URL("P_DOC_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Generates presigned S3 URL (1hr expiry) for PDF viewing in Mendix.'
EXECUTE AS OWNER
AS '
DECLARE v_file_name VARCHAR; v_expiry TIMESTAMP_NTZ; v_existing_url VARCHAR; v_url VARCHAR; rs RESULTSET;
BEGIN
  SELECT FILE_NAME, PDF_URL_EXPIRY, PDF_PRESIGNED_URL INTO :v_file_name, :v_expiry, :v_existing_url
  FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED WHERE DOC_ID = :P_DOC_ID;
  IF (v_file_name IS NULL OR v_file_name = '''') THEN RETURN ''{"error":"Document not found"}''; END IF;
  IF (v_existing_url IS NOT NULL AND v_expiry IS NOT NULL AND v_expiry > DATEADD(''MINUTE'', 2, CURRENT_TIMESTAMP())) THEN
    RETURN v_existing_url;
  END IF;
  LET sql_stmt VARCHAR := ''SELECT GET_PRESIGNED_URL(@MENDIX_APP.AGENTS.LOGISTICS_STAGE, '''''' || :v_file_name || '''''', 3600)'';
  rs := (EXECUTE IMMEDIATE :sql_stmt);
  LET c CURSOR FOR rs;
  OPEN c; FETCH c INTO v_url; CLOSE c;
  UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
  SET PDF_PRESIGNED_URL = :v_url, PDF_URL_EXPIRY = DATEADD(''SECOND'', 3600, CURRENT_TIMESTAMP())
  WHERE DOC_ID = :P_DOC_ID;
  RETURN v_url;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.GET_PRESIGNED_URL_FOR_FILE("P_FILE_PATH" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Generates presigned URL (1hr expiry) for any file path in LOGISTICS_STAGE.'
EXECUTE AS OWNER
AS '
DECLARE url VARCHAR; rs RESULTSET;
BEGIN
  LET sql_stmt VARCHAR := ''SELECT GET_PRESIGNED_URL(@MENDIX_APP.AGENTS.LOGISTICS_STAGE, '''''' || :P_FILE_PATH || '''''', 3600)'';
  rs := (EXECUTE IMMEDIATE :sql_stmt);
  LET c CURSOR FOR rs;
  OPEN c; FETCH c INTO url; CLOSE c;
  RETURN url;
END;
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.HEALTH_CHECK_TEXT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET bl NUMBER; LET alerts NUMBER; LET ai NUMBER;
  BEGIN bl := (SELECT COUNT(*) FROM BILL_OF_LADING); EXCEPTION WHEN OTHER THEN bl := -1; END;
  BEGIN alerts := (SELECT COUNT(*) FROM FRAUD_ALERT); EXCEPTION WHEN OTHER THEN alerts := -1; END;
  BEGIN ai := (SELECT COUNT(*) FROM AI_CALL_LOG); EXCEPTION WHEN OTHER THEN ai := -1; END;
  RETURN ''BL: '' || :bl::VARCHAR || '' | Alerts: '' || :alerts::VARCHAR || '' | AI Calls: '' || :ai::VARCHAR || '' | Status: HEALTHY'';
END';
