-- 60_procedures_4: PROCEDURE (10 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SYNC_EXTRACTED_TO_BILL_OF_LADING()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Promotes extracted PDF documents from BILL_OF_LADING_EXTRACTED into operational BILL_OF_LADING table. Idempotent.'
EXECUTE AS CALLER
AS 'DECLARE v_promoted NUMBER := 0;
BEGIN
    LET doc_cursor CURSOR FOR (SELECT DOC_ID FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED WHERE SYNCED_TO_BL_AT IS NULL ORDER BY DOC_ID);
    FOR d IN doc_cursor DO
        LET v_doc_id NUMBER := d.DOC_ID;
        LET v_bl_id NUMBER;
        INSERT INTO MENDIX_APP.AGENTS.BILL_OF_LADING (
            BL_NUMBER, SHIPPER_NAME, CONSIGNEE_NAME, NOTIFY_PARTY,
            PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE, PLACE_OF_RECEIPT, PLACE_OF_DELIVERY,
            VESSEL_NAME, VOYAGE_NUMBER, CONTAINER_NUMBER, HS_CODE, COMMODITY_DESCRIPTION, PACKAGE_COUNT, PACKAGE_TYPE,
            GROSS_WEIGHT_KGS, FREIGHT_AMOUNT, CURRENCY_CODE, TOTAL_CHARGES,
            CARRIER_NAME, BL_DATE, CREATED_AT, STATUS, SYNCED_TO_ERP, AI_CONFIDENCE_SCORE, PROCESSED_AT, REMARKS)
        SELECT
            LEFT(COALESCE(NULLIF(TRIM(e.BL_NUMBER), ''''), ''DOC-'' || e.DOC_ID::VARCHAR), 50),
            LEFT(e.SHIPPER_NAME, 200), LEFT(e.CONSIGNEE_NAME, 200), LEFT(e.NOTIFY_PARTY, 200),
            LEFT(COALESCE(REGEXP_SUBSTR(e.PORT_OF_LOADING, ''\\(([A-Z]{5})\\)'', 1, 1, ''e'', 1), e.PORT_OF_LOADING), 10),
            LEFT(COALESCE(REGEXP_SUBSTR(e.PORT_OF_DISCHARGE, ''\\(([A-Z]{5})\\)'', 1, 1, ''e'', 1), e.PORT_OF_DISCHARGE), 10),
            LEFT(e.PORT_OF_LOADING, 100), LEFT(e.PORT_OF_DISCHARGE, 100),
            LEFT(e.VESSEL_NAME, 100), LEFT(e.VOYAGE_NUMBER, 50), LEFT(e.CONTAINER_NUMBER, 15),
            LEFT(e.HS_CODE, 10), LEFT(e.COMMODITY_DESC, 1000), e.PACKAGE_COUNT, LEFT(e.PACKAGE_TYPE, 50),
            e.GROSS_WEIGHT_KG, e.FREIGHT_CHARGES, LEFT(NVL(e.FREIGHT_CURRENCY, ''USD''), 5), e.FREIGHT_CHARGES,
            LEFT(e.CARRIER_NAME, 100), e.DATE_OF_ISSUE, CURRENT_TIMESTAMP(),
            CASE WHEN e.STATUS IN (''AI_Processed'', ''Synced_To_SAP'') THEN ''APPROVED'' ELSE ''Pending_Review'' END,
            (e.STATUS = ''Synced_To_SAP''), e.CONFIDENCE_SCORE, e.PROCESSED_AT,
            LEFT(''Ingested from PDF '' || e.FILE_NAME || COALESCE('' | AI alert: '' || NULLIF(e.ALERT, ''No anomalies detected''), ''''), 2000)
        FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED e WHERE e.DOC_ID = :v_doc_id;
        SELECT MAX(BL_ID) INTO :v_bl_id FROM MENDIX_APP.AGENTS.BILL_OF_LADING;
        UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED SET SYNCED_TO_BL_AT = CURRENT_TIMESTAMP(), BL_ID = :v_bl_id WHERE DOC_ID = :v_doc_id;
        v_promoted := :v_promoted + 1;
    END FOR;
    RETURN ''{"procedure":"SYNC_EXTRACTED_TO_BILL_OF_LADING","documents_promoted":'' || :v_promoted || ''}'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.SYSTEM_HEALTH_CHECK()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET health VARIANT; LET bl_count NUMBER := 0; LET alert_count NUMBER := 0;
  LET ai_calls NUMBER := 0; LET search_ok BOOLEAN := FALSE;
  BEGIN bl_count := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.BILL_OF_LADING); EXCEPTION WHEN OTHER THEN bl_count := -1; END;
  BEGIN alert_count := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.FRAUD_ALERT); EXCEPTION WHEN OTHER THEN alert_count := -1; END;
  BEGIN ai_calls := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.AI_CALL_LOG); EXCEPTION WHEN OTHER THEN ai_calls := -1; END;
  BEGIN
    LET search_test VARCHAR := (SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(''MENDIX_APP.AGENTS.BL_SEARCH_SERVICE'', ''{"query":"test","columns":["BL_NUMBER"],"limit":1}''));
    search_ok := TRUE;
  EXCEPTION WHEN OTHER THEN search_ok := FALSE;
  END;
  health := OBJECT_CONSTRUCT(''timestamp'', CURRENT_TIMESTAMP()::VARCHAR, ''bill_of_lading_count'', :bl_count, ''fraud_alerts'', :alert_count, ''ai_call_log'', :ai_calls, ''cortex_search_active'', :search_ok, ''status'', IFF(:bl_count > 0 AND :alert_count >= 0 AND :ai_calls >= 0, ''HEALTHY'', ''DEGRADED''));
  RETURN :health;
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.TEST_PIPELINE_E2E()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
    LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    LET sample_bl_text VARCHAR := ''BILL OF LADING No: MAEU2024VN0891
Shipper: VIETNAM ELECTRONICS MANUFACTURING JSC
Consignee: TECH IMPORTS GMBH
Vessel: MV EVER GOLDEN  Voyage: 045E
Port of Loading: HO CHI MINH CITY (VNSGN)
Port of Discharge: HAMBURG (DEHAM)
Container No: MSKU7234561  Size: 40HC
Commodity: ELECTRONIC COMPONENTS
HS Code: 8534.00
Gross Weight: 18500 KG
Freight: USD 4850.00 PREPAID
Date of Issue: 2024-06-15'';
    LET extraction_prompt VARCHAR := ''Extract fields from this Bill of Lading as valid JSON only: {"bl_number":"","container_number":"","vessel_name":"","voyage_number":"","shipper_name":"","consignee_name":"","port_of_loading":"","port_of_discharge":"","commodity_desc":"","hs_code":"","gross_weight_kg":0,"freight_charges":0,"freight_currency":"USD","date_of_issue":"YYYY-MM-DD"}. Return ONLY JSON. Text: '' || :sample_bl_text;
    LET extracted_json VARCHAR;
    extracted_json := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', :extraction_prompt));
    LET json_start NUMBER := POSITION(''{'' IN :extracted_json);
    LET json_end NUMBER := LENGTH(:extracted_json) - POSITION(''}'' IN REVERSE(:extracted_json)) + 1;
    IF (:json_start > 0 AND :json_end > :json_start) THEN
        extracted_json := SUBSTRING(:extracted_json, :json_start, :json_end - :json_start + 1);
    END IF;
    LET parsed VARIANT := TRY_PARSE_JSON(:extracted_json);
    IF (:parsed IS NULL) THEN parsed := PARSE_JSON(''{"bl_number":"PARSE_ERROR"}''); END IF;
    LET elapsed NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
    RETURN ''E2E Test OK | BL: '' || :parsed:bl_number::VARCHAR || '' | Time: '' || :elapsed::VARCHAR || ''ms'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.WORKFLOW_AUTO_REMEDIATE("P_ALERT_ID" NUMBER(38,0), "P_ACTION" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Automated remediation: applies BLOCK/ESCALATE/CLEAR and records AI decision reason.'
EXECUTE AS CALLER
AS '
DECLARE v_bl_id NUMBER; v_bl_number VARCHAR; v_result VARCHAR; v_ai_reason VARCHAR; v_note VARCHAR;
BEGIN
    SELECT BL_ID, NVL(AI_DECISION_REASON, ''No AI reason recorded'') INTO :v_bl_id, :v_ai_reason
    FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :P_ALERT_ID;
    SELECT BL_NUMBER INTO :v_bl_number FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :v_bl_id;
    CASE UPPER(:P_ACTION)
        WHEN ''BLOCK'' THEN
            v_note := ''AUTO-BLOCKED by AI decision. Reason: '' || :v_ai_reason;
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET STATUS = ''BLOCKED'', FRAUD_CHECK_PASSED = FALSE WHERE BL_ID = :v_bl_id;
            UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''RESOLVED'', RESOLVED_AT = CURRENT_TIMESTAMP(), RESOLUTION_NOTES = LEFT(:v_note, 2000) WHERE ALERT_ID = :P_ALERT_ID;
            INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, STATUS)
            VALUES (''FRAUD_BLOCK'', ''compliance@vflogistics.com'', ''Shipment Blocked'', ''BLOCKED: '' || :v_bl_number || '' - '' || :v_ai_reason, ''SENT'');
            v_result := ''Shipment '' || :v_bl_number || '' BLOCKED.'';
        WHEN ''ESCALATE'' THEN
            v_note := ''ESCALATED by AI decision. Reason: '' || :v_ai_reason;
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET STATUS = ''Pending_Review'' WHERE BL_ID = :v_bl_id;
            UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''ESCALATED'', RESOLUTION_NOTES = LEFT(:v_note, 2000) WHERE ALERT_ID = :P_ALERT_ID;
            INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, STATUS)
            VALUES (''FRAUD_ESCALATE'', ''compliance@vflogistics.com'', ''Alert Escalated'', ''Alert #'' || :P_ALERT_ID || '' on '' || :v_bl_number || '' - '' || :v_ai_reason, ''SENT'');
            v_result := ''Alert #'' || :P_ALERT_ID || '' ESCALATED.'';
        WHEN ''CLEAR'' THEN
            v_note := ''CLEARED by AI - no fraud. Reason: '' || :v_ai_reason;
            UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''RESOLVED'', RESOLVED_AT = CURRENT_TIMESTAMP(), RESOLUTION_NOTES = LEFT(:v_note, 2000) WHERE ALERT_ID = :P_ALERT_ID;
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET FRAUD_CHECK_PASSED = TRUE WHERE BL_ID = :v_bl_id;
            v_result := ''Alert #'' || :P_ALERT_ID || '' CLEARED. Shipment approved.'';
        ELSE v_result := ''ERROR: Unknown action.'';
    END CASE;
    RETURN ''{"workflow":"AUTO_REMEDIATE","alert_id":'' || :P_ALERT_ID || '',"action":"'' || :P_ACTION || ''","result":"'' || :v_result || ''"}'';
END
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.WORKFLOW_DETECT_AND_ACT("P_QUEUE_LIMIT" NUMBER(38,0) DEFAULT 100)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Automated fraud/compliance detection with data-derived thresholds. Excludes Pending_Review/DRAFT records.'
EXECUTE AS CALLER
AS '
DECLARE
    v_p99_charges FLOAT; v_p99_weight FLOAT; v_p95_cpk FLOAT; v_median_cpk FLOAT;
    v_new_alerts NUMBER DEFAULT 0; v_high_severity NUMBER DEFAULT 0; v_actions_taken NUMBER DEFAULT 0;
    v_cap NUMBER DEFAULT 8; v_queue_open NUMBER DEFAULT 0; v_throttled BOOLEAN DEFAULT FALSE;
BEGIN
    SELECT COUNT(*) INTO :v_queue_open FROM MENDIX_APP.AGENTS.FRAUD_ALERT
    WHERE STATUS = ''OPEN'' AND SEVERITY IN (''HIGH'', ''MEDIUM'') AND BL_ID IS NOT NULL AND DETECTED_AT >= DATEADD(day, -7, CURRENT_TIMESTAMP()) /* QUEUE_WINDOW_DAYS = 7 */;
    SELECT PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY TOTAL_CHARGES),
           PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY GROSS_WEIGHT_KGS),
           PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TOTAL_CHARGES / NULLIF(GROSS_WEIGHT_KGS,0)),
           MEDIAN(TOTAL_CHARGES / NULLIF(GROSS_WEIGHT_KGS,0))
    INTO :v_p99_charges, :v_p99_weight, :v_p95_cpk, :v_median_cpk
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING
    WHERE TOTAL_CHARGES IS NOT NULL AND GROSS_WEIGHT_KGS > 0 AND STATUS NOT IN (''Pending_Review'', ''DRAFT'');
    v_throttled := (:v_queue_open >= :P_QUEUE_LIMIT); /* This gate used to wrap every detection rule in its ELSE branch, so a saturated queue skipped all of them and a backlog of MEDIUM alerts could hide a HIGH-severity fraud. It now only records that the queue is saturated; each rule below carries its own severity guard. The IF is kept as a deliberately-always-false branch so the existing ELSE / END IF structure stays valid without restructuring five INSERT statements. */ IF (FALSE) THEN v_throttled := :v_throttled;
    ELSE
        INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
        SELECT ''COST_PER_KG_ANOMALY'',
            CASE WHEN TOTAL_CHARGES / GROSS_WEIGHT_KGS > 10 * :v_median_cpk THEN ''HIGH'' ELSE ''MEDIUM'' END,
            ''Cost/kg $'' || ROUND(TOTAL_CHARGES / GROSS_WEIGHT_KGS, 4) || '' vs median $'' || ROUND(:v_median_cpk, 4) || '' on '' || BL_NUMBER,
            BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        FROM MENDIX_APP.AGENTS.BILL_OF_LADING b
        WHERE GROSS_WEIGHT_KGS > 0 AND TOTAL_CHARGES IS NOT NULL
          AND TOTAL_CHARGES / GROSS_WEIGHT_KGS > 5 * :v_median_cpk AND (:v_throttled = FALSE OR TOTAL_CHARGES / GROSS_WEIGHT_KGS > 10 * :v_median_cpk)
          AND NOT EXISTS (SELECT 1 FROM MENDIX_APP.AGENTS.FRAUD_ALERT a WHERE a.BL_ID = b.BL_ID)
        ORDER BY TOTAL_CHARGES / GROSS_WEIGHT_KGS DESC LIMIT :v_cap;
        v_new_alerts := SQLROWCOUNT;
        INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
        SELECT ''HIGH_VALUE_ANOMALY'',
            CASE WHEN GROSS_WEIGHT_KGS > 0 AND TOTAL_CHARGES / GROSS_WEIGHT_KGS > 10 * :v_median_cpk THEN ''HIGH'' ELSE ''MEDIUM'' END,
            ''Charges $'' || TOTAL_CHARGES || '' exceed p99 $'' || ROUND(:v_p99_charges) || '' on '' || BL_NUMBER,
            BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        FROM MENDIX_APP.AGENTS.BILL_OF_LADING b
        WHERE TOTAL_CHARGES > :v_p99_charges AND (:v_throttled = FALSE OR (GROSS_WEIGHT_KGS > 0 AND TOTAL_CHARGES / GROSS_WEIGHT_KGS > 10 * :v_median_cpk))
          AND NOT EXISTS (SELECT 1 FROM MENDIX_APP.AGENTS.FRAUD_ALERT a WHERE a.BL_ID = b.BL_ID)
        ORDER BY TOTAL_CHARGES DESC LIMIT :v_cap;
        v_new_alerts := :v_new_alerts + SQLROWCOUNT;
        INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
        SELECT ''WEIGHT_ANOMALY'', ''MEDIUM'',
            ''Weight '' || GROSS_WEIGHT_KGS || ''kg exceeds p99 '' || ROUND(:v_p99_weight) || ''kg on '' || BL_NUMBER,
            BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        FROM MENDIX_APP.AGENTS.BILL_OF_LADING b
        WHERE GROSS_WEIGHT_KGS > :v_p99_weight AND :v_throttled = FALSE
          AND NOT EXISTS (SELECT 1 FROM MENDIX_APP.AGENTS.FRAUD_ALERT a WHERE a.BL_ID = b.BL_ID)
        ORDER BY GROSS_WEIGHT_KGS DESC LIMIT :v_cap;
        v_new_alerts := :v_new_alerts + SQLROWCOUNT;
        INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
        SELECT ''SUSPICIOUS_PARTY'', ''HIGH'',
            ''Suspicious counterparty on '' || BL_NUMBER || '': '' || SHIPPER_NAME || '' -> '' || NVL(CONSIGNEE_NAME, ''(none)''),
            BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        FROM MENDIX_APP.AGENTS.BILL_OF_LADING b
        WHERE (UPPER(SHIPPER_NAME) LIKE ''%SUSPICIOUS%'' OR UPPER(CONSIGNEE_NAME) LIKE ''%SHELL CORP%'' OR UPPER(SHIPPER_NAME) LIKE ''%UNKNOWN%'')
          AND NOT EXISTS (SELECT 1 FROM MENDIX_APP.AGENTS.FRAUD_ALERT a WHERE a.BL_ID = b.BL_ID) LIMIT :v_cap;
        v_new_alerts := :v_new_alerts + SQLROWCOUNT;
        INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
        SELECT ''DOCUMENT_QUALITY'', CASE WHEN AI_CONFIDENCE_SCORE <= 50 THEN ''HIGH'' ELSE ''MEDIUM'' END,
            ''AI confidence '' || AI_CONFIDENCE_SCORE::VARCHAR || ''/100 on '' || BL_NUMBER,
            BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
        FROM MENDIX_APP.AGENTS.BILL_OF_LADING b
        WHERE AI_CONFIDENCE_SCORE IS NOT NULL AND AI_CONFIDENCE_SCORE < 85 AND (:v_throttled = FALSE OR AI_CONFIDENCE_SCORE <= 50)
          AND NOT EXISTS (SELECT 1 FROM MENDIX_APP.AGENTS.FRAUD_ALERT a WHERE a.BL_ID = b.BL_ID) LIMIT :v_cap;
        v_new_alerts := :v_new_alerts + SQLROWCOUNT;
    END IF;
    SELECT COUNT(*) INTO :v_high_severity FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'';
    UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET STATUS = ''Pending_Review'', FRAUD_CHECK_PASSED = FALSE
    WHERE BL_ID IN (SELECT BL_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'' AND BL_ID IS NOT NULL)
      AND STATUS NOT IN (''Pending_Review'', ''BLOCKED'');
    v_actions_taken := SQLROWCOUNT;
    INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, STATUS)
    SELECT ''WORKFLOW_RUN'', ''system'', IFF(:v_throttled, ''Detection throttled'', ''Detection completed''),
           ''New alerts: '' || :v_new_alerts || ''. HIGH open: '' || :v_high_severity, ''SENT'';
    RETURN ''{"workflow":"DETECT_AND_ACT","throttled":'' || IFF(:v_throttled, ''true'', ''false'')
        || '',"medium_suppressed":'' || IFF(:v_throttled, ''true'', ''false'') || '',"new_alerts":'' || :v_new_alerts || '',"high_severity_open":'' || :v_high_severity
        || '',"shipments_flagged":'' || :v_actions_taken || ''}'';
END
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.WORKFLOW_FULL_PIPELINE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'DECLARE v_scan_result VARCHAR; v_alert_id NUMBER;
BEGIN
    CALL MENDIX_APP.AGENTS.WORKFLOW_DETECT_AND_ACT();
    v_scan_result := SQLROWCOUNT || '' rules executed'';
    SELECT ALERT_ID INTO :v_alert_id FROM MENDIX_APP.AGENTS.FRAUD_ALERT
    WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'' ORDER BY CREATED_AT DESC LIMIT 1;
    CALL MENDIX_APP.AGENTS.WORKFLOW_INVESTIGATE_ANOMALY(:v_alert_id);
    CALL MENDIX_APP.AGENTS.WORKFLOW_AUTO_REMEDIATE(:v_alert_id, ''ESCALATE'');
    RETURN ''{"workflow":"FULL_PIPELINE","status":"COMPLETED","alert_investigated":'' || :v_alert_id || ''}'';
END';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.WORKFLOW_FULL_PIPELINE_V2("P_MODE" VARCHAR DEFAULT 'AUTO', "P_MAX_ALERTS" NUMBER(38,0) DEFAULT 1)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='End-to-end automation: detect -> investigate -> sanctions -> remediate -> SAP post for cleared.'
EXECUTE AS CALLER
AS '
DECLARE
    v_start_time TIMESTAMP; v_step_start TIMESTAMP; v_step_ms NUMBER;
    v_alert_id NUMBER; v_severity VARCHAR; v_prev_alert_id NUMBER DEFAULT NULL;
    v_shipper VARCHAR; v_sap_bl_id NUMBER; v_sap_result VARCHAR; v_elapsed_ms NUMBER;
    v_ai_action VARCHAR; v_ai_reason VARCHAR;
    v_processed NUMBER DEFAULT 0; v_blocked NUMBER DEFAULT 0; v_escalated NUMBER DEFAULT 0;
    v_cleared NUMBER DEFAULT 0; v_sap_posted NUMBER DEFAULT 0;
    v_first_decision VARCHAR DEFAULT NULL; v_first_reason VARCHAR DEFAULT NULL;
    v_alert_ids VARCHAR DEFAULT ''''; v_max NUMBER;
BEGIN
    v_start_time := CURRENT_TIMESTAMP();
    v_max := GREATEST(NVL(:P_MAX_ALERTS, 1), 1);
    v_step_start := CURRENT_TIMESTAMP();
    CALL MENDIX_APP.AGENTS.WORKFLOW_DETECT_AND_ACT();
    v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
    VALUES (''FULL_PIPELINE_V2'', ''DETECT_ANOMALIES'', 1, :P_MODE || '',max='' || :v_max, ''Scan completed'', :v_step_ms, ''SUCCESS'');
    LOOP
        IF (:v_processed >= :v_max) THEN BREAK; END IF;
        v_alert_id := NULL;
        v_alert_id := (SELECT ALERT_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT
        WHERE STATUS = ''OPEN'' AND SEVERITY IN (''HIGH'', ''MEDIUM'') AND BL_ID IS NOT NULL
        ORDER BY CASE SEVERITY WHEN ''HIGH'' THEN 1 ELSE 2 END, CREATED_AT DESC LIMIT 1);
        IF (:v_alert_id IS NULL) THEN BREAK; END IF;
        IF (:v_prev_alert_id IS NOT NULL AND :v_alert_id = :v_prev_alert_id) THEN BREAK; END IF;
        v_prev_alert_id := :v_alert_id;
        v_step_start := CURRENT_TIMESTAMP();
        CALL MENDIX_APP.AGENTS.WORKFLOW_INVESTIGATE_ANOMALY(:v_alert_id);
        v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
        SELECT NVL(AI_RECOMMENDED_ACTION, ''ESCALATE''), NVL(AI_DECISION_REASON, ''No AI reason'')
        INTO :v_ai_action, :v_ai_reason FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :v_alert_id LIMIT 1;
        INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
        VALUES (''FULL_PIPELINE_V2'', ''AI_INVESTIGATE'', 2, ''alert='' || :v_alert_id, ''decision='' || :v_ai_action, :v_step_ms, ''SUCCESS'');
        v_shipper := (SELECT SHIPPER_NAME FROM MENDIX_APP.AGENTS.BILL_OF_LADING
        WHERE BL_ID = (SELECT BL_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :v_alert_id LIMIT 1));
        v_step_start := CURRENT_TIMESTAMP();
        CALL MENDIX_APP.AGENTS.WORKFLOW_SANCTIONS_SCREEN(:v_shipper);
        v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
        INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
        VALUES (''FULL_PIPELINE_V2'', ''SANCTIONS_SCREEN'', 3, :v_shipper, ''Completed'', :v_step_ms, ''SUCCESS'');
        v_step_start := CURRENT_TIMESTAMP();
        CALL MENDIX_APP.AGENTS.WORKFLOW_AUTO_REMEDIATE(:v_alert_id, :v_ai_action);
        v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
        INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
        VALUES (''FULL_PIPELINE_V2'', ''AUTO_REMEDIATE'', 4, ''alert='' || :v_alert_id || '',action='' || :v_ai_action, ''Executed'', :v_step_ms, ''SUCCESS'');
        v_sap_result := ''{"status":"SKIPPED"}'';
        IF (:v_ai_action = ''CLEAR'') THEN
            SELECT BL_ID INTO :v_sap_bl_id FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :v_alert_id LIMIT 1;
            IF (:v_sap_bl_id IS NOT NULL) THEN
                v_step_start := CURRENT_TIMESTAMP();
                CALL MENDIX_APP.AGENTS.SAP_POST_FI_DOCUMENT(:v_sap_bl_id) INTO :v_sap_result;
                v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
                v_sap_posted := :v_sap_posted + 1;
                INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
                VALUES (''FULL_PIPELINE_V2'', ''SAP_POST'', 5, ''bl_id='' || :v_sap_bl_id, :v_sap_result, :v_step_ms, ''SUCCESS'');
            END IF;
        END IF;
        v_processed := :v_processed + 1;
        v_alert_ids := IFF(:v_alert_ids = '''', TO_VARCHAR(:v_alert_id), :v_alert_ids || '','' || :v_alert_id);
        IF (:v_ai_action = ''BLOCK'') THEN v_blocked := :v_blocked + 1;
        ELSEIF (:v_ai_action = ''CLEAR'') THEN v_cleared := :v_cleared + 1;
        ELSE v_escalated := :v_escalated + 1; END IF;
        IF (:v_first_decision IS NULL) THEN v_first_decision := :v_ai_action; v_first_reason := :v_ai_reason; END IF;
    END LOOP;
    IF (:v_processed = 0) THEN
        INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
        VALUES (''FULL_PIPELINE_V2'', ''AI_INVESTIGATE'', 2, ''no_open_alert'', ''SKIPPED'', 0, ''SKIPPED'');
        v_first_decision := ''NONE''; v_first_reason := ''No open alert in this run.'';
    END IF;
    v_elapsed_ms := DATEDIFF(''millisecond'', :v_start_time, CURRENT_TIMESTAMP());
    RETURN ''{"workflow":"FULL_PIPELINE_V2","status":"COMPLETED","alerts_processed":'' || :v_processed
        || '',"decisions":{"blocked":'' || :v_blocked || '',"escalated":'' || :v_escalated || '',"cleared":'' || :v_cleared || ''}''
        || '',"sap_posted":'' || :v_sap_posted || '',"ai_decision":"'' || NVL(:v_first_decision,''NONE'')
        || ''","ai_reason":"'' || REPLACE(NVL(:v_first_reason,''''), ''"'', ''\\"'') || ''","execution_ms":'' || :v_elapsed_ms || ''}'';
END
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.WORKFLOW_INGEST_AND_DECIDE()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='End-to-end: extract PDFs -> promote to operational table -> run full fraud/compliance pipeline.'
EXECUTE AS CALLER
AS '
DECLARE v_extract VARCHAR; v_sync VARCHAR; v_pipeline VARCHAR;
    v_start TIMESTAMP; v_step_start TIMESTAMP; v_elapsed NUMBER; v_step_ms NUMBER;
BEGIN
    v_start := CURRENT_TIMESTAMP();
    v_step_start := CURRENT_TIMESTAMP();
    CALL MENDIX_APP.AGENTS.PROCESS_BL_DOCUMENTS() INTO :v_extract;
    v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
    VALUES (''INGEST_AND_DECIDE'', ''EXTRACT_DOCUMENTS'', 1, ''@LOGISTICS_STAGE'', :v_extract, :v_step_ms, ''SUCCESS'');
    v_step_start := CURRENT_TIMESTAMP();
    CALL MENDIX_APP.AGENTS.SYNC_EXTRACTED_TO_BILL_OF_LADING() INTO :v_sync;
    v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
    VALUES (''INGEST_AND_DECIDE'', ''PROMOTE_TO_OPERATIONAL'', 2, ''BILL_OF_LADING_EXTRACTED'', :v_sync, :v_step_ms, ''SUCCESS'');
    v_step_start := CURRENT_TIMESTAMP();
    CALL MENDIX_APP.AGENTS.WORKFLOW_FULL_PIPELINE_V2(''AUTO'') INTO :v_pipeline;
    v_step_ms := DATEDIFF(''millisecond'', :v_step_start, CURRENT_TIMESTAMP());
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, EXECUTION_TIME_MS, STATUS)
    VALUES (''INGEST_AND_DECIDE'', ''FRAUD_PIPELINE'', 3, ''AUTO'', :v_pipeline, :v_step_ms, ''SUCCESS'');
    v_elapsed := DATEDIFF(''millisecond'', :v_start, CURRENT_TIMESTAMP());
    RETURN ''{"workflow":"INGEST_AND_DECIDE","status":"COMPLETED","extraction":"'' || REPLACE(:v_extract, ''"'', ''\\"'') || ''","pipeline":'' || :v_pipeline || '',"total_ms":'' || :v_elapsed || ''}'';
END
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.WORKFLOW_INVESTIGATE_ANOMALY("P_ALERT_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='AI investigation: builds evidence pack, uses structured JSON output to decide BLOCK/ESCALATE/CLEAR.'
EXECUTE AS CALLER
AS '
DECLARE
    v_alert_type VARCHAR; v_bl_id NUMBER; v_bl_number VARCHAR; v_shipper VARCHAR; v_consignee VARCHAR;
    v_charges NUMBER; v_weight NUMBER; v_carrier VARCHAR; v_port_load VARCHAR; v_port_discharge VARCHAR;
    v_confidence FLOAT; v_cost_per_kg FLOAT; v_median_cpk FLOAT; v_p95_cpk FLOAT;
    v_cpk_multiple FLOAT; v_cpk_band VARCHAR; v_band_rule VARCHAR;
    v_sanction_hits NUMBER DEFAULT 0; v_doc_context VARCHAR DEFAULT '''';
    v_prompt VARCHAR; v_resp VARIANT; v_payload VARIANT; v_context VARCHAR;
    v_decision VARCHAR; v_reason VARCHAR; v_assessment VARCHAR;
    v_start_ts TIMESTAMP_NTZ; v_elapsed_ms NUMBER;
    v_in_tok NUMBER DEFAULT 0; v_out_tok NUMBER DEFAULT 0; v_tot_tok NUMBER DEFAULT 0;
    v_attempts NUMBER DEFAULT 0; v_contract VARCHAR; v_options VARIANT;
BEGIN
    SELECT ALERT_TYPE, BL_ID INTO :v_alert_type, :v_bl_id FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :P_ALERT_ID LIMIT 1;
    SELECT BL_NUMBER, SHIPPER_NAME, CONSIGNEE_NAME, TOTAL_CHARGES, GROSS_WEIGHT_KGS, CARRIER_NAME,
           PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE, AI_CONFIDENCE_SCORE
    INTO :v_bl_number, :v_shipper, :v_consignee, :v_charges, :v_weight, :v_carrier, :v_port_load, :v_port_discharge, :v_confidence
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :v_bl_id LIMIT 1;
    v_cost_per_kg := ROUND(:v_charges / NULLIF(:v_weight, 0), 4);
    SELECT ROUND(MEDIAN(TOTAL_CHARGES / NULLIF(GROSS_WEIGHT_KGS,0)),4),
           ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY TOTAL_CHARGES / NULLIF(GROSS_WEIGHT_KGS,0)),4)
    INTO :v_median_cpk, :v_p95_cpk FROM MENDIX_APP.AGENTS.BILL_OF_LADING
    WHERE TOTAL_CHARGES IS NOT NULL AND GROSS_WEIGHT_KGS > 0;
    v_cpk_multiple := ROUND(:v_cost_per_kg / NULLIF(:v_median_cpk, 0), 2);
    v_cpk_band := CASE WHEN :v_cpk_multiple IS NULL THEN ''NOT_COMPUTABLE''
        WHEN :v_cpk_multiple > 10 THEN ''EXTREME_ABOVE_10X_MEDIAN''
        WHEN :v_cpk_multiple > 5 THEN ''ELEVATED_BETWEEN_5X_AND_10X_MEDIAN''
        ELSE ''NORMAL_AT_OR_BELOW_5X_MEDIAN'' END;
    v_band_rule := CASE :v_cpk_band
        WHEN ''EXTREME_ABOVE_10X_MEDIAN'' THEN ''Mandates BLOCK on economics alone.''
        WHEN ''ELEVATED_BETWEEN_5X_AND_10X_MEDIAN'' THEN ''Mandates ESCALATE for human judgement.''
        WHEN ''NORMAL_AT_OR_BELOW_5X_MEDIAN'' THEN ''Economically ordinary, does NOT justify BLOCK or ESCALATE alone.''
        ELSE ''Not computable, reason to ESCALATE.'' END;
    BEGIN
        SELECT COUNT(*) INTO :v_sanction_hits FROM MENDIX_APP.AGENTS.V_SANCTIONS_SCREENING_SOURCE
        WHERE UPPER(ENTITY_NAME) LIKE ''%'' || UPPER(NVL(:v_shipper, ''~none~'')) || ''%''
           OR UPPER(ENTITY_NAME) LIKE ''%'' || UPPER(NVL(:v_consignee, ''~none~'')) || ''%'';
    EXCEPTION WHEN OTHER THEN v_sanction_hits := -1; END;
    BEGIN
        SELECT '' DOCUMENT PROVENANCE: extracted from PDF '' || e.FILE_NAME || ''. Confidence '' || COALESCE(e.CONFIDENCE_SCORE::VARCHAR, ''unknown'') || ''/100. Alert: '' || COALESCE(e.ALERT, ''not recorded'')
        INTO :v_doc_context FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED e WHERE e.BL_ID = :v_bl_id LIMIT 1;
    EXCEPTION WHEN OTHER THEN v_doc_context := ''''; END;
    v_context := ''Alert type: '' || :v_alert_type || ''. BL: '' || :v_bl_number || ''. Shipper: '' || NVL(:v_shipper, ''(not stated)'') || ''. Consignee: '' || NVL(:v_consignee, ''(not stated)'') || ''. Route: '' || NVL(:v_port_load, ''?'') || '' -> '' || NVL(:v_port_discharge, ''?'') || ''. Charges: $'' || NVL(TO_VARCHAR(:v_charges),''n/a'') || ''. Weight: '' || NVL(TO_VARCHAR(:v_weight),''n/a'') || ''kg. Cost/kg: $'' || NVL(TO_VARCHAR(:v_cost_per_kg),''n/a'') || '' ('' || NVL(TO_VARCHAR(:v_cpk_multiple),''n/a'') || ''x median $'' || :v_median_cpk || ''). BAND: '' || :v_cpk_band || ''. '' || :v_band_rule || '' Sanctions matches: '' || :v_sanction_hits || ''.'' || NVL(:v_doc_context, '''');
    v_prompt := ''You are a maritime logistics fraud analyst. The cost-per-kg band is PRE-COMPUTED. Trust it. Rubric: BLOCK if sanctions>0, OR band is EXTREME, OR counterparty is suspicious/shell/unknown. ESCALATE if band is ELEVATED, OR cost not computable, OR extraction confidence<60. CLEAR if sanctions=0 AND band NORMAL AND counterparties are real businesses. Return JSON: {"decision":"BLOCK|ESCALATE|CLEAR","reason":"...","assessment":"..."}. Evidence: '' || :v_context;
    v_contract := ''{"type":"json","schema":{"type":"object","properties":{"decision":{"type":"string","enum":["BLOCK","ESCALATE","CLEAR"]},"reason":{"type":"string"},"assessment":{"type":"string"}},"required":["decision","reason","assessment"]}}'';
    v_options := PARSE_JSON(''{"temperature":0,"max_tokens":700,"response_format":'' || :v_contract || ''}'');
    WHILE (:v_attempts < 2 AND :v_decision IS NULL) DO
        v_attempts := :v_attempts + 1;
        v_start_ts := CURRENT_TIMESTAMP();
        BEGIN
            SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', ARRAY_CONSTRUCT(OBJECT_CONSTRUCT(''role'', ''user'', ''content'', :v_prompt)), :v_options) INTO :v_resp;
            v_elapsed_ms := DATEDIFF(''millisecond'', :v_start_ts, CURRENT_TIMESTAMP());
            v_in_tok := NVL(:v_resp:usage:prompt_tokens::NUMBER, 0);
            v_out_tok := NVL(:v_resp:usage:completion_tokens::NUMBER, 0);
            v_tot_tok := NVL(:v_resp:usage:total_tokens::NUMBER, :v_in_tok + :v_out_tok);
            v_payload := TRY_PARSE_JSON(:v_resp:structured_output[0]:raw_message::STRING);
            v_decision := UPPER(NVL(:v_payload:decision::STRING, ''''));
            IF (:v_decision NOT IN (''BLOCK'', ''ESCALATE'', ''CLEAR'')) THEN v_decision := NULL; END IF;
            v_reason := :v_payload:reason::STRING;
            v_assessment := :v_payload:assessment::STRING;
            INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, PROCEDURE_NAME, CONTEXT, CALL_STATUS, STATUS, LATENCY_MS, INPUT_TOKENS, OUTPUT_TOKENS, TOTAL_TOKENS, PROMPT, RESPONSE)
            SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', ''WORKFLOW_INVESTIGATE_ANOMALY'', ''fraud_investigation:attempt'' || :v_attempts,
                   IFF(:v_decision IS NULL, ''PARSE_RETRY'', ''SUCCESS''), IFF(:v_decision IS NULL, ''PARSE_RETRY'', ''SUCCESS''),
                   :v_elapsed_ms, :v_in_tok, :v_out_tok, :v_tot_tok, LEFT(:v_prompt, 5000), LEFT(:v_resp:structured_output[0]:raw_message::STRING, 10000);
        EXCEPTION WHEN OTHER THEN
            v_elapsed_ms := DATEDIFF(''millisecond'', :v_start_ts, CURRENT_TIMESTAMP());
            INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, PROCEDURE_NAME, CONTEXT, CALL_STATUS, STATUS, LATENCY_MS, PROMPT, RESPONSE)
            SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', ''WORKFLOW_INVESTIGATE_ANOMALY'', ''fraud_investigation:attempt'' || :v_attempts, ''ERROR'', ''ERROR'', :v_elapsed_ms, LEFT(:v_prompt, 5000), LEFT(SQLERRM, 1000);
        END;
    END WHILE;
    IF (:v_decision IS NULL) THEN
        v_decision := ''ESCALATE''; v_reason := ''AI could not return a valid decision; routed to human review.'';
        v_assessment := NVL(:v_assessment, ''No assessment returned.'');
    END IF;
    UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''INVESTIGATING'', AI_RISK_ASSESSMENT = :v_assessment,
        AI_RECOMMENDED_ACTION = :v_decision, AI_DECISION_REASON = LEFT(:v_reason, 2000), AI_ANALYZED_AT = CURRENT_TIMESTAMP()
    WHERE ALERT_ID = :P_ALERT_ID;
    RETURN ''{"workflow":"INVESTIGATE_ANOMALY","alert_id":'' || :P_ALERT_ID || '',"ai_decision":"'' || :v_decision || ''","sanctions_matches":'' || :v_sanction_hits || '',"band":"'' || :v_cpk_band || ''"}'';
END
';

CREATE OR REPLACE PROCEDURE MENDIX_APP.AGENTS.WORKFLOW_SANCTIONS_SCREEN("P_ENTITY_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Screens entity against US ITA export-screened-entities via V_SANCTIONS_SCREENING_SOURCE.'
EXECUTE AS CALLER
AS 'DECLARE v_match_count NUMBER DEFAULT 0; v_basis VARCHAR DEFAULT ''NONE''; v_result VARCHAR;
BEGIN
    SELECT COUNT(*) INTO :v_match_count FROM MENDIX_APP.AGENTS.V_SANCTIONS_SCREENING_SOURCE
    WHERE UPPER(ENTITY_NAME) LIKE ''%'' || UPPER(:P_ENTITY_NAME) || ''%'';
    SELECT COALESCE(MAX(RECORD_BASIS), ''NONE'') INTO :v_basis FROM MENDIX_APP.AGENTS.V_SANCTIONS_SCREENING_SOURCE;
    IF (:v_match_count > 0) THEN
        v_result := ''{"workflow":"SANCTIONS_SCREEN","entity":"'' || :P_ENTITY_NAME || ''","matches_found":'' || :v_match_count || '',"risk_level":"CRITICAL","data_basis":"'' || :v_basis || ''","action":"BLOCK"}'';
    ELSE
        v_result := ''{"workflow":"SANCTIONS_SCREEN","entity":"'' || :P_ENTITY_NAME || ''","matches_found":0,"risk_level":"CLEAR","data_basis":"'' || :v_basis || ''","action":"Entity cleared for trade."}'';
    END IF;
    RETURN :v_result;
END';
