-- 80_streams: STREAM (7 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

create or replace stream MENDIX_APP.AGENTS.BL_CHANGE_STREAM on table BILL_OF_LADING append_only = true;

create or replace stream MENDIX_APP.AGENTS.BL_COMPLIANCE_STREAM on table BILL_OF_LADING;

create or replace stream MENDIX_APP.AGENTS.BL_INSIGHTS_STREAM on table BILL_OF_LADING;

create or replace stream MENDIX_APP.AGENTS.EXTRACTED_DOCS_STREAM on table BILL_OF_LADING_EXTRACTED;

create or replace stream MENDIX_APP.AGENTS.FRAUD_EXPLAIN_STREAM on table FRAUD_ALERT;

create or replace stream MENDIX_APP.AGENTS.FRAUD_NOTIFY_STREAM on table FRAUD_ALERT;

create or replace stream MENDIX_APP.AGENTS.NEW_PDF_STREAM on directory(@LOGISTICS_STAGE);
