-- 95_streamlit: STREAMLIT (1 statement(s))
-- Generated by tools/split_ddl.py. Run chunks in filename order.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

create or replace streamlit MENDIX_APP.AGENTS.VF_LOGISTICS_DASHBOARD
	root_location='@MENDIX_APP.AGENTS.STREAMLIT_STAGE
	main_file='app.py'
	query_warehouse='COMPUTE_WH'
	title='VF Logistics Dashboard';
create or replace cortex search service MENDIX_APP.AGENTS.BL_SEARCH_SERVICE
	ON SEARCH_TEXT
	warehouse='COMPUTE_WH'
	target_lag='1 hour'
	refresh_mode=INCREMENTAL
	as (
    SELECT SEARCH_TEXT, STATUS, CARRIER_NAME, PORT_OF_LOADING_LOCODE,
           PORT_OF_DISCHARGE_LOCODE, BL_NUMBER, BL_ID, TOTAL_CHARGES
    FROM MENDIX_APP.AGENTS.BL_SEARCH_CORPUS
  );
