create or replace database MENDIX_APP;

create or replace schema AGENTS;

create or replace tag DATA_DOMAIN COMMENT='Business domain classification'
;
create or replace tag DATA_OWNER COMMENT='Team or person responsible for data quality'
;
create or replace tag DATA_SENSITIVITY COMMENT='Data sensitivity level: PUBLIC, INTERNAL, CONFIDENTIAL, RESTRICTED'
;
create or replace tag PII_FLAG COMMENT='Contains Personally Identifiable Information: YES/NO'
;
create or replace TABLE AI_ANOMALY_REPORT (
	REPORT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ANOMALY_TYPE VARCHAR(50),
	SEVERITY VARCHAR(20),
	BL_IDS VARCHAR(200),
	BUSINESS_EXPLANATION VARCHAR(2000),
	RECOMMENDED_ACTIONS VARCHAR(1000),
	GENERATED_BY VARCHAR(50) DEFAULT 'AI_AUTO',
	LANGUAGE VARCHAR(5) DEFAULT 'EN',
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(20) DEFAULT 'NEW',
	primary key (REPORT_ID)
);
create or replace TABLE AI_CALL_LOG (
	CALL_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	MODEL_NAME VARCHAR(50),
	PROMPT VARCHAR(5000),
	RESPONSE VARCHAR(10000),
	TOTAL_TOKENS NUMBER(10,0),
	CALL_STATUS VARCHAR(20),
	ERROR_MESSAGE VARCHAR(1000),
	CALL_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CONTEXT VARCHAR(100),
	PROCEDURE_NAME VARCHAR(100),
	INPUT_TOKENS NUMBER(10,0),
	OUTPUT_TOKENS NUMBER(10,0),
	LATENCY_MS NUMBER(10,0),
	STATUS VARCHAR(20),
	LOG_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	primary key (CALL_ID)
);
create or replace TABLE AI_CLASSIFICATION_CACHE (
	CACHE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DOC_HASH VARCHAR(64),
	DOC_TEXT VARCHAR(5000),
	DOC_TYPE VARCHAR(50),
	CONFIDENCE_SCORE FLOAT,
	MODEL_NAME VARCHAR(50),
	CACHED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LAST_USED_AT TIMESTAMP_NTZ(9),
	HIT_COUNT NUMBER(10,0) DEFAULT 1,
	primary key (CACHE_ID)
);
create or replace TABLE ANALYTICS_AI_DAILY_REPORT (
	REPORT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	REPORT_DATE DATE,
	TOTAL_BLS NUMBER(10,0),
	FRAUD_ALERTS NUMBER(10,0),
	AI_COST_USD FLOAT,
	AVG_CONFIDENCE_SCORE FLOAT,
	GENERATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (REPORT_ID)
);
create or replace TABLE ANALYTICS_CARRIER_PERFORMANCE (
	CARRIER_NAME VARCHAR(100) NOT NULL,
	REPORT_MONTH DATE NOT NULL,
	TOTAL_SHIPMENTS NUMBER(10,0),
	ON_TIME_DELIVERY_PCT FLOAT,
	AVG_TRANSIT_DAYS FLOAT,
	TOTAL_REVENUE FLOAT,
	primary key (CARRIER_NAME, REPORT_MONTH)
);
create or replace TABLE ANALYTICS_ROUTE_SUMMARY (
	PORT_PAIR VARCHAR(50) NOT NULL,
	REPORT_MONTH DATE NOT NULL,
	TOTAL_SHIPMENTS NUMBER(10,0),
	AVG_FREIGHT_COST FLOAT,
	AVG_TRANSIT_DAYS FLOAT,
	primary key (PORT_PAIR, REPORT_MONTH)
);
create or replace TABLE APP_CONFIG (
	CONFIG_KEY VARCHAR(100) NOT NULL,
	CONFIG_VALUE VARCHAR(1000),
	CONFIG_TYPE VARCHAR(50),
	DESCRIPTION VARCHAR(500),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_BY VARCHAR(100) DEFAULT 'SYSTEM',
	primary key (CONFIG_KEY)
);
create or replace TABLE BILL_OF_LADING cluster by (STATUS, CARRIER_NAME, CREATED_AT)(
	BL_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	BL_NUMBER VARCHAR(50),
	SHIPPER_NAME VARCHAR(200) WITH TAG (MENDIX_APP.AGENTS.PII_FLAG='YES'),
	SHIPPER_ADDRESS VARCHAR(500),
	CONSIGNEE_NAME VARCHAR(200) WITH TAG (MENDIX_APP.AGENTS.PII_FLAG='YES'),
	CONSIGNEE_ADDRESS VARCHAR(500),
	NOTIFY_PARTY VARCHAR(200) WITH TAG (MENDIX_APP.AGENTS.PII_FLAG='YES'),
	PORT_OF_LOADING_LOCODE VARCHAR(10),
	PORT_OF_DISCHARGE_LOCODE VARCHAR(10),
	PLACE_OF_RECEIPT VARCHAR(100),
	PLACE_OF_DELIVERY VARCHAR(100),
	VESSEL_NAME VARCHAR(100),
	VOYAGE_NUMBER VARCHAR(50),
	CONTAINER_NUMBER VARCHAR(15),
	CONTAINER_SIZE VARCHAR(10),
	SEAL_NUMBER VARCHAR(20),
	HS_CODE VARCHAR(10),
	COMMODITY_DESCRIPTION VARCHAR(1000),
	PACKAGE_COUNT NUMBER(10,0),
	PACKAGE_TYPE VARCHAR(50),
	GROSS_WEIGHT_KGS FLOAT,
	VOLUME_CBM FLOAT,
	FREIGHT_TERMS VARCHAR(20),
	FREIGHT_AMOUNT FLOAT,
	CURRENCY_CODE VARCHAR(5) DEFAULT 'USD',
	TOTAL_CHARGES FLOAT,
	SHIPPER_REFERENCE VARCHAR(100),
	CONSIGNEE_REFERENCE VARCHAR(100),
	CARRIER_NAME VARCHAR(100),
	CARRIER_BOOKING_NUMBER VARCHAR(50),
	BL_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(50) DEFAULT 'DRAFT',
	PAYMENT_STATUS VARCHAR(50) DEFAULT 'UNPAID',
	IS_DANGEROUS_GOODS BOOLEAN DEFAULT FALSE,
	VGM_DECLARED BOOLEAN DEFAULT FALSE,
	SYNCED_TO_ERP BOOLEAN DEFAULT FALSE,
	SAP_DOCUMENT_NUMBER VARCHAR(50),
	COMPLIANCE_CHECK_PASSED BOOLEAN,
	FRAUD_CHECK_PASSED BOOLEAN,
	REMARKS VARCHAR(2000),
	ETD DATE,
	ETA DATE,
	CONTAINER_TYPE VARCHAR(100),
	AI_CONFIDENCE_SCORE FLOAT,
	PROCESSED_AT TIMESTAMP_NTZ(9),
	unique (BL_NUMBER),
	primary key (BL_ID)
) WITH TAG (MENDIX_APP.AGENTS.DATA_DOMAIN='LOGISTICS', MENDIX_APP.AGENTS.DATA_OWNER='Operations Team', MENDIX_APP.AGENTS.DATA_SENSITIVITY='CONFIDENTIAL', MENDIX_APP.AGENTS.PII_FLAG='YES')
;
create or replace TABLE BILL_OF_LADING_EXTRACTED (
	DOC_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	FILE_NAME VARCHAR(500) NOT NULL,
	FILE_PATH VARCHAR(1000),
	FILE_SIZE_BYTES NUMBER(38,0),
	UPLOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	BL_NUMBER VARCHAR(50),
	CONTAINER_NUMBER VARCHAR(20),
	VESSEL_NAME VARCHAR(200),
	VOYAGE_NUMBER VARCHAR(50),
	SHIPPER_NAME VARCHAR(500),
	CONSIGNEE_NAME VARCHAR(500),
	NOTIFY_PARTY VARCHAR(500),
	PORT_OF_LOADING VARCHAR(200),
	PORT_OF_DISCHARGE VARCHAR(200),
	COMMODITY_DESC VARCHAR(2000),
	HS_CODE VARCHAR(20),
	GROSS_WEIGHT_KG FLOAT,
	NET_WEIGHT_KG FLOAT,
	PACKAGE_COUNT NUMBER(38,0),
	PACKAGE_TYPE VARCHAR(100),
	FREIGHT_CHARGES FLOAT,
	FREIGHT_CURRENCY VARCHAR(3) DEFAULT 'USD',
	DATE_OF_ISSUE DATE,
	CONFIDENCE_SCORE FLOAT,
	STATUS VARCHAR(30),
	ANOMALY_FLAGS VARIANT,
	RAW_EXTRACTED_JSON VARIANT,
	RAW_TEXT VARCHAR(16777216),
	AI_MODEL_USED VARCHAR(50),
	PROCESSING_TIME_MS NUMBER(38,0),
	PROCESSED_AT TIMESTAMP_NTZ(9),
	REVIEWED_BY VARCHAR(100),
	REVIEWED_AT TIMESTAMP_NTZ(9),
	REVIEW_NOTES VARCHAR(2000),
	FINAL_STATUS VARCHAR(30),
	CORRECTED_JSON VARIANT,
	PDF_PRESIGNED_URL VARCHAR(5000),
	PDF_URL_EXPIRY TIMESTAMP_NTZ(9),
	primary key (DOC_ID)
) WITH TAG (MENDIX_APP.AGENTS.DATA_DOMAIN='AI_PROCESSING', MENDIX_APP.AGENTS.DATA_OWNER='AI Team', MENDIX_APP.AGENTS.DATA_SENSITIVITY='CONFIDENTIAL', MENDIX_APP.AGENTS.PII_FLAG='NO')
;
create or replace TABLE BL_SEARCH_CORPUS (
	BL_ID NUMBER(38,0),
	BL_NUMBER VARCHAR(50),
	SEARCH_TEXT VARCHAR(1657),
	STATUS VARCHAR(50),
	CARRIER_NAME VARCHAR(100),
	TOTAL_CHARGES FLOAT,
	PORT_OF_LOADING_LOCODE VARCHAR(10),
	PORT_OF_DISCHARGE_LOCODE VARCHAR(10),
	CREATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE CHAT_SESSION (
	SESSION_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	USER_ID VARCHAR(100),
	BL_ID NUMBER(38,0),
	SESSION_START TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	SESSION_END TIMESTAMP_NTZ(9),
	MESSAGE_COUNT NUMBER(10,0) DEFAULT 0,
	LANGUAGE VARCHAR(5) DEFAULT 'EN',
	TOKENS_USED NUMBER(10,0) DEFAULT 0,
	CREATED_AT TIMESTAMP_NTZ(9),
	primary key (SESSION_ID)
);
create or replace TABLE COMPLIANCE_CHECK_RESULT (
	CHECK_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	BL_ID NUMBER(38,0),
	CHECK_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	COMPLIANT BOOLEAN,
	VIOLATIONS VARCHAR(1000),
	RISK_SCORE NUMBER(10,0),
	RULES_CHECKED NUMBER(10,0),
	primary key (CHECK_ID)
);
create or replace TABLE CONTAINER_PHOTO_VERIFICATION (
	PHOTO_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CONTAINER_NUMBER VARCHAR(15),
	BL_ID NUMBER(38,0),
	PHOTO_URL VARCHAR(500),
	UPLOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	VERIFICATION_STATUS VARCHAR(20) DEFAULT 'PENDING',
	VERIFIED_BY VARCHAR(100),
	VERIFIED_AT TIMESTAMP_NTZ(9),
	REMARKS VARCHAR(1000),
	primary key (PHOTO_ID)
);
create or replace TABLE DOCUMENT_DISCREPANCY (
	DISCREPANCY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	BL_ID NUMBER(38,0),
	FIELD_NAME VARCHAR(100),
	EXPECTED_VALUE VARCHAR(500),
	ACTUAL_VALUE VARCHAR(500),
	SEVERITY VARCHAR(20),
	DETECTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(20) DEFAULT 'OPEN',
	RESOLVED_AT TIMESTAMP_NTZ(9),
	primary key (DISCREPANCY_ID)
);
create or replace dynamic table DT_CARRIER_PERFORMANCE(
	CARRIER_NAME,
	TOTAL_SHIPMENTS,
	AVG_CHARGES,
	TOTAL_REVENUE,
	AVG_WEIGHT_KGS,
	DELIVERED_COUNT,
	DELIVERY_SUCCESS_RATE_PCT
) target_lag = '5 minutes' refresh_mode = AUTO initialize = ON_CREATE warehouse = COMPUTE_WH
 as
SELECT 
    CARRIER_NAME,
    COUNT(*) as TOTAL_SHIPMENTS,
    ROUND(AVG(TOTAL_CHARGES), 2) as AVG_CHARGES,
    ROUND(SUM(TOTAL_CHARGES), 2) as TOTAL_REVENUE,
    ROUND(AVG(GROSS_WEIGHT_KGS), 2) as AVG_WEIGHT_KGS,
    SUM(CASE WHEN STATUS = 'Delivered' THEN 1 ELSE 0 END) as DELIVERED_COUNT,
    ROUND(
        SUM(CASE WHEN STATUS = 'Delivered' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0),
        2
    ) as DELIVERY_SUCCESS_RATE_PCT
FROM BILL_OF_LADING
WHERE CARRIER_NAME IS NOT NULL
GROUP BY CARRIER_NAME;
create or replace dynamic table DT_ROUTE_ANALYTICS(
	ROUTE,
	ORIGIN_PORT,
	DEST_PORT,
	TOTAL_SHIPMENTS,
	AVG_FREIGHT_COST,
	AVG_WEIGHT_KGS,
	MIN_CHARGES,
	MAX_CHARGES
) target_lag = '5 minutes' refresh_mode = AUTO initialize = ON_CREATE warehouse = COMPUTE_WH
 as
SELECT 
    PORT_OF_LOADING_LOCODE || '_TO_' || PORT_OF_DISCHARGE_LOCODE as ROUTE,
    PORT_OF_LOADING_LOCODE as ORIGIN_PORT,
    PORT_OF_DISCHARGE_LOCODE as DEST_PORT,
    COUNT(*) as TOTAL_SHIPMENTS,
    ROUND(AVG(TOTAL_CHARGES), 2) as AVG_FREIGHT_COST,
    ROUND(AVG(GROSS_WEIGHT_KGS), 2) as AVG_WEIGHT_KGS,
    MIN(TOTAL_CHARGES) as MIN_CHARGES,
    MAX(TOTAL_CHARGES) as MAX_CHARGES
FROM BILL_OF_LADING
WHERE PORT_OF_LOADING_LOCODE IS NOT NULL 
  AND PORT_OF_DISCHARGE_LOCODE IS NOT NULL
GROUP BY PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE;
create or replace dynamic table DT_SHIPMENT_KPI(
	TOTAL_SHIPMENTS,
	SAP_POSTED,
	PENDING_REVIEW,
	IN_TRANSIT,
	DELIVERED,
	AVG_CHARGES_USD,
	TOTAL_REVENUE_USD,
	AVG_WEIGHT_KGS,
	LAST_BL_CREATED_AT,
	REFRESHED_AT
) target_lag = '1 minute' refresh_mode = AUTO initialize = ON_CREATE warehouse = COMPUTE_WH
 as
SELECT 
    COUNT(*) as TOTAL_SHIPMENTS,
    SUM(CASE WHEN STATUS = 'SAP_POSTED' THEN 1 ELSE 0 END) as SAP_POSTED,
    SUM(CASE WHEN STATUS = 'Pending_Review' THEN 1 ELSE 0 END) as PENDING_REVIEW,
    SUM(CASE WHEN STATUS = 'In_Transit' THEN 1 ELSE 0 END) as IN_TRANSIT,
    SUM(CASE WHEN STATUS = 'Delivered' THEN 1 ELSE 0 END) as DELIVERED,
    ROUND(AVG(TOTAL_CHARGES), 2) as AVG_CHARGES_USD,
    ROUND(SUM(TOTAL_CHARGES), 2) as TOTAL_REVENUE_USD,
    ROUND(AVG(GROSS_WEIGHT_KGS), 2) as AVG_WEIGHT_KGS,
    MAX(CREATED_AT) as LAST_BL_CREATED_AT,
    CURRENT_TIMESTAMP() as REFRESHED_AT
FROM BILL_OF_LADING;
create or replace TABLE ERROR_LOG (
	ERROR_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	ERROR_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	PROCEDURE_NAME VARCHAR(200),
	ERROR_CODE VARCHAR(20),
	ERROR_MESSAGE VARCHAR(5000),
	CONTEXT VARCHAR(1000),
	SEVERITY VARCHAR(20) DEFAULT 'ERROR',
	FILE_NAME VARCHAR(500),
	RESOLVED BOOLEAN DEFAULT FALSE
);
create or replace TABLE FRAUD_ALERT (
	ALERT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ALERT_TYPE VARCHAR(50),
	SEVERITY VARCHAR(20),
	DESCRIPTION VARCHAR(1000),
	DOCUMENT_IDS VARCHAR(200),
	STATUS VARCHAR(20) DEFAULT 'OPEN',
	ASSIGNED_TO VARCHAR(100),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	RESOLVED_AT TIMESTAMP_NTZ(9),
	RESOLUTION_NOTES VARCHAR(2000),
	BL_ID NUMBER(38,0),
	DETECTED_AT TIMESTAMP_NTZ(9),
	primary key (ALERT_ID)
) WITH TAG (MENDIX_APP.AGENTS.DATA_DOMAIN='COMPLIANCE', MENDIX_APP.AGENTS.DATA_OWNER='Compliance Team', MENDIX_APP.AGENTS.DATA_SENSITIVITY='RESTRICTED', MENDIX_APP.AGENTS.PII_FLAG='NO')
;
create or replace TABLE HS_CODE_REFERENCE (
	HS_CODE VARCHAR(10) NOT NULL,
	DESCRIPTION VARCHAR(500),
	CATEGORY VARCHAR(100),
	IS_DANGEROUS_GOODS BOOLEAN DEFAULT FALSE,
	IS_RESTRICTED BOOLEAN DEFAULT FALSE,
	REQUIRES_PERMIT BOOLEAN DEFAULT FALSE,
	UNIT_OF_MEASURE VARCHAR(10),
	DUTY_RATE_PCT FLOAT,
	DG_CLASS VARCHAR(20),
	primary key (HS_CODE)
) WITH TAG (MENDIX_APP.AGENTS.DATA_DOMAIN='REFERENCE', MENDIX_APP.AGENTS.DATA_OWNER='Operations Team', MENDIX_APP.AGENTS.DATA_SENSITIVITY='PUBLIC', MENDIX_APP.AGENTS.PII_FLAG='NO')
;
create or replace TABLE NOTIFICATION_LOG (
	NOTIFICATION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	NOTIFICATION_TYPE VARCHAR(50),
	RECIPIENT VARCHAR(200) WITH TAG (MENDIX_APP.AGENTS.PII_FLAG='YES'),
	SUBJECT VARCHAR(500),
	BODY VARCHAR(5000),
	SENT_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(50) DEFAULT 'QUEUED'
) WITH TAG (MENDIX_APP.AGENTS.DATA_DOMAIN='OPERATIONS', MENDIX_APP.AGENTS.DATA_OWNER='Operations Team', MENDIX_APP.AGENTS.DATA_SENSITIVITY='INTERNAL', MENDIX_APP.AGENTS.PII_FLAG='YES')
;
create or replace TABLE PARSED_DOCUMENTS (
	DOC_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	FILE_NAME VARCHAR(500),
	FILE_PATH VARCHAR(1000),
	PARSED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	DOCUMENT_TYPE VARCHAR(100),
	EXTRACTED_DATA VARIANT,
	RAW_TEXT VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT,
	STATUS VARCHAR(50) DEFAULT 'PROCESSED',
	PARSER_MODEL VARCHAR(100) DEFAULT 'mistral-large2',
	PROCESSING_TIME_MS NUMBER(38,0)
);
create or replace TABLE PORT_MASTER (
	PORT_CODE VARCHAR(10) NOT NULL,
	PORT_NAME VARCHAR(200),
	COUNTRY VARCHAR(100),
	COUNTRY_CODE VARCHAR(5),
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	PORT_TYPE VARCHAR(50),
	TIMEZONE VARCHAR(50),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	primary key (PORT_CODE)
);
create or replace TABLE SAP_CO_COST_ALLOCATION (
	ALLOCATION_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	COST_CENTER VARCHAR(10),
	COST_ELEMENT VARCHAR(10),
	AMOUNT FLOAT,
	CURRENCY_CODE VARCHAR(5),
	FISCAL_PERIOD NUMBER(3,0),
	FISCAL_YEAR NUMBER(4,0),
	BL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ALLOCATION_ID)
);
create or replace TABLE SAP_FI_DOCUMENT (
	FI_DOC_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SAP_DOCUMENT_NUMBER VARCHAR(10),
	COMPANY_CODE VARCHAR(4),
	FISCAL_YEAR NUMBER(4,0),
	POSTING_DATE DATE,
	DOCUMENT_TYPE VARCHAR(2),
	REFERENCE VARCHAR(16),
	DOCUMENT_HEADER_TEXT VARCHAR(25),
	CURRENCY_CODE VARCHAR(5),
	TOTAL_AMOUNT FLOAT,
	BL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (FI_DOC_ID)
);
create or replace TABLE SAP_FI_LINE_ITEM (
	LINE_ITEM_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SAP_DOCUMENT_NUMBER VARCHAR(10),
	LINE_ITEM_NUMBER NUMBER(3,0),
	GL_ACCOUNT VARCHAR(10),
	AMOUNT FLOAT,
	CURRENCY_CODE VARCHAR(5),
	COST_CENTER VARCHAR(10),
	PROFIT_CENTER VARCHAR(10),
	TEXT VARCHAR(50),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (LINE_ITEM_ID)
);
create or replace TABLE SAP_MM_GOODS_RECEIPT (
	GR_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	MATERIAL_DOCUMENT VARCHAR(10),
	MATERIAL_DOC_YEAR NUMBER(4,0),
	POSTING_DATE DATE,
	DOCUMENT_DATE DATE,
	MATERIAL_NUMBER VARCHAR(18),
	PLANT VARCHAR(4),
	STORAGE_LOCATION VARCHAR(4),
	QUANTITY FLOAT,
	UNIT_OF_MEASURE VARCHAR(3),
	BL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (GR_ID)
);
create or replace TABLE SAP_SD_DELIVERY (
	DELIVERY_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DELIVERY_NUMBER VARCHAR(10),
	DELIVERY_DATE DATE,
	SHIPPING_POINT VARCHAR(4),
	SOLD_TO_PARTY VARCHAR(10),
	SHIP_TO_PARTY VARCHAR(10),
	TOTAL_WEIGHT FLOAT,
	WEIGHT_UNIT VARCHAR(3),
	BL_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (DELIVERY_ID)
);
create or replace TABLE VESSEL_REGISTRY (
	VESSEL_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	VESSEL_NAME VARCHAR(100),
	IMO_NUMBER VARCHAR(10),
	FLAG VARCHAR(50),
	GROSS_TONNAGE NUMBER(10,0),
	BUILT_YEAR NUMBER(4,0),
	VESSEL_TYPE VARCHAR(50),
	OPERATOR_NAME VARCHAR(100),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	unique (VESSEL_NAME),
	unique (IMO_NUMBER),
	primary key (VESSEL_ID)
);
create or replace TABLE WORKFLOW_AUDIT_LOG (
	AUDIT_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	WORKFLOW_NAME VARCHAR(100),
	STEP_NAME VARCHAR(100),
	STEP_ORDER NUMBER(38,0),
	INPUT_PARAMS VARCHAR(2000),
	OUTPUT_RESULT VARCHAR(5000),
	EXECUTION_TIME_MS NUMBER(38,0),
	STATUS VARCHAR(20),
	EXECUTED_BY VARCHAR(200) DEFAULT CURRENT_USER(),
	EXECUTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace view V_AGENT_DATA_SUMMARY(
	BL_ID,
	BL_NUMBER,
	SHIPPER_NAME,
	CONSIGNEE_NAME,
	ORIGIN_PORT,
	DEST_PORT,
	CARRIER_NAME,
	VESSEL_NAME,
	CONTAINER_NUMBER,
	CONTAINER_SIZE,
	HS_CODE,
	COMMODITY_DESCRIPTION,
	GROSS_WEIGHT_KGS,
	TOTAL_CHARGES,
	STATUS,
	PAYMENT_STATUS,
	IS_DANGEROUS_GOODS,
	ETD,
	ETA,
	BL_DATE,
	SYNCED_TO_ERP,
	FREIGHT_TERMS
) as
SELECT 
    BL_ID, BL_NUMBER, SHIPPER_NAME, CONSIGNEE_NAME,
    PORT_OF_LOADING_LOCODE as ORIGIN_PORT, PORT_OF_DISCHARGE_LOCODE as DEST_PORT,
    CARRIER_NAME, VESSEL_NAME, CONTAINER_NUMBER, CONTAINER_SIZE,
    HS_CODE, COMMODITY_DESCRIPTION, GROSS_WEIGHT_KGS, TOTAL_CHARGES,
    STATUS, PAYMENT_STATUS, IS_DANGEROUS_GOODS, ETD, ETA, BL_DATE,
    SYNCED_TO_ERP, FREIGHT_TERMS
FROM BILL_OF_LADING;
create or replace view V_AI_DAILY_COST(
	DAY,
	TOTAL_CALLS,
	TOTAL_TOKENS,
	INPUT_TOKENS,
	OUTPUT_TOKENS,
	AVG_LATENCY_MS,
	ESTIMATED_COST_USD,
	ERRORS
) as
SELECT 
    DATE(CALL_TIMESTAMP) as DAY,
    COUNT(*) as TOTAL_CALLS,
    SUM(TOTAL_TOKENS) as TOTAL_TOKENS,
    SUM(CASE WHEN TOTAL_TOKENS IS NOT NULL THEN TOTAL_TOKENS * 0.6 / 1000000 ELSE 0 END) as INPUT_TOKENS,
    SUM(CASE WHEN TOTAL_TOKENS IS NOT NULL THEN TOTAL_TOKENS * 0.4 / 1000000 ELSE 0 END) as OUTPUT_TOKENS,
    ROUND(AVG(DATEDIFF('SECOND', CALL_TIMESTAMP, CALL_TIMESTAMP)) * 1000, 0) as AVG_LATENCY_MS,
    ROUND(SUM(COALESCE(TOTAL_TOKENS, 0)) * 0.0000015, 6) as ESTIMATED_COST_USD,
    SUM(CASE WHEN CALL_STATUS = 'ERROR' THEN 1 ELSE 0 END) as ERRORS
FROM AI_CALL_LOG
GROUP BY DATE(CALL_TIMESTAMP);
create or replace view V_AI_USAGE_SUMMARY(
	PROCEDURE_NAME,
	CALL_COUNT,
	TOTAL_TOKENS,
	AVG_LATENCY_MS,
	SUCCESS_COUNT,
	ERROR_COUNT,
	ERROR_RATE_PCT
) as
SELECT 
    CONTEXT as PROCEDURE_NAME,
    COUNT(*) as CALL_COUNT,
    SUM(COALESCE(TOTAL_TOKENS, 0)) as TOTAL_TOKENS,
    ROUND(AVG(DATEDIFF('SECOND', CALL_TIMESTAMP, CALL_TIMESTAMP)) * 1000, 0) as AVG_LATENCY_MS,
    SUM(CASE WHEN CALL_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) as SUCCESS_COUNT,
    SUM(CASE WHEN CALL_STATUS = 'ERROR' THEN 1 ELSE 0 END) as ERROR_COUNT,
    ROUND(SUM(CASE WHEN CALL_STATUS = 'ERROR' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 1) as ERROR_RATE_PCT
FROM AI_CALL_LOG
GROUP BY CONTEXT;
create or replace view V_EXCHANGE_RATES(
	QUOTE_CURRENCY_ID,
	EXCHANGE_RATE,
	RATE_DATE
) as
SELECT 
    QUOTE_CURRENCY_ID,
    ROUND(VALUE, 2) as EXCHANGE_RATE, 
    DATE as RATE_DATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FX_RATES_TIMESERIES
WHERE BASE_CURRENCY_ID = 'USD'
AND QUOTE_CURRENCY_ID IN ('EUR','GBP','JPY','VND','CNY','SGD','KRW','THB','AUD','INR')
QUALIFY ROW_NUMBER() OVER (PARTITION BY QUOTE_CURRENCY_ID ORDER BY DATE DESC) = 1;
create or replace view V_EXPORT_RESTRICTED_ENTITIES(
	ENTITY_NAME,
	COUNTRY,
	LIST_TYPE,
	EFFECTIVE_DATE
) as
SELECT 
    EXPORT_RESTRICTED_ENTITY_NAME as ENTITY_NAME,
    COALESCE(GEO_ID_COUNTRY, 'Unknown') as COUNTRY,
    SOURCE as LIST_TYPE,
    START_DATE as EFFECTIVE_DATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.INTERNATIONAL_TRADE_ADMINISTRATION_EXPORT_SCREENED_ENTITIES_INDEX_PIT
WHERE _EFFECTIVE_END_TIMESTAMP IS NOT NULL
AND EXPORT_RESTRICTED_ENTITY_NAME IS NOT NULL;
create or replace view V_EXTRACTION_METRICS(
	TOTAL_DOCUMENTS,
	AUTO_APPROVED,
	PENDING_REVIEW,
	SYNCED_TO_SAP,
	REJECTED,
	AUTO_APPROVAL_RATE_PCT,
	AVG_CONFIDENCE_SCORE,
	MEDIAN_CONFIDENCE_SCORE,
	AVG_PROCESSING_MS,
	MAX_PROCESSING_MS,
	PIPELINE_ERRORS_TOTAL,
	ERRORS_LAST_24H,
	UNRESOLVED_ERRORS,
	SUCCESS_RATE_PCT,
	DOCS_CONFIDENCE_100,
	DOCS_CONFIDENCE_75,
	DOCS_CONFIDENCE_50,
	DOCS_CONFIDENCE_25,
	DOCS_CONFIDENCE_0,
	FIRST_PROCESSED,
	LAST_PROCESSED,
	REPORT_GENERATED_AT
) COMMENT='AI extraction pipeline KPIs: accuracy, confidence distribution, error rates, processing speed. Use for dashboards and SLA monitoring.'
 as
WITH extraction_stats AS (
    SELECT
        COUNT(*) as TOTAL_DOCUMENTS,
        COUNT(CASE WHEN STATUS = 'AI_Processed' THEN 1 END) as AUTO_APPROVED,
        COUNT(CASE WHEN STATUS = 'Pending_Review' THEN 1 END) as PENDING_REVIEW,
        COUNT(CASE WHEN STATUS = 'Synced_To_SAP' THEN 1 END) as SYNCED_TO_SAP,
        COUNT(CASE WHEN STATUS = 'Rejected' THEN 1 END) as REJECTED,
        AVG(CONFIDENCE_SCORE) as AVG_CONFIDENCE,
        MEDIAN(CONFIDENCE_SCORE) as MEDIAN_CONFIDENCE,
        AVG(PROCESSING_TIME_MS) as AVG_PROCESSING_MS,
        MAX(PROCESSING_TIME_MS) as MAX_PROCESSING_MS,
        MIN(PROCESSED_AT) as FIRST_PROCESSED,
        MAX(PROCESSED_AT) as LAST_PROCESSED
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
),
error_stats AS (
    SELECT
        COUNT(*) as TOTAL_ERRORS,
        COUNT(CASE WHEN ERROR_TIMESTAMP > DATEADD('HOUR', -24, CURRENT_TIMESTAMP()) THEN 1 END) as ERRORS_LAST_24H,
        COUNT(CASE WHEN RESOLVED = FALSE THEN 1 END) as UNRESOLVED_ERRORS
    FROM MENDIX_APP.AGENTS.ERROR_LOG
    WHERE PROCEDURE_NAME = 'PROCESS_BL_DOCUMENTS'
),
confidence_dist AS (
    SELECT
        COUNT(CASE WHEN CONFIDENCE_SCORE = 100 THEN 1 END) as SCORE_100,
        COUNT(CASE WHEN CONFIDENCE_SCORE = 75 THEN 1 END) as SCORE_75,
        COUNT(CASE WHEN CONFIDENCE_SCORE = 50 THEN 1 END) as SCORE_50,
        COUNT(CASE WHEN CONFIDENCE_SCORE = 25 THEN 1 END) as SCORE_25,
        COUNT(CASE WHEN CONFIDENCE_SCORE = 0 THEN 1 END) as SCORE_0
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
)
SELECT
    e.TOTAL_DOCUMENTS,
    e.AUTO_APPROVED,
    e.PENDING_REVIEW,
    e.SYNCED_TO_SAP,
    e.REJECTED,
    ROUND(IFF(e.TOTAL_DOCUMENTS > 0, e.AUTO_APPROVED * 100.0 / e.TOTAL_DOCUMENTS, 0), 1) as AUTO_APPROVAL_RATE_PCT,
    ROUND(e.AVG_CONFIDENCE, 1) as AVG_CONFIDENCE_SCORE,
    ROUND(e.MEDIAN_CONFIDENCE, 1) as MEDIAN_CONFIDENCE_SCORE,
    ROUND(e.AVG_PROCESSING_MS, 0) as AVG_PROCESSING_MS,
    e.MAX_PROCESSING_MS,
    er.TOTAL_ERRORS as PIPELINE_ERRORS_TOTAL,
    er.ERRORS_LAST_24H,
    er.UNRESOLVED_ERRORS,
    ROUND(IFF(e.TOTAL_DOCUMENTS + er.TOTAL_ERRORS > 0, 
        e.TOTAL_DOCUMENTS * 100.0 / (e.TOTAL_DOCUMENTS + er.TOTAL_ERRORS), 0), 1) as SUCCESS_RATE_PCT,
    c.SCORE_100 as DOCS_CONFIDENCE_100,
    c.SCORE_75 as DOCS_CONFIDENCE_75,
    c.SCORE_50 as DOCS_CONFIDENCE_50,
    c.SCORE_25 as DOCS_CONFIDENCE_25,
    c.SCORE_0 as DOCS_CONFIDENCE_0,
    e.FIRST_PROCESSED,
    e.LAST_PROCESSED,
    CURRENT_TIMESTAMP() as REPORT_GENERATED_AT
FROM extraction_stats e
CROSS JOIN error_stats er
CROSS JOIN confidence_dist c;
create or replace view V_PORT_WEATHER_FORECAST(
	PORT_NAME,
	WEATHER_IMPACT,
	WIND_SPEED_KMH,
	FORECAST_DATE
) as
WITH port_stations AS (
    SELECT 'SNM00048698' as STATION_ID, 'Port of Singapore' as PORT_NAME UNION ALL
    SELECT 'CHM00058362', 'Shanghai Port' UNION ALL
    SELECT 'JA000047662', 'Tokyo Port' UNION ALL
    SELECT 'KSM00047159', 'Busan Port' UNION ALL
    SELECT 'NLE00152490', 'Rotterdam Port' UNION ALL
    SELECT 'GM000010147', 'Hamburg Port'
),
latest_temp AS (
    SELECT 
        t.NOAA_WEATHER_STATION_ID,
        t.VALUE as MAX_TEMP_C,
        t.DATE as FORECAST_DATE,
        ROW_NUMBER() OVER (PARTITION BY t.NOAA_WEATHER_STATION_ID ORDER BY t.DATE DESC) as RN
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.NOAA_WEATHER_METRICS_TIMESERIES t
    WHERE t.NOAA_WEATHER_STATION_ID IN (SELECT STATION_ID FROM port_stations)
    AND t.VARIABLE_NAME = 'Maximum temperature'
)
SELECT 
    ps.PORT_NAME,
    CASE 
        WHEN lt.MAX_TEMP_C >= 38 THEN 'Extreme Heat'
        WHEN lt.MAX_TEMP_C <= 0 THEN 'Freezing Warning'
        ELSE 'Good Weather'
    END as WEATHER_IMPACT,
    -- Estimate wind from temp variance (demo purpose)
    ROUND(ABS(lt.MAX_TEMP_C - 25) * 2 + 10, 0) as WIND_SPEED_KMH,
    lt.FORECAST_DATE
FROM port_stations ps
LEFT JOIN latest_temp lt 
    ON ps.STATION_ID = lt.NOAA_WEATHER_STATION_ID AND lt.RN = 1;
create or replace view V_SHIPMENT_KPI_STATIC(
	TOTAL_SHIPMENTS,
	SAP_POSTED,
	PENDING_REVIEW,
	IN_TRANSIT,
	DELIVERED,
	AVG_CHARGES_USD,
	TOTAL_REVENUE_USD,
	AVG_WEIGHT_KGS,
	LAST_BL_CREATED_AT,
	REFRESHED_AT
) as
SELECT 
    COUNT(*) as TOTAL_SHIPMENTS,
    SUM(CASE WHEN STATUS = 'SAP_POSTED' THEN 1 ELSE 0 END) as SAP_POSTED,
    SUM(CASE WHEN STATUS = 'Pending_Review' THEN 1 ELSE 0 END) as PENDING_REVIEW,
    SUM(CASE WHEN STATUS = 'In_Transit' THEN 1 ELSE 0 END) as IN_TRANSIT,
    SUM(CASE WHEN STATUS = 'Delivered' THEN 1 ELSE 0 END) as DELIVERED,
    ROUND(AVG(TOTAL_CHARGES), 2) as AVG_CHARGES_USD,
    ROUND(SUM(TOTAL_CHARGES), 2) as TOTAL_REVENUE_USD,
    ROUND(AVG(GROSS_WEIGHT_KGS), 2) as AVG_WEIGHT_KGS,
    MAX(CREATED_AT) as LAST_BL_CREATED_AT,
    CURRENT_TIMESTAMP() as REFRESHED_AT
FROM BILL_OF_LADING;
CREATE OR REPLACE FILE FORMAT RAW_TEXT
	RECORD_DELIMITER = 'NONE'
	FIELD_DELIMITER = 'NONE'
;
CREATE OR REPLACE PROCEDURE "AI_COMPLETE_WITH_RETRY"("P_PROMPT" VARCHAR, "P_MODEL" VARCHAR DEFAULT 'llama3-8b', "P_MAX_RETRIES" NUMBER(38,0) DEFAULT 2)
RETURNS VARIANT
LANGUAGE SQL
COMMENT='Wrapper for CORTEX.COMPLETE with retry logic. Handles transient AI model failures gracefully with configurable retry count.'
EXECUTE AS OWNER
AS '
DECLARE
    V_RESPONSE VARIANT;
    V_RETRY_COUNT NUMBER DEFAULT 0;
    V_ERROR_MSG VARCHAR;
    V_MODEL_TO_USE VARCHAR DEFAULT P_MODEL;
BEGIN
    -- Retry loop
    WHILE (V_RETRY_COUNT <= P_MAX_RETRIES) DO
        BEGIN
            -- Call Cortex AI Complete
            V_RESPONSE := SNOWFLAKE.CORTEX.COMPLETE(V_MODEL_TO_USE, P_PROMPT);
            
            -- Log success
            INSERT INTO AI_CALL_LOG (MODEL_NAME, PROMPT, RESPONSE, CALL_STATUS, CONTEXT)
            VALUES (V_MODEL_TO_USE, P_PROMPT, V_RESPONSE::VARCHAR, ''SUCCESS'', ''AI_COMPLETE_WITH_RETRY'');
            
            RETURN V_RESPONSE;
        EXCEPTION
            WHEN OTHER THEN
                V_ERROR_MSG := SQLERRM;
                V_RETRY_COUNT := V_RETRY_COUNT + 1;
                
                -- Switch to fallback model if primary fails
                IF (V_RETRY_COUNT = 1 AND V_MODEL_TO_USE = ''llama3-8b'') THEN
                    V_MODEL_TO_USE := ''mistral-large2'';
                END IF;
                
                -- Log error
                INSERT INTO AI_CALL_LOG (MODEL_NAME, PROMPT, CALL_STATUS, ERROR_MESSAGE, CONTEXT)
                VALUES (V_MODEL_TO_USE, P_PROMPT, ''ERROR'', V_ERROR_MSG, ''AI_COMPLETE_WITH_RETRY'');
                
                -- If max retries reached, raise error
                IF (V_RETRY_COUNT > P_MAX_RETRIES) THEN
                    RETURN OBJECT_CONSTRUCT(''error'', TRUE, ''message'', V_ERROR_MSG);
                END IF;
        END;
    END WHILE;
    
    RETURN OBJECT_CONSTRUCT(''error'', TRUE, ''message'', ''Max retries exceeded'');
END;
';
CREATE OR REPLACE PROCEDURE "AI_EXPLAIN_ANOMALY"("P_FRAUD_ALERT_ID" NUMBER(38,0), "P_LANGUAGE" VARCHAR DEFAULT 'EN')
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Uses CORTEX.COMPLETE to generate natural language explanation for fraud alerts. Analyzes shipment context, historical patterns, and peer comparisons.'
EXECUTE AS OWNER
AS '
DECLARE
    V_ALERT_TYPE VARCHAR;
    V_DESCRIPTION VARCHAR;
    V_PROMPT VARCHAR;
    V_EXPLANATION VARCHAR;
    V_RESPONSE VARIANT;
BEGIN
    -- Get alert details
    SELECT ALERT_TYPE, DESCRIPTION
    INTO V_ALERT_TYPE, V_DESCRIPTION
    FROM FRAUD_ALERT
    WHERE ALERT_ID = :P_FRAUD_ALERT_ID;
    
    -- Build explanation prompt
    V_PROMPT := ''You are a logistics fraud analyst. Explain this fraud alert in business terms for '' ||
                CASE :P_LANGUAGE 
                    WHEN ''VN'' THEN ''Vietnamese''
                    WHEN ''JA'' THEN ''Japanese''
                    ELSE ''English''
                END ||
                '' readers. Alert type: '' || :V_ALERT_TYPE || 
                ''. Description: '' || :V_DESCRIPTION ||
                ''. Provide: 1) What happened, 2) Why it matters, 3) Recommended actions. Keep it under 200 words.'';
    
    -- Call AI
    V_RESPONSE := (CALL AI_COMPLETE_WITH_RETRY(:V_PROMPT, ''llama3-8b'', 2));
    V_EXPLANATION := V_RESPONSE::VARCHAR;
    
    -- Store in report table
    INSERT INTO AI_ANOMALY_REPORT (
        ANOMALY_TYPE, 
        SEVERITY, 
        BUSINESS_EXPLANATION, 
        LANGUAGE, 
        STATUS
    )
    VALUES (
        :V_ALERT_TYPE, 
        ''MEDIUM'', 
        :V_EXPLANATION, 
        :P_LANGUAGE, 
        ''NEW''
    );
    
    RETURN V_EXPLANATION;
END;
';
CREATE OR REPLACE PROCEDURE "AI_EXPLAIN_ANOMALY"("P_LANGUAGE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_ALERT_ID NUMBER;
    V_COUNT NUMBER DEFAULT 0;
    V_RESULT VARCHAR;
BEGIN
    -- Find unexplained HIGH alerts
    SELECT COUNT(*) INTO V_COUNT FROM FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'';
    
    IF (V_COUNT = 0) THEN
        RETURN ''{"reports_generated": 0, "message": "No open HIGH alerts to explain"}'';
    END IF;
    
    -- Get first alert
    SELECT ALERT_ID INTO V_ALERT_ID
    FROM FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN''
    ORDER BY CREATED_AT DESC LIMIT 1;
    
    -- Call the main procedure
    CALL AI_EXPLAIN_ANOMALY(:V_ALERT_ID, :P_LANGUAGE);
    
    RETURN ''{"reports_generated": 1, "alert_id": '' || :V_ALERT_ID || ''}'';
EXCEPTION
    WHEN OTHER THEN
        RETURN ''{"reports_generated": 0, "message": "'' || REPLACE(SQLERRM, ''"'', ''\\\\"'') || ''"}'';
END;
';
CREATE OR REPLACE PROCEDURE "AI_GENERATE_INSIGHTS"("P_LANGUAGE" VARCHAR DEFAULT 'EN')
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_TOTAL_BLS NUMBER;
    V_HIGH_RISK NUMBER;
    V_SAP_POSTED NUMBER;
    V_AVG_CHARGES FLOAT;
    V_OPEN_ALERTS NUMBER;
    V_STATS VARCHAR;
    V_PROMPT VARCHAR;
    V_RAW VARCHAR;
    V_INSIGHTS VARCHAR;
    V_START_POS NUMBER;
    V_END_POS NUMBER;
BEGIN
    SELECT 
        COUNT(*),
        SUM(CASE WHEN STATUS = ''Pending_Review'' THEN 1 ELSE 0 END),
        SUM(CASE WHEN STATUS = ''SAP_POSTED'' THEN 1 ELSE 0 END),
        ROUND(AVG(TOTAL_CHARGES), 2)
    INTO V_TOTAL_BLS, V_HIGH_RISK, V_SAP_POSTED, V_AVG_CHARGES
    FROM BILL_OF_LADING;
    
    SELECT COUNT(*) INTO V_OPEN_ALERTS FROM FRAUD_ALERT WHERE STATUS = ''OPEN'';
    
    V_STATS := ''Total BLs: '' || :V_TOTAL_BLS || '', Pending: '' || :V_HIGH_RISK ||
               '', SAP Posted: '' || :V_SAP_POSTED || '', Avg charges: $'' || :V_AVG_CHARGES ||
               '', Open fraud alerts: '' || :V_OPEN_ALERTS;
    
    V_PROMPT := ''Return ONLY a JSON object (no markdown, no explanation). Stats: '' || :V_STATS ||
                ''. Format: {"status":"SUCCESS","insights":[{"category":"RISK","priority":"HIGH","title":"...","insight":"..."},{"category":"OPPORTUNITY","priority":"MEDIUM","title":"...","insight":"..."},{"category":"TREND","priority":"LOW","title":"...","insight":"..."}],"data_summary":"..."}'';

    BEGIN
        SELECT SNOWFLAKE.CORTEX.COMPLETE(''llama3-8b'', :V_PROMPT) INTO V_RAW;
        
        -- Extract JSON from response (find first { and last })
        V_START_POS := POSITION(''{'' IN V_RAW);
        V_END_POS := LENGTH(V_RAW) - POSITION(''}'' IN REVERSE(V_RAW)) + 1;
        
        IF (V_START_POS > 0 AND V_END_POS > V_START_POS) THEN
            V_INSIGHTS := SUBSTRING(V_RAW, V_START_POS, V_END_POS - V_START_POS + 1);
        ELSE
            V_INSIGHTS := ''{"status":"SUCCESS","insights":[{"category":"RISK","priority":"HIGH","title":"Pending Backlog","insight":"'' || :V_HIGH_RISK || '' pending shipments need review"},{"category":"OPPORTUNITY","priority":"MEDIUM","title":"Revenue","insight":"$'' || :V_AVG_CHARGES || '' avg across '' || :V_TOTAL_BLS || '' shipments"},{"category":"TREND","priority":"LOW","title":"Automation","insight":"'' || :V_SAP_POSTED || '' auto-posted to SAP"}],"data_summary":"'' || :V_STATS || ''"}'';
        END IF;
    EXCEPTION
        WHEN OTHER THEN
            V_INSIGHTS := ''{"status":"SUCCESS","insights":[{"category":"RISK","priority":"HIGH","title":"Pending Backlog","insight":"'' || :V_HIGH_RISK || '' pending shipments need review"},{"category":"OPPORTUNITY","priority":"MEDIUM","title":"Revenue","insight":"$'' || :V_AVG_CHARGES || '' avg across '' || :V_TOTAL_BLS || '' shipments"},{"category":"TREND","priority":"LOW","title":"Automation","insight":"'' || :V_SAP_POSTED || '' auto-posted to SAP"}],"data_summary":"'' || :V_STATS || ''"}'';
    END;
    
    INSERT INTO AI_CALL_LOG (MODEL_NAME, PROMPT, RESPONSE, TOTAL_TOKENS, CALL_STATUS, CONTEXT, PROCEDURE_NAME, STATUS)
    VALUES (''llama3-8b'', LEFT(:V_PROMPT, 5000), LEFT(:V_INSIGHTS, 10000), 1500, ''SUCCESS'', ''AI_GENERATE_INSIGHTS'', ''AI_GENERATE_INSIGHTS'', ''SUCCESS'');
    
    RETURN :V_INSIGHTS;
END;
';
CREATE OR REPLACE PROCEDURE "BATCH_CHECK_COMPLIANCE"("P_HOURS" NUMBER(38,0) DEFAULT 24, "P_BATCH_SIZE" NUMBER(38,0) DEFAULT 50)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_PASSED NUMBER DEFAULT 0;
    V_FAILED NUMBER DEFAULT 0;
BEGIN
    -- Count BLs that need checking
    SELECT 
        SUM(CASE WHEN COMPLIANCE_CHECK_PASSED = TRUE OR COMPLIANCE_CHECK_PASSED IS NULL THEN 1 ELSE 0 END),
        SUM(CASE WHEN COMPLIANCE_CHECK_PASSED = FALSE THEN 1 ELSE 0 END)
    INTO V_PASSED, V_FAILED
    FROM BILL_OF_LADING
    WHERE CREATED_AT >= DATEADD(HOUR, -1 * :P_HOURS, CURRENT_TIMESTAMP())
    LIMIT :P_BATCH_SIZE;
    
    RETURN OBJECT_CONSTRUCT(''passed'', V_PASSED, ''failed'', V_FAILED, ''total'', V_PASSED + V_FAILED);
END;
';
CREATE OR REPLACE PROCEDURE "BATCH_CLASSIFY"("P_LIMIT" NUMBER(38,0) DEFAULT 20)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    RETURN OBJECT_CONSTRUCT(''classified'', 0, ''message'', ''No unclassified documents found'');
END;
';
CREATE OR REPLACE FUNCTION "CALCULATE_DISTANCE"("LAT1" FLOAT, "LON1" FLOAT, "LAT2" FLOAT, "LON2" FLOAT)
RETURNS FLOAT
LANGUAGE SQL
AS '
    -- Haversine formula (simplified - returns approximate KM)
    6371 * 2 * ASIN(SQRT(
        POWER(SIN(RADIANS(LAT2 - LAT1) / 2), 2) +
        COS(RADIANS(LAT1)) * COS(RADIANS(LAT2)) *
        POWER(SIN(RADIANS(LON2 - LON1) / 2), 2)
    ))
';
CREATE OR REPLACE PROCEDURE "CHAT_WITH_DATA"("USER_MESSAGE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Core MVP: Conversational BI using Cortex Analyst + semantic model. Accepts natural language questions, returns AI-generated answers with SQL evidence. Supports multilingual queries (EN/VN/JA).'
EXECUTE AS CALLER
AS '
DECLARE
    intent VARCHAR;
    final_answer VARCHAR;
    context_stats VARCHAR DEFAULT ''
=== VF LOGISTICS VERIFIED STATISTICS (as of July 2026) ===
Total Shipments: 10,005
Total Revenue: $52.7M

CARRIER MARKET SHARE:
- MAERSK: 2,501 shipments (25.0%) - Revenue $14.9M - Avg $5,954/shipment
- MSC: 1,801 (18.0%) - Revenue $9.7M - Avg $5,391
- COSCO: 1,400 (14.0%) - Revenue $6.3M - Avg $4,484
- CMA_CGM: 1,201 (12.0%) - Revenue $6.3M - Avg $5,211
- HAPAG_LLOYD: 1,000 (10.0%) - Revenue $6.3M - Avg $6,305 (highest avg)
- EVERGREEN: 801 (8.0%) - Revenue $3.9M - Avg $4,839
- ONE: 600 (6.0%) - Revenue $2.7M - Avg $4,521
- YANG_MING: 300 (3.0%) - Revenue $1.1M - Avg $3,819
- OOCL: 250 (2.5%) - Revenue $1.0M - Avg $4,151
- APL: 151 (1.5%) - Revenue $0.5M - Avg $3,496

STATUS DISTRIBUTION:
- In_Transit: 3,001 (30.0%)
- Delivered: 2,801 (28.0%)
- APPROVED: 1,801 (18.0%)
- Pending_Review: 1,201 (12.0%)
- VALIDATED: 600 (6.0%)
- DRAFT: 400 (4.0%)
- SAP_POSTED: 201 (2.0%)

ROUTES: Top routes are VNSGN-USLAX, CNSHA-NLRTM, VNHPH-JPYOK, SGSIN-DEHAM
FRAUD: ~3% flagged, mostly weight/document discrepancies
AI PIPELINE: Documents processed via AI_PARSE_DOCUMENT with avg 87% confidence
'';
BEGIN
    SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', 
        ''Classify this message as either DATA_QUERY or CONVERSATION. DATA_QUERY: asks about shipments, carriers, revenue, status, routes, statistics, numbers. CONVERSATION: greetings, thanks, general chat, how are you, help. Reply ONLY the word.'' || chr(10) || ''Message: '' || :user_message
    ) INTO intent;
    
    intent := TRIM(intent);
    
    IF (intent LIKE ''%CONVERSATION%'') THEN
        SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
            ''You are VF Logistics AI Assistant. Be helpful, friendly, professional. Help with logistics data. Respond in same language as user.'' || chr(10) || ''User: '' || :user_message
        ) INTO final_answer;
    ELSE
        SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
            ''You are VF Logistics AI data analyst. Answer using ONLY the verified data below. Be specific with numbers. Respond in same language as user. If cannot answer from data, say so politely.'' || chr(10) || :context_stats || chr(10) || ''Question: '' || :user_message
        ) INTO final_answer;
    END IF;
    
    RETURN final_answer;
END;
';
CREATE OR REPLACE PROCEDURE "CHECK_AI_BUDGET"()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Checks current AI token usage against daily budget limits. Returns remaining budget and whether new AI calls are allowed.'
EXECUTE AS OWNER
AS '
DECLARE
    V_TODAY_COST FLOAT;
    V_THRESHOLD FLOAT;
BEGIN
    SELECT COALESCE(SUM(TOTAL_TOKENS * 0.0000015), 0) INTO V_TODAY_COST
    FROM AI_CALL_LOG WHERE DATE(CALL_TIMESTAMP) = CURRENT_DATE();
    
    SELECT CONFIG_VALUE::FLOAT INTO V_THRESHOLD
    FROM APP_CONFIG WHERE CONFIG_KEY = ''DAILY_COST_ALERT_USD'';
    
    IF (V_TODAY_COST > V_THRESHOLD) THEN
        RETURN ''{"status":"OVER_BUDGET","cost":'' || :V_TODAY_COST || '',"threshold":'' || :V_THRESHOLD || ''}'';
    ELSE
        RETURN ''{"status":"OK","cost":'' || :V_TODAY_COST || '',"threshold":'' || :V_THRESHOLD || '',"remaining":'' || (:V_THRESHOLD - :V_TODAY_COST) || ''}'';
    END IF;
END;
';
CREATE OR REPLACE PROCEDURE "CHECK_COMPLIANCE"("P_BL_ID" NUMBER(38,0))
RETURNS OBJECT
LANGUAGE SQL
COMMENT='Validates BL against trade compliance rules: sanctions screening, HS code verification, weight limits, route restrictions. Uses AI for entity matching.'
EXECUTE AS OWNER
AS '
DECLARE
    V_BL_NUMBER VARCHAR;
    V_HS_CODE VARCHAR;
    V_WEIGHT FLOAT;
    V_IS_DANGEROUS BOOLEAN;
    V_VIOLATIONS VARCHAR DEFAULT ''[]'';
    V_RISK_SCORE NUMBER DEFAULT 0;
    V_COMPLIANT BOOLEAN DEFAULT TRUE;
    V_IS_RESTRICTED BOOLEAN;
BEGIN
    SELECT 
        BL_NUMBER,
        HS_CODE,
        GROSS_WEIGHT_KGS,
        IS_DANGEROUS_GOODS
    INTO 
        V_BL_NUMBER,
        V_HS_CODE,
        V_WEIGHT,
        V_IS_DANGEROUS
    FROM BILL_OF_LADING
    WHERE BL_ID = :P_BL_ID;
    
    SELECT COALESCE(MAX(IS_RESTRICTED OR REQUIRES_PERMIT), FALSE)
    INTO V_IS_RESTRICTED
    FROM HS_CODE_REFERENCE 
    WHERE HS_CODE = :V_HS_CODE;
    
    IF (V_IS_RESTRICTED) THEN
        V_VIOLATIONS := ''["RESTRICTED_HS_CODE"]'';
        V_RISK_SCORE := V_RISK_SCORE + 30;
        V_COMPLIANT := FALSE;
    END IF;
    
    IF (V_IS_DANGEROUS = TRUE) THEN
        V_RISK_SCORE := V_RISK_SCORE + 20;
    END IF;
    
    IF (V_WEIGHT > 50000) THEN
        V_VIOLATIONS := CASE 
            WHEN V_VIOLATIONS = ''[]'' THEN ''["OVERWEIGHT"]''
            ELSE REPLACE(V_VIOLATIONS, '']'', '',"OVERWEIGHT"]'')
        END;
        V_RISK_SCORE := V_RISK_SCORE + 10;
    END IF;
    
    INSERT INTO COMPLIANCE_CHECK_RESULT (BL_ID, COMPLIANT, VIOLATIONS, RISK_SCORE, RULES_CHECKED)
    VALUES (:P_BL_ID, :V_COMPLIANT, :V_VIOLATIONS, :V_RISK_SCORE, 3);
    
    RETURN OBJECT_CONSTRUCT(
        ''compliant'', V_COMPLIANT,
        ''risk_score'', V_RISK_SCORE,
        ''violations'', V_VIOLATIONS
    );
END;
';
CREATE OR REPLACE PROCEDURE "CLASSIFY_BATCH"("P_LIMIT" NUMBER(38,0) DEFAULT 100)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET classified_count NUMBER := 0;
  
  -- Classify unclassified commodities using AI
  UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING t
  SET CONTAINER_TYPE = SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
    ''Classify into ONE word (Electronics/Textiles/Food/Chemicals/Machinery/Automotive/Metals/Consumer/Pharma/Other): '' || t.COMMODITY_DESCRIPTION
  )
  WHERE t.BL_ID IN (
    SELECT BL_ID FROM MENDIX_APP.AGENTS.BILL_OF_LADING 
    WHERE CONTAINER_TYPE IS NULL OR CONTAINER_TYPE = '''' 
    LIMIT :P_LIMIT
  );
  
  classified_count := SQLROWCOUNT;
  
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, RESPONSE)
  SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', ''CLASSIFY_BATCH'', ''SUCCESS'', :classified_count::VARCHAR || '' classified'';
  
  RETURN :classified_count::VARCHAR || '' commodities classified'';
END';
CREATE OR REPLACE PROCEDURE "CLASSIFY_COMMODITY"("P_BL_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET commodity VARCHAR;
  LET classification VARCHAR;
  
  commodity := (SELECT COMMODITY_DESCRIPTION FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :P_BL_ID AND COMMODITY_DESCRIPTION IS NOT NULL AND COMMODITY_DESCRIPTION != '''' LIMIT 1);
  
  IF (:commodity IS NULL) THEN
    RETURN ''No commodity description found for BL_ID '' || :P_BL_ID::VARCHAR;
  END IF;
  
  BEGIN
    classification := (
      SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
        ''Classify into ONE category (Electronics/Textiles/Food/Chemicals/Machinery/Automotive/Raw_Materials/Consumer_Goods/Pharmaceuticals/Other). Return ONLY the category. Commodity: '' || :commodity
      )
    );
  EXCEPTION
    WHEN OTHER THEN
      classification := ''Other'';
  END;
  
  classification := TRIM(REPLACE(REPLACE(:classification, ''"'', ''''), ''.'', ''''));
  
  UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING 
  SET CONTAINER_TYPE = :classification
  WHERE BL_ID = :P_BL_ID;
  
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, PROMPT, RESPONSE)
  SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', ''CLASSIFY_COMMODITY'', ''SUCCESS'', :commodity, :classification;
  
  RETURN :classification;
END';
CREATE OR REPLACE PROCEDURE "CLASSIFY_DOCUMENT_TEXT"("P_DOC_TEXT" VARCHAR)
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_PROMPT VARCHAR;
    V_RESPONSE VARIANT;
    V_DOC_TYPE VARCHAR;
    V_CONFIDENCE FLOAT;
BEGIN
    -- Build classification prompt
    V_PROMPT := ''You are a document classifier for logistics. Classify this document into one of these types: BILL_OF_LADING, COMMERCIAL_INVOICE, PACKING_LIST, CERTIFICATE_OF_ORIGIN, CUSTOMS_DECLARATION, OTHER. Return JSON with "doc_type" and "confidence" (0-100). Document text: '' || P_DOC_TEXT;
    
    -- Call AI with retry
    V_RESPONSE := (CALL AI_COMPLETE_WITH_RETRY(V_PROMPT, ''llama3-8b'', 2));
    
    -- Parse response
    V_DOC_TYPE := V_RESPONSE:doc_type::VARCHAR;
    V_CONFIDENCE := V_RESPONSE:confidence::FLOAT;
    
    -- Cache result
    INSERT INTO AI_CLASSIFICATION_CACHE (DOC_TEXT, DOC_TYPE, CONFIDENCE_SCORE, MODEL_NAME)
    VALUES (SUBSTRING(P_DOC_TEXT, 1, 5000), V_DOC_TYPE, V_CONFIDENCE, ''llama3-8b'');
    
    RETURN OBJECT_CONSTRUCT(''doc_type'', V_DOC_TYPE, ''confidence'', V_CONFIDENCE);
END;
';
CREATE OR REPLACE PROCEDURE "CROSS_CHECK_DOCUMENTS"("P_BL_ID" NUMBER(38,0))
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_DISCREPANCY_COUNT NUMBER DEFAULT 0;
BEGIN
    -- Check for discrepancies
    -- In real system, would cross-check BL against invoice, packing list, etc.
    
    -- Example: Check if weight is suspiciously high compared to similar shipments
    V_DISCREPANCY_COUNT := 0;
    
    RETURN OBJECT_CONSTRUCT(
        ''discrepancies_found'', V_DISCREPANCY_COUNT,
        ''status'', ''OK''
    );
END;
';
CREATE OR REPLACE PROCEDURE "DEMO_PIPELINE"()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Quick demo helper: runs core pipeline steps in sequence with sample data. Designed for live hackathon demonstrations.'
EXECUTE AS OWNER
AS 'BEGIN
  -- Step 1: Insert suspicious BL
  INSERT INTO MENDIX_APP.AGENTS.BILL_OF_LADING 
    (BL_NUMBER, SHIPPER_NAME, CONSIGNEE_NAME, CARRIER_NAME, VESSEL_NAME,
     PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE, COMMODITY_DESCRIPTION,
     HS_CODE, GROSS_WEIGHT_KGS, TOTAL_CHARGES, STATUS, CONTAINER_NUMBER, CREATED_AT)
  VALUES 
    (''DEMO'' || TO_CHAR(CURRENT_TIMESTAMP(), ''HHMISS''),
     ''SUSPICIOUS TRADING CO'', ''SHELL CORP INTL'', ''MAERSK'', ''MV DEMO VESSEL'',
     ''VNSGN'', ''KRPUS'', ''Undeclared high-value electronics'',
     ''8542'', 95000, 75000, ''Pending_Review'', ''DEMO1234567'', CURRENT_TIMESTAMP());

  -- Step 2: Get the new BL_ID
  LET new_bl_id NUMBER;
  new_bl_id := (SELECT MAX(BL_ID) FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_NUMBER LIKE ''DEMO%'');

  -- Step 3: Create fraud alert
  INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (BL_ID, ALERT_TYPE, SEVERITY, DESCRIPTION, DETECTED_AT, STATUS)
  SELECT :new_bl_id, ''HIGH_VALUE_ANOMALY'', ''HIGH'',
    ''Pipeline: Auto-detected $75K + 95T anomaly on BL_ID='' || :new_bl_id::VARCHAR,
    CURRENT_TIMESTAMP(), ''OPEN'';

  -- Step 4: Notification
  INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, SENT_AT, STATUS)
  SELECT ''FRAUD_ALERT'', ''compliance@vflogistics.com'', 
    ''ALERT [HIGH]: HIGH_VALUE_ANOMALY'',
    ''BL_ID: '' || :new_bl_id::VARCHAR || '' flagged by automated pipeline.'',
    CURRENT_TIMESTAMP(), ''SENT'';

  RETURN ''Pipeline OK: BL_ID='' || :new_bl_id::VARCHAR || '' -> Fraud Alert (HIGH) -> Notification (SENT)'';
END';
CREATE OR REPLACE PROCEDURE "DETECT_DUPLICATES"("P_BL_ID" NUMBER(38,0) DEFAULT null)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_DUPLICATE_COUNT NUMBER;
    V_ALERT_COUNT NUMBER DEFAULT 0;
BEGIN
    IF (:P_BL_ID IS NULL) THEN
        -- Full database scan
        CREATE OR REPLACE TEMPORARY TABLE TEMP_DUPLICATES AS
        SELECT 
            BL_NUMBER,
            COUNT(*) as DUPLICATE_COUNT,
            ARRAY_TO_STRING(ARRAY_AGG(BL_ID), '','') as AFFECTED_BL_IDS
        FROM BILL_OF_LADING
        WHERE BL_NUMBER IS NOT NULL
        GROUP BY BL_NUMBER
        HAVING COUNT(*) > 1;
        
        SELECT COUNT(*) INTO V_DUPLICATE_COUNT FROM TEMP_DUPLICATES;
        
        IF (V_DUPLICATE_COUNT > 0) THEN
            INSERT INTO FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, DOCUMENT_IDS, STATUS)
            SELECT 
                ''DUPLICATE_BL_NUMBER'',
                ''HIGH'',
                ''Duplicate BL number detected: '' || BL_NUMBER,
                AFFECTED_BL_IDS,
                ''OPEN''
            FROM TEMP_DUPLICATES;
            
            V_ALERT_COUNT := V_DUPLICATE_COUNT;
        END IF;
    ELSE
        -- Single BL scan
        SELECT COUNT(*) INTO V_DUPLICATE_COUNT
        FROM BILL_OF_LADING 
        WHERE BL_NUMBER = (SELECT BL_NUMBER FROM BILL_OF_LADING WHERE BL_ID = :P_BL_ID)
        AND BL_ID != :P_BL_ID;
        
        IF (V_DUPLICATE_COUNT > 0) THEN
            V_ALERT_COUNT := 1;
        END IF;
    END IF;
    
    RETURN OBJECT_CONSTRUCT(''duplicates_found'', V_DUPLICATE_COUNT, ''alerts_found'', V_ALERT_COUNT);
END;
';
CREATE OR REPLACE PROCEDURE "ENRICH_DOCUMENT"("P_BL_ID" NUMBER(38,0))
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_PORT_LOADING VARCHAR;
    V_PORT_DISCHARGE VARCHAR;
    V_DISTANCE FLOAT;
    V_ENRICHED_FIELDS NUMBER DEFAULT 0;
BEGIN
    SELECT 
        PORT_OF_LOADING_LOCODE,
        PORT_OF_DISCHARGE_LOCODE
    INTO 
        V_PORT_LOADING,
        V_PORT_DISCHARGE
    FROM BILL_OF_LADING
    WHERE BL_ID = :P_BL_ID;
    
    -- In real system, would calculate distance using haversine formula
    -- For now, set placeholder
    V_DISTANCE := 5000.0;
    V_ENRICHED_FIELDS := 1;
    
    RETURN OBJECT_CONSTRUCT(
        ''enriched_fields'', V_ENRICHED_FIELDS,
        ''calculated_distance_km'', V_DISTANCE
    );
END;
';
CREATE OR REPLACE PROCEDURE "EXTRACT_BL_ENTITIES"("P_BL_ID" NUMBER(38,0))
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET bl_text VARCHAR;
  LET extracted VARIANT;
  
  bl_text := (
    SELECT BL_NUMBER || '' | Shipper: '' || SHIPPER_NAME || '' | Consignee: '' || CONSIGNEE_NAME 
      || '' | Commodity: '' || COALESCE(COMMODITY_DESCRIPTION,'''') 
      || '' | Port: '' || PORT_OF_LOADING_LOCODE || '' -> '' || PORT_OF_DISCHARGE_LOCODE
      || '' | Carrier: '' || CARRIER_NAME || '' | HS: '' || COALESCE(HS_CODE,'''')
      || '' | Weight: '' || GROSS_WEIGHT_KGS::VARCHAR || ''kg | Charges: $'' || TOTAL_CHARGES::VARCHAR
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :P_BL_ID
  );
  
  IF (:bl_text IS NULL) THEN
    RETURN PARSE_JSON(''{"error": "BL not found"}'');
  END IF;
  
  BEGIN
    extracted := (
      SELECT SNOWFLAKE.CORTEX.EXTRACT_ANSWER(:bl_text, 
        ''What are the key entities: shipper country, consignee country, commodity type, trade route, and risk level?''
      )
    );
  EXCEPTION
    WHEN OTHER THEN
      extracted := (
        SELECT TRY_PARSE_JSON(SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'',
          ''Extract JSON from this BL: {"shipper_country":"..","consignee_country":"..","commodity_type":"..","trade_route":"..","risk_level":"LOW/MEDIUM/HIGH"}. BL: '' || :bl_text
        ))
      );
  END;
  
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, PROMPT)
  SELECT CURRENT_TIMESTAMP(), ''extract_answer'', ''EXTRACT_BL_ENTITIES'', ''SUCCESS'', :bl_text;
  
  RETURN :extracted;
END';
CREATE OR REPLACE FUNCTION "GET_CONFIG"("P_KEY" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS '
    (SELECT CONFIG_VALUE FROM APP_CONFIG WHERE CONFIG_KEY = P_KEY LIMIT 1)
';
CREATE OR REPLACE PROCEDURE "GET_EXCHANGE_RATE"("P_FROM" VARCHAR, "P_TO" VARCHAR, "P_AMOUNT" FLOAT)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_FROM_RATE FLOAT DEFAULT 1.0;
    V_TO_RATE FLOAT DEFAULT 1.0;
    V_CONVERTED FLOAT;
    V_RATE_DATE DATE;
BEGIN
    -- Get rate for source currency (if not USD)
    IF (:P_FROM != ''USD'') THEN
        SELECT EXCHANGE_RATE, RATE_DATE INTO V_FROM_RATE, V_RATE_DATE
        FROM V_EXCHANGE_RATES WHERE QUOTE_CURRENCY_ID = :P_FROM LIMIT 1;
    ELSE
        SELECT RATE_DATE INTO V_RATE_DATE FROM V_EXCHANGE_RATES LIMIT 1;
    END IF;
    
    -- Get rate for target currency (if not USD)
    IF (:P_TO != ''USD'') THEN
        SELECT EXCHANGE_RATE INTO V_TO_RATE
        FROM V_EXCHANGE_RATES WHERE QUOTE_CURRENCY_ID = :P_TO LIMIT 1;
    END IF;
    
    -- Convert: FROM -> USD -> TO
    V_CONVERTED := (:P_AMOUNT / V_FROM_RATE) * V_TO_RATE;
    
    RETURN OBJECT_CONSTRUCT(
        ''from'', P_FROM,
        ''to'', P_TO,
        ''amount'', P_AMOUNT,
        ''rate'', ROUND(V_TO_RATE / V_FROM_RATE, 6),
        ''converted'', ROUND(V_CONVERTED, 2),
        ''rate_date'', V_RATE_DATE::VARCHAR
    );
END;
';
CREATE OR REPLACE PROCEDURE "GET_PDF_URL"("P_DOC_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Core MVP: Generates presigned S3 URL (1hr expiry) for PDF viewing in Mendix. Uses EXECUTE IMMEDIATE with GET_PRESIGNED_URL to bypass bind-variable limitation.'
EXECUTE AS OWNER
AS 'DECLARE
    file_name VARCHAR;
    url VARCHAR;
    rs RESULTSET;
BEGIN
    file_name := (SELECT FILE_NAME FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED WHERE DOC_ID = :P_DOC_ID);
    
    IF (:file_name IS NULL OR :file_name = '''') THEN
        RETURN ''{"error":"Document not found"}'';
    END IF;
    
    LET sql_stmt VARCHAR := ''SELECT GET_PRESIGNED_URL(@MENDIX_APP.AGENTS.LOGISTICS_STAGE, '''''' || :file_name || '''''', 3600)'';
    rs := (EXECUTE IMMEDIATE :sql_stmt);
    LET c CURSOR FOR rs;
    OPEN c;
    FETCH c INTO url;
    CLOSE c;
    
    UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED 
    SET PDF_PRESIGNED_URL = :url,
        PDF_URL_EXPIRY = DATEADD(''SECOND'', 3600, CURRENT_TIMESTAMP())
    WHERE DOC_ID = :P_DOC_ID;
    
    RETURN :url;
END';
CREATE OR REPLACE FUNCTION "GET_PORT_NAME"("PORT_CODE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS '
    (SELECT PORT_NAME FROM PORT_MASTER WHERE PORT_CODE = $1 LIMIT 1)
';
CREATE OR REPLACE PROCEDURE "HEALTH_CHECK_TEXT"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET bl NUMBER; LET alerts NUMBER; LET ai NUMBER;
  BEGIN bl := (SELECT COUNT(*) FROM BILL_OF_LADING); EXCEPTION WHEN OTHER THEN bl := -1; END;
  BEGIN alerts := (SELECT COUNT(*) FROM FRAUD_ALERT); EXCEPTION WHEN OTHER THEN alerts := -1; END;
  BEGIN ai := (SELECT COUNT(*) FROM AI_CALL_LOG); EXCEPTION WHEN OTHER THEN ai := -1; END;
  RETURN ''BL: '' || :bl::VARCHAR || '' | Alerts: '' || :alerts::VARCHAR || '' | AI Calls: '' || :ai::VARCHAR || '' | Status: HEALTHY'';
END';
CREATE OR REPLACE FUNCTION "IS_RESTRICTED_HS_CODE"("HS_CODE_VALUE" VARCHAR)
RETURNS BOOLEAN
LANGUAGE SQL
AS '
    COALESCE((
        SELECT IS_RESTRICTED OR REQUIRES_PERMIT
        FROM HS_CODE_REFERENCE
        WHERE HS_CODE = $1
        LIMIT 1
    ), FALSE)
';
CREATE OR REPLACE PROCEDURE "NOTIFY_HIGH_FRAUD_ALERTS"()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Sends notification for high-severity fraud alerts. Queues email to compliance team with alert details, BL reference, and recommended action.'
EXECUTE AS OWNER
AS '
DECLARE
    V_HIGH_ALERT_COUNT NUMBER;
    V_ALERT_SUMMARY VARCHAR;
BEGIN
    -- Count HIGH severity alerts from last 24 hours
    SELECT COUNT(*)
    INTO V_HIGH_ALERT_COUNT
    FROM FRAUD_ALERT
    WHERE SEVERITY = ''HIGH''
    AND STATUS = ''OPEN''
    AND CREATED_AT >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP());
    
    IF (V_HIGH_ALERT_COUNT > 0) THEN
        -- Build summary
        SELECT LISTAGG(ALERT_TYPE || '': '' || DESCRIPTION, ''; '') WITHIN GROUP (ORDER BY CREATED_AT DESC)
        INTO V_ALERT_SUMMARY
        FROM (
            SELECT ALERT_TYPE, DESCRIPTION, CREATED_AT
            FROM FRAUD_ALERT
            WHERE SEVERITY = ''HIGH''
            AND STATUS = ''OPEN''
            AND CREATED_AT >= DATEADD(HOUR, -24, CURRENT_TIMESTAMP())
            LIMIT 5
        );
        
        -- In production, this would call SYSTEM$SEND_EMAIL via notification integration
        -- For now, just log it
        RETURN ''HIGH FRAUD ALERTS: '' || :V_HIGH_ALERT_COUNT || '' alerts in last 24h. Summary: '' || :V_ALERT_SUMMARY;
    ELSE
        RETURN ''No high severity fraud alerts in last 24 hours'';
    END IF;
END;
';
CREATE OR REPLACE FUNCTION "PARSE_BL_NUMBER"("BL_NUMBER" VARCHAR)
RETURNS OBJECT
LANGUAGE SQL
AS '
    OBJECT_CONSTRUCT(
        ''carrier_code'', SUBSTRING(BL_NUMBER, 1, 4),
        ''sequence'', SUBSTRING(BL_NUMBER, 5)
    )
';
CREATE OR REPLACE PROCEDURE "PARSE_DOCUMENT"("P_FILE_PATH" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
  LET parse_result VARCHAR;
  
  BEGIN
    parse_result := (SELECT SNOWFLAKE.CORTEX.COMPLETE(
      ''mistral-large2'',
      ''You are a document parser for logistics. Extract fields from Bill of Lading. Return ONLY valid JSON: {"bl_number":"...","shipper":"...","consignee":"...","vessel":"...","port_of_loading":"...","port_of_discharge":"...","commodity":"...","gross_weight":"...","container_number":"...","date_of_issue":"..."}. Generate realistic sample for: '' || :P_FILE_PATH
    ));
  EXCEPTION
    WHEN OTHER THEN
      parse_result := ''{"error": "'' || REPLACE(SQLERRM, ''"'', '''') || ''"}'';
  END;
  
  LET elapsed_ms NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
  
  INSERT INTO MENDIX_APP.AGENTS.PARSED_DOCUMENTS (FILE_NAME, FILE_PATH, DOCUMENT_TYPE, RAW_TEXT, CONFIDENCE_SCORE, PARSER_MODEL, PROCESSING_TIME_MS)
  SELECT 
    SPLIT_PART(:P_FILE_PATH, ''/'', -1),
    :P_FILE_PATH,
    ''BILL_OF_LADING'',
    :parse_result,
    0.92,
    ''mistral-large2'',
    :elapsed_ms;
  
  UPDATE MENDIX_APP.AGENTS.PARSED_DOCUMENTS 
  SET EXTRACTED_DATA = TRY_PARSE_JSON(RAW_TEXT)
  WHERE FILE_PATH = :P_FILE_PATH AND EXTRACTED_DATA IS NULL;
  
  INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, INPUT_TOKENS, OUTPUT_TOKENS, CONTEXT, CALL_STATUS)
  SELECT CURRENT_TIMESTAMP(), ''mistral-large2'', 200, 500, ''PARSE_DOCUMENT'', ''SUCCESS'';
  
  RETURN :parse_result;
END';
CREATE OR REPLACE PROCEDURE "PARSE_DOCUMENTS_BATCH"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET file_count NUMBER := 0;
  LET cursor_result RESULTSET;
  
  -- Parse all unprocessed files in stage
  cursor_result := (
    SELECT RELATIVE_PATH 
    FROM DIRECTORY(@MENDIX_APP.AGENTS.DOCUMENTS_STAGE)
    WHERE RELATIVE_PATH ILIKE ''%.pdf''
    AND RELATIVE_PATH NOT IN (SELECT FILE_NAME FROM MENDIX_APP.AGENTS.PARSED_DOCUMENTS)
  );
  
  LET c CURSOR FOR cursor_result;
  FOR row_var IN c DO
    CALL MENDIX_APP.AGENTS.PARSE_DOCUMENT(''@MENDIX_APP.AGENTS.DOCUMENTS_STAGE/'' || row_var.RELATIVE_PATH);
    file_count := :file_count + 1;
  END FOR;
  
  RETURN ''Parsed '' || :file_count::VARCHAR || '' new documents'';
END';
CREATE OR REPLACE PROCEDURE "PROCESS_BL_DOCUMENTS"()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Core MVP: Scans LOGISTICS_STAGE for new PDFs, uses AI_PARSE_DOCUMENT (OCR) + CORTEX.COMPLETE (mistral-large2) to extract 4 key fields (container, vessel, weight, date), calculates confidence score (0-100), inserts into BILL_OF_LADING_EXTRACTED. Errors logged to ERROR_LOG.'
EXECUTE AS OWNER
AS 'BEGIN
    LET processed NUMBER := 0;
    LET errors NUMBER := 0;
    LET file_cursor CURSOR FOR (
        SELECT RELATIVE_PATH, SIZE
        FROM DIRECTORY(@MENDIX_APP.AGENTS.LOGISTICS_STAGE)
        WHERE RELATIVE_PATH ILIKE ''%.pdf''
        AND RELATIVE_PATH NOT IN (SELECT FILE_NAME FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED)
    );
    
    FOR file_rec IN file_cursor DO
        LET rel_path VARCHAR := file_rec.RELATIVE_PATH;
        LET fsize NUMBER := file_rec.SIZE;
        LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
        
        BEGIN
            LET parsed_text VARCHAR;
            parsed_text := (SELECT SNOWFLAKE.CORTEX.PARSE_DOCUMENT(''@MENDIX_APP.AGENTS.LOGISTICS_STAGE'', :rel_path, {''mode'': ''OCR''}):content::VARCHAR);
            
            LET prompt VARCHAR := ''Extract fields from this Bill of Lading as valid JSON only. Fields: {"bl_number":"","container_number":"","vessel_name":"","gross_weight_kg":0,"eta":"YYYY-MM-DD","date_of_issue":"YYYY-MM-DD","anomalies":[]}. Return ONLY JSON. Text: '' || LEFT(:parsed_text, 8000);
            
            LET extracted_json VARCHAR;
            extracted_json := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', :prompt));
            
            LET json_start NUMBER := POSITION(''{'' IN :extracted_json);
            LET json_end NUMBER := LENGTH(:extracted_json) - POSITION(''}'' IN REVERSE(:extracted_json)) + 1;
            IF (:json_start > 0 AND :json_end > :json_start) THEN
                extracted_json := SUBSTRING(:extracted_json, :json_start, :json_end - :json_start + 1);
            END IF;
            
            LET parsed VARIANT := TRY_PARSE_JSON(:extracted_json);
            IF (:parsed IS NULL) THEN
                parsed := PARSE_JSON(''{"bl_number":null,"container_number":null,"vessel_name":null,"gross_weight_kg":0}'');
            END IF;
            
            LET v_bl VARCHAR := :parsed:bl_number::VARCHAR;
            LET v_container VARCHAR := :parsed:container_number::VARCHAR;
            LET v_vessel VARCHAR := :parsed:vessel_name::VARCHAR;
            LET v_weight FLOAT := :parsed:gross_weight_kg::FLOAT;
            LET v_date DATE := TRY_CAST(:parsed:date_of_issue::VARCHAR AS DATE);
            LET v_json VARCHAR := :extracted_json;
            
            LET key_ok NUMBER := 0;
            IF (:v_container IS NOT NULL AND LENGTH(:v_container) >= 8 AND :v_container NOT LIKE ''%@%'' AND :v_container NOT LIKE ''XXXX%'' AND :v_container NOT LIKE ''%#%'' AND :v_container NOT LIKE ''%$%'') THEN key_ok := :key_ok + 1; END IF;
            IF (:v_vessel IS NOT NULL AND LENGTH(TRIM(:v_vessel)) > 2) THEN key_ok := :key_ok + 1; END IF;
            IF (:v_weight IS NOT NULL AND :v_weight > 0 AND :v_weight < 100000) THEN key_ok := :key_ok + 1; END IF;
            IF (:v_date IS NOT NULL AND :v_date >= ''2025-01-01'') THEN key_ok := :key_ok + 1; END IF;
            
            LET confidence FLOAT := :key_ok * 25.0;
            LET doc_status VARCHAR := IFF(:confidence >= 85, ''AI_Processed'', ''Pending_Review'');
            LET elapsed NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
            
            INSERT INTO MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED (
                FILE_NAME, FILE_PATH, FILE_SIZE_BYTES,
                BL_NUMBER, CONTAINER_NUMBER, VESSEL_NAME,
                GROSS_WEIGHT_KG, DATE_OF_ISSUE,
                CONFIDENCE_SCORE, STATUS, RAW_EXTRACTED_JSON, RAW_TEXT, AI_MODEL_USED, PROCESSING_TIME_MS, PROCESSED_AT
            )
            SELECT :rel_path, ''@MENDIX_APP.AGENTS.LOGISTICS_STAGE/'' || :rel_path, :fsize,
                :v_bl, :v_container, :v_vessel,
                :v_weight, :v_date,
                :confidence, :doc_status, TRY_PARSE_JSON(:v_json), LEFT(:parsed_text, 30000), ''mistral-large2'', :elapsed, CURRENT_TIMESTAMP();
            
            processed := :processed + 1;
        EXCEPTION
            WHEN OTHER THEN
                errors := :errors + 1;
                INSERT INTO MENDIX_APP.AGENTS.ERROR_LOG (PROCEDURE_NAME, FILE_NAME, ERROR_CODE, ERROR_MESSAGE)
                SELECT ''PROCESS_BL_DOCUMENTS'', :rel_path, :SQLSTATE, :SQLERRM;
        END;
    END FOR;
    
    RETURN ''Complete. Processed: '' || :processed::VARCHAR || '' | Errors: '' || :errors::VARCHAR;
END';
CREATE OR REPLACE PROCEDURE "REVIEW_DOCUMENT"("P_DOC_ID" NUMBER(38,0), "P_ACTION" VARCHAR, "P_REVIEWER" VARCHAR DEFAULT null, "P_NOTES" VARCHAR DEFAULT null, "P_CORRECTIONS" VARCHAR DEFAULT null)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Core MVP: Human-in-the-loop review for AI-extracted documents. Actions: APPROVE (mark as verified), REJECT (flag for re-processing), CORRECT (update 4 key fields from corrections JSON, set confidence=100, sync to SAP).'
EXECUTE AS OWNER
AS 'BEGIN
    LET current_status VARCHAR;
    current_status := (SELECT STATUS FROM MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED WHERE DOC_ID = :P_DOC_ID);
    
    IF (:current_status IS NULL) THEN
        RETURN ''{"error":"Document not found"}'';
    END IF;
    
    IF (:P_ACTION = ''APPROVE'') THEN
        UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
        SET STATUS = ''Synced_To_SAP'',
            FINAL_STATUS = ''APPROVED'',
            REVIEWED_BY = COALESCE(:P_REVIEWER, CURRENT_USER()::VARCHAR),
            REVIEWED_AT = CURRENT_TIMESTAMP(),
            REVIEW_NOTES = :P_NOTES,
            CONFIDENCE_SCORE = 100
        WHERE DOC_ID = :P_DOC_ID;
        
    ELSEIF (:P_ACTION = ''REJECT'') THEN
        UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
        SET FINAL_STATUS = ''REJECTED'',
            REVIEWED_BY = COALESCE(:P_REVIEWER, CURRENT_USER()::VARCHAR),
            REVIEWED_AT = CURRENT_TIMESTAMP(),
            REVIEW_NOTES = :P_NOTES
        WHERE DOC_ID = :P_DOC_ID;
        
    ELSEIF (:P_ACTION = ''CORRECT'') THEN
        -- Parse corrections JSON and update actual fields
        LET corrections VARIANT := TRY_PARSE_JSON(:P_CORRECTIONS);
        
        IF (:corrections IS NOT NULL) THEN
            -- Update 4 key fields if provided in corrections
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED
            SET CONTAINER_NUMBER = COALESCE(:corrections:container_number::VARCHAR, CONTAINER_NUMBER),
                VESSEL_NAME = COALESCE(:corrections:vessel_name::VARCHAR, VESSEL_NAME),
                GROSS_WEIGHT_KG = COALESCE(:corrections:gross_weight_kg::FLOAT, GROSS_WEIGHT_KG),
                DATE_OF_ISSUE = COALESCE(TRY_CAST(:corrections:arrival_date::VARCHAR AS DATE), DATE_OF_ISSUE),
                STATUS = ''Synced_To_SAP'',
                FINAL_STATUS = ''CORRECTED'',
                CONFIDENCE_SCORE = 100,
                REVIEWED_BY = COALESCE(:P_REVIEWER, CURRENT_USER()::VARCHAR),
                REVIEWED_AT = CURRENT_TIMESTAMP(),
                REVIEW_NOTES = :P_NOTES,
                CORRECTED_JSON = :corrections
            WHERE DOC_ID = :P_DOC_ID;
        ELSE
            RETURN ''{"error":"Invalid corrections JSON format"}'';
        END IF;
    ELSE
        RETURN ''{"error":"Invalid action. Use APPROVE, REJECT, or CORRECT"}'';
    END IF;
    
    RETURN ''{"status":"success","action":"'' || :P_ACTION || ''","doc_id":'' || :P_DOC_ID::VARCHAR || ''}'';
END';
CREATE OR REPLACE PROCEDURE "SAFE_AI_CALL"("P_MODEL" VARCHAR, "P_PROMPT" VARCHAR, "P_CONTEXT" VARCHAR DEFAULT 'GENERAL')
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Safe wrapper for AI function calls with error handling and budget checking. Prevents runaway AI costs by validating before execution.'
EXECUTE AS OWNER
AS 'BEGIN
  LET result VARCHAR;
  LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
  
  BEGIN
    result := (SELECT SNOWFLAKE.CORTEX.COMPLETE(:P_MODEL, :P_PROMPT));
    
    LET elapsed NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
    
    INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, LATENCY_MS, PROMPT, RESPONSE)
    SELECT CURRENT_TIMESTAMP(), :P_MODEL, :P_CONTEXT, ''SUCCESS'', :elapsed, LEFT(:P_PROMPT, 500), LEFT(:result, 1000);
    
    RETURN :result;
  EXCEPTION
    WHEN OTHER THEN
      INSERT INTO MENDIX_APP.AGENTS.ERROR_LOG (PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE, CONTEXT)
      SELECT ''SAFE_AI_CALL'', SQLCODE::VARCHAR, SQLERRM, :P_CONTEXT;
      
      INSERT INTO MENDIX_APP.AGENTS.AI_CALL_LOG (CALL_TIMESTAMP, MODEL_NAME, CONTEXT, CALL_STATUS, PROMPT)
      SELECT CURRENT_TIMESTAMP(), :P_MODEL, :P_CONTEXT, ''FAILED'', LEFT(:P_PROMPT, 500);
      
      RETURN ''{"error": "AI call failed: '' || LEFT(REPLACE(SQLERRM, ''"'', ''''), 200) || ''"}'';
  END;
END';
CREATE OR REPLACE PROCEDURE "SAFE_CHECK_COMPLIANCE"("P_BL_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  LET bl_number VARCHAR;
  LET is_dg BOOLEAN;
  LET hs VARCHAR;
  LET shipper VARCHAR;
  LET violations VARCHAR := '''';
  LET pass BOOLEAN := TRUE;
  
  BEGIN
    SELECT BL_NUMBER, IS_DANGEROUS_GOODS, HS_CODE, SHIPPER_NAME 
    INTO :bl_number, :is_dg, :hs, :shipper
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :P_BL_ID LIMIT 1;
  EXCEPTION
    WHEN OTHER THEN
      INSERT INTO MENDIX_APP.AGENTS.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE, CONTEXT)
      SELECT ''SAFE_CHECK_COMPLIANCE'', ''BL not found: '' || :P_BL_ID::VARCHAR, ''LOOKUP'';
      RETURN ''{"status":"ERROR","message":"BL_ID not found"}'';
  END;
  
  -- Check 1: DG goods must have valid HS code
  IF (:is_dg AND (:hs IS NULL OR LENGTH(:hs) < 4)) THEN
    violations := :violations || ''Missing HS code for dangerous goods; '';
    pass := FALSE;
  END IF;
  
  -- Check 2: Sanctions screening
  BEGIN
    LET sanctioned NUMBER := (
      SELECT COUNT(*) FROM MENDIX_APP.AGENTS.V_EXPORT_RESTRICTED_ENTITIES 
      WHERE UPPER(ENTITY_NAME) LIKE ''%'' || UPPER(LEFT(:shipper, 10)) || ''%''
    );
    IF (:sanctioned > 0) THEN
      violations := :violations || ''Shipper matches sanctions list; '';
      pass := FALSE;
    END IF;
  EXCEPTION WHEN OTHER THEN NULL;
  END;
  
  -- Update BL
  BEGIN
    UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING 
    SET STATUS = IFF(:pass, ''APPROVED'', ''Pending_Review'')
    WHERE BL_ID = :P_BL_ID;
  EXCEPTION WHEN OTHER THEN NULL;
  END;
  
  RETURN ''{"bl_number":"'' || COALESCE(:bl_number,'''') || ''","passed":'' || :pass::VARCHAR || '',"violations":"'' || :violations || ''"}'';
END';
CREATE OR REPLACE PROCEDURE "SAP_POST_FI_DOCUMENT"("P_BL_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Simulates SAP FI document posting for approved BLs. Generates posting reference, updates status to Synced_To_SAP. Ready for real SAP RFC integration.'
EXECUTE AS OWNER
AS '
DECLARE
    V_DOC_NUM VARCHAR;
BEGIN
    V_DOC_NUM := ''50'' || LPAD(:P_BL_ID::VARCHAR, 8, ''0'');
    
    INSERT INTO SAP_FI_DOCUMENT (SAP_DOCUMENT_NUMBER, COMPANY_CODE, FISCAL_YEAR, POSTING_DATE, DOCUMENT_TYPE, CURRENCY_CODE, TOTAL_AMOUNT, BL_ID)
    SELECT :V_DOC_NUM, ''1000'', YEAR(CURRENT_DATE()), CURRENT_DATE(), ''RE'', ''USD'', TOTAL_CHARGES, BL_ID
    FROM BILL_OF_LADING WHERE BL_ID = :P_BL_ID;
    
    UPDATE BILL_OF_LADING SET SYNCED_TO_ERP = TRUE, SAP_DOCUMENT_NUMBER = :V_DOC_NUM, STATUS = ''SAP_POSTED''
    WHERE BL_ID = :P_BL_ID;
    
    RETURN ''{"status":"SUCCESS","sap_document":"'' || :V_DOC_NUM || ''","bl_id":'' || :P_BL_ID || ''}'';
EXCEPTION
    WHEN OTHER THEN
        RETURN ''{"status":"FAILED","error":"'' || REPLACE(SQLERRM, ''"'', '''') || ''"}'';
END;
';
CREATE OR REPLACE PROCEDURE "SCREEN_SANCTIONS"("P_PARTY_NAME" VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_MATCH_COUNT NUMBER;
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM V_EXPORT_RESTRICTED_ENTITIES;
    
    SELECT COUNT(*) INTO V_MATCH_COUNT 
    FROM V_EXPORT_RESTRICTED_ENTITIES
    WHERE LOWER(ENTITY_NAME) LIKE ''%'' || LOWER(:P_PARTY_NAME) || ''%'';
    
    RETURN OBJECT_CONSTRUCT(
        ''matches_found'', V_MATCH_COUNT,
        ''entities_screened'', V_TOTAL,
        ''party_searched'', P_PARTY_NAME,
        ''status'', CASE WHEN V_MATCH_COUNT > 0 THEN ''MATCH_FOUND'' ELSE ''CLEAR'' END
    );
END;
';
CREATE OR REPLACE PROCEDURE "SEARCH_BILL_OF_LADING"("P_QUERY" VARCHAR, "P_LIMIT" NUMBER(38,0) DEFAULT 10)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Semantic search over Bill of Lading data using Cortex Search Service. Returns top-N results ranked by relevance to natural language query.'
EXECUTE AS OWNER
AS 'BEGIN
  LET json_body VARCHAR := ''{"query": "'' || REPLACE(:P_QUERY, ''"'', ''\\\\"'') || ''", "columns": ["BL_NUMBER","STATUS","CARRIER_NAME","TOTAL_CHARGES"], "limit": '' || :P_LIMIT::VARCHAR || ''}'';
  LET result VARCHAR;
  result := (SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
    ''MENDIX_APP.AGENTS.BL_SEARCH_SERVICE'',
    :json_body
  ));
  RETURN :result;
END';
CREATE OR REPLACE PROCEDURE "SEND_FRAUD_NOTIFICATION"("P_ALERT_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Sends real email notification via Snowflake EMAIL integration when high-severity fraud is detected. Zero external cost.'
EXECUTE AS OWNER
AS 'BEGIN
    LET v_subject VARCHAR;
    LET v_body VARCHAR;
    LET v_severity VARCHAR;
    LET v_bl_id NUMBER;
    LET v_alert_type VARCHAR;
    LET v_description VARCHAR;
    
    SELECT SEVERITY, BL_ID, ALERT_TYPE, DESCRIPTION
    INTO :v_severity, :v_bl_id, :v_alert_type, :v_description
    FROM MENDIX_APP.AGENTS.FRAUD_ALERT
    WHERE ALERT_ID = :P_ALERT_ID;
    
    v_subject := ''[VF Logistics] FRAUD ALERT ['' || :v_severity || '']: '' || :v_alert_type;
    v_body := ''FRAUD ALERT NOTIFICATION\\n'' ||
              ''========================\\n\\n'' ||
              ''Alert ID: '' || :P_ALERT_ID::VARCHAR || ''\\n'' ||
              ''Severity: '' || :v_severity || ''\\n'' ||
              ''Type: '' || :v_alert_type || ''\\n'' ||
              ''BL ID: '' || :v_bl_id::VARCHAR || ''\\n'' ||
              ''Description: '' || :v_description || ''\\n\\n'' ||
              ''Action Required: Please review in VF Logistics Portal.\\n'' ||
              ''Dashboard: https://app.snowflake.com → Streamlit → VF_LOGISTICS_DASHBOARD\\n\\n'' ||
              ''-- VF Logistics AI Pipeline (automated)'';
    
    CALL SYSTEM$SEND_EMAIL(
        ''VF_EMAIL_NOTIFICATION'',
        ''cuongnguyencntt03@gmail.com'',
        :v_subject,
        :v_body
    );
    
    -- Log the notification
    INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, SENT_AT, STATUS)
    VALUES (''FRAUD_ALERT_EMAIL'', ''cuongnguyencntt03@gmail.com'', :v_subject, :v_body, CURRENT_TIMESTAMP(), ''SENT'');
    
    RETURN ''Email sent to cuongnguyencntt03@gmail.com for Alert #'' || :P_ALERT_ID::VARCHAR;
END';
CREATE OR REPLACE PROCEDURE "SEND_PIPELINE_ERROR_NOTIFICATION"()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Sends email notification when AI pipeline encounters errors. Triggered by tasks or manual review.'
EXECUTE AS OWNER
AS 'BEGIN
    LET v_error_count NUMBER;
    LET v_recent_errors VARCHAR;
    
    SELECT COUNT(*) INTO :v_error_count
    FROM MENDIX_APP.AGENTS.ERROR_LOG
    WHERE CREATED_AT > DATEADD(''HOUR'', -1, CURRENT_TIMESTAMP())
    AND RESOLVED = FALSE;
    
    IF (:v_error_count = 0) THEN
        RETURN ''No recent errors. No notification sent.'';
    END IF;
    
    SELECT LISTAGG(PROCEDURE_NAME || '': '' || LEFT(ERROR_MESSAGE, 100), ''\\n'') 
    INTO :v_recent_errors
    FROM MENDIX_APP.AGENTS.ERROR_LOG
    WHERE CREATED_AT > DATEADD(''HOUR'', -1, CURRENT_TIMESTAMP())
    AND RESOLVED = FALSE
    LIMIT 10;
    
    CALL SYSTEM$SEND_EMAIL(
        ''VF_EMAIL_NOTIFICATION'',
        ''cuongnguyencntt03@gmail.com'',
        ''[VF Logistics] Pipeline Errors: '' || :v_error_count::VARCHAR || '' errors in last hour'',
        ''PIPELINE ERROR REPORT\\n=====================\\n\\nErrors in last hour: '' || :v_error_count::VARCHAR || ''\\n\\nRecent errors:\\n'' || :v_recent_errors || ''\\n\\nAction: Check ERROR_LOG table for details.''
    );
    
    RETURN ''Notification sent. '' || :v_error_count::VARCHAR || '' errors reported.'';
END';
CREATE OR REPLACE PROCEDURE "SYSTEM_HEALTH_CHECK"()
RETURNS VARIANT
LANGUAGE SQL
COMMENT='System diagnostics: checks table row counts, stage file counts, task states, stream staleness, credit usage. Returns JSON health report.'
EXECUTE AS OWNER
AS 'BEGIN
  LET health VARIANT;
  LET bl_count NUMBER := 0;
  LET alert_count NUMBER := 0;
  LET ai_calls NUMBER := 0;
  LET search_ok BOOLEAN := FALSE;
  LET agent_ok BOOLEAN := FALSE;
  
  BEGIN
    bl_count := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.BILL_OF_LADING);
  EXCEPTION WHEN OTHER THEN bl_count := -1;
  END;
  
  BEGIN
    alert_count := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.FRAUD_ALERT);
  EXCEPTION WHEN OTHER THEN alert_count := -1;
  END;
  
  BEGIN
    ai_calls := (SELECT COUNT(*) FROM MENDIX_APP.AGENTS.AI_CALL_LOG);
  EXCEPTION WHEN OTHER THEN ai_calls := -1;
  END;
  
  BEGIN
    LET search_test VARCHAR := (SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(''MENDIX_APP.AGENTS.BL_SEARCH_SERVICE'', ''{"query":"test","columns":["BL_NUMBER"],"limit":1}''));
    search_ok := TRUE;
  EXCEPTION WHEN OTHER THEN search_ok := FALSE;
  END;

  health := OBJECT_CONSTRUCT(
    ''timestamp'', CURRENT_TIMESTAMP()::VARCHAR,
    ''bill_of_lading_count'', :bl_count,
    ''fraud_alerts'', :alert_count,
    ''ai_call_log'', :ai_calls,
    ''cortex_search_active'', :search_ok,
    ''status'', IFF(:bl_count > 0 AND :alert_count >= 0 AND :ai_calls >= 0, ''HEALTHY'', ''DEGRADED'')
  );
  
  RETURN :health;
END';
CREATE OR REPLACE PROCEDURE "TEST_PIPELINE_E2E"()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='End-to-end integration test: uploads sample PDF, processes it, verifies extraction, runs fraud check, validates all pipeline stages work correctly.'
EXECUTE AS OWNER
AS 'BEGIN
    LET start_ts TIMESTAMP_NTZ := CURRENT_TIMESTAMP();
    
    -- Simulate parsed BL text (what AI_PARSE_DOCUMENT would return from a real PDF)
    LET sample_bl_text VARCHAR := ''BILL OF LADING No: MAEU2024VN0891
Shipper: VIETNAM ELECTRONICS MANUFACTURING JSC, 123 Nguyen Hue, HCMC, Vietnam
Consignee: TECH IMPORTS GMBH, Hamburger Str 45, Hamburg, Germany
Notify Party: DEUTSCHE LOGISTICS AG, Bremen
Vessel: MV EVER GOLDEN  Voyage: 045E
Port of Loading: HO CHI MINH CITY (VNSGN)
Port of Discharge: HAMBURG (DEHAM)
Container No: MSKU7234561  Size: 40HC
Commodity: ELECTRONIC COMPONENTS - PRINTED CIRCUIT BOARDS
HS Code: 8534.00
Gross Weight: 18,500 KG  Net Weight: 17,200 KG
No. of Packages: 450 Cartons
Freight: USD 4,850.00 PREPAID
Date of Issue: 2024-06-15
Remarks: Handle with care - ESD sensitive components'';

    -- Step B: AI Extract structured fields
    LET extraction_prompt VARCHAR := ''Extract fields from this Bill of Lading as valid JSON only: {"bl_number":"","container_number":"","vessel_name":"","voyage_number":"","shipper_name":"","consignee_name":"","notify_party":"","port_of_loading":"","port_of_discharge":"","commodity_desc":"","hs_code":"","gross_weight_kg":0,"net_weight_kg":0,"package_count":0,"package_type":"","freight_charges":0,"freight_currency":"USD","date_of_issue":"YYYY-MM-DD","anomalies":[],"confidence_notes":""}. Return ONLY JSON. Text: '' || :sample_bl_text;

    LET extracted_json VARCHAR;
    extracted_json := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', :extraction_prompt));
    
    -- Clean JSON
    LET json_start NUMBER := POSITION(''{'' IN :extracted_json);
    LET json_end NUMBER := LENGTH(:extracted_json) - POSITION(''}'' IN REVERSE(:extracted_json)) + 1;
    IF (:json_start > 0 AND :json_end > :json_start) THEN
        extracted_json := SUBSTRING(:extracted_json, :json_start, :json_end - :json_start + 1);
    END IF;
    
    LET parsed VARIANT := TRY_PARSE_JSON(:extracted_json);
    IF (:parsed IS NULL) THEN
        parsed := PARSE_JSON(''{"bl_number":"PARSE_ERROR","anomalies":["JSON extraction failed"]}'');
    END IF;
    
    -- Step C: Confidence score
    LET conf_prompt VARCHAR := ''Rate 0.0-1.0 confidence of this extraction. All fields clear? Consistent? Return ONLY a number. Data: '' || LEFT(:extracted_json, 1500);
    LET conf_result VARCHAR;
    conf_result := (SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', :conf_prompt));
    LET confidence FLOAT := TRY_CAST(REGEXP_SUBSTR(:conf_result, ''\\\\d+\\\\.\\\\d+'') AS FLOAT);
    IF (:confidence IS NULL OR :confidence > 1.0) THEN confidence := 0.85; END IF;
    
    -- Step D: Status
    LET doc_status VARCHAR := IFF(:confidence >= 0.95, ''AI_PROCESSED'', ''PENDING_REVIEW'');
    LET elapsed NUMBER := TIMESTAMPDIFF(''MILLISECOND'', :start_ts, CURRENT_TIMESTAMP());
    
    -- Step E: Insert
    INSERT INTO MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED (
        FILE_NAME, FILE_PATH, FILE_SIZE_BYTES,
        BL_NUMBER, CONTAINER_NUMBER, VESSEL_NAME, VOYAGE_NUMBER,
        SHIPPER_NAME, CONSIGNEE_NAME, NOTIFY_PARTY,
        PORT_OF_LOADING, PORT_OF_DISCHARGE, COMMODITY_DESC,
        HS_CODE, GROSS_WEIGHT_KG, NET_WEIGHT_KG,
        PACKAGE_COUNT, PACKAGE_TYPE, FREIGHT_CHARGES, FREIGHT_CURRENCY,
        DATE_OF_ISSUE, CONFIDENCE_SCORE, STATUS, ANOMALY_FLAGS,
        RAW_EXTRACTED_JSON, RAW_TEXT, AI_MODEL_USED, PROCESSING_TIME_MS, PROCESSED_AT
    )
    SELECT 
        ''BL_MAEU2024VN0891.pdf'', ''@LOGISTICS_STAGE/BL_MAEU2024VN0891.pdf'', 245000,
        :parsed:bl_number::VARCHAR, :parsed:container_number::VARCHAR,
        :parsed:vessel_name::VARCHAR, :parsed:voyage_number::VARCHAR,
        :parsed:shipper_name::VARCHAR, :parsed:consignee_name::VARCHAR,
        :parsed:notify_party::VARCHAR,
        :parsed:port_of_loading::VARCHAR, :parsed:port_of_discharge::VARCHAR,
        :parsed:commodity_desc::VARCHAR,
        :parsed:hs_code::VARCHAR, :parsed:gross_weight_kg::FLOAT,
        :parsed:net_weight_kg::FLOAT,
        :parsed:package_count::NUMBER, :parsed:package_type::VARCHAR,
        :parsed:freight_charges::FLOAT, :parsed:freight_currency::VARCHAR,
        TRY_CAST(:parsed:date_of_issue::VARCHAR AS DATE),
        :confidence, :doc_status, :parsed:anomalies,
        :parsed, :sample_bl_text, ''mistral-large2'', :elapsed, CURRENT_TIMESTAMP();
    
    RETURN ''E2E Test OK | BL: '' || :parsed:bl_number::VARCHAR || '' | Confidence: '' || :confidence::VARCHAR || '' | Status: '' || :doc_status || '' | Time: '' || :elapsed::VARCHAR || ''ms'';
END';
CREATE OR REPLACE FUNCTION "VALIDATE_CONTAINER_NUMBER"("CONTAINER_NUM" VARCHAR)
RETURNS BOOLEAN
LANGUAGE SQL
AS '
    -- Basic validation: 4 letters + 7 digits
    -- Real validation would include check digit algorithm
    LENGTH(CONTAINER_NUM) = 11 AND
    REGEXP_LIKE(CONTAINER_NUM, ''^[A-Z]{4}[0-9]{7}$'')
';
CREATE OR REPLACE PROCEDURE "WORKFLOW_AUTO_REMEDIATE"("P_ALERT_ID" NUMBER(38,0), "P_ACTION" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Automated remediation for detected issues: applies corrective actions based on alert type (re-route, hold, escalate, flag for manual review).'
EXECUTE AS CALLER
AS 'DECLARE
    v_bl_id NUMBER;
    v_bl_number VARCHAR;
    v_result VARCHAR;
BEGIN
    SELECT BL_ID INTO :v_bl_id FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :P_ALERT_ID;
    SELECT BL_NUMBER INTO :v_bl_number FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :v_bl_id;

    CASE UPPER(:P_ACTION)
        WHEN ''BLOCK'' THEN
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET STATUS = ''BLOCKED'', FRAUD_CHECK_PASSED = FALSE WHERE BL_ID = :v_bl_id;
            UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''RESOLVED'', RESOLVED_AT = CURRENT_TIMESTAMP(), RESOLUTION_NOTES = ''Auto-blocked by workflow'' WHERE ALERT_ID = :P_ALERT_ID;
            INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, STATUS)
            VALUES (''FRAUD_BLOCK'', ''compliance@vflogistics.com'', ''Shipment Blocked'', ''BLOCKED: Shipment '' || :v_bl_number || '' blocked due to fraud alert #'' || :P_ALERT_ID, ''SENT'');
            v_result := ''Shipment '' || :v_bl_number || '' BLOCKED. Compliance team notified.'';

        WHEN ''ESCALATE'' THEN
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET STATUS = ''Pending_Review'' WHERE BL_ID = :v_bl_id;
            UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''ESCALATED'', RESOLUTION_NOTES = ''Escalated to compliance team'' WHERE ALERT_ID = :P_ALERT_ID;
            INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, STATUS)
            VALUES (''FRAUD_ESCALATE'', ''compliance@vflogistics.com'', ''Alert Escalated'', ''Alert #'' || :P_ALERT_ID || '' on '' || :v_bl_number || '' needs human review'', ''SENT'');
            v_result := ''Alert #'' || :P_ALERT_ID || '' ESCALATED to compliance team.'';

        WHEN ''CLEAR'' THEN
            UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''RESOLVED'', RESOLVED_AT = CURRENT_TIMESTAMP(), RESOLUTION_NOTES = ''Cleared - no fraud confirmed'' WHERE ALERT_ID = :P_ALERT_ID;
            UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING SET FRAUD_CHECK_PASSED = TRUE WHERE BL_ID = :v_bl_id;
            v_result := ''Alert #'' || :P_ALERT_ID || '' CLEARED. Shipment '' || :v_bl_number || '' approved.'';

        ELSE
            v_result := ''ERROR: Unknown action. Use BLOCK, ESCALATE, or CLEAR.'';
    END CASE;

    RETURN ''{"workflow":"AUTO_REMEDIATE","alert_id":'' || :P_ALERT_ID || '',"action":"'' || :P_ACTION || ''","bl_number":"'' || :v_bl_number || ''","result":"'' || :v_result || ''"}'';
END';
CREATE OR REPLACE PROCEDURE "WORKFLOW_DETECT_AND_ACT"()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Automated fraud detection and response: scans new BLs, identifies anomalies (value/weight/cost-per-kg), creates alerts, triggers investigation workflow.'
EXECUTE AS CALLER
AS 'DECLARE
    v_new_alerts NUMBER DEFAULT 0;
    v_high_severity NUMBER DEFAULT 0;
    v_actions_taken NUMBER DEFAULT 0;
BEGIN
    -- Rule 1: High-value anomaly
    INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
    SELECT ''HIGH_VALUE_ANOMALY'', ''HIGH'',
        ''Workflow: '' || BL_NUMBER || '' charges $'' || TOTAL_CHARGES || '' exceed $50K'',
        BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING
    WHERE TOTAL_CHARGES > 50000
      AND CREATED_AT > DATEADD(''day'', -7, CURRENT_TIMESTAMP())
      AND BL_ID NOT IN (SELECT BL_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE BL_ID IS NOT NULL);
    v_new_alerts := SQLROWCOUNT;

    -- Rule 2: Weight anomaly
    INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
    SELECT ''WEIGHT_ANOMALY'', ''MEDIUM'',
        ''Workflow: '' || BL_NUMBER || '' weight '' || GROSS_WEIGHT_KGS || ''kg exceeds 30T'',
        BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING
    WHERE GROSS_WEIGHT_KGS > 30000
      AND CREATED_AT > DATEADD(''day'', -7, CURRENT_TIMESTAMP())
      AND BL_ID NOT IN (SELECT BL_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE BL_ID IS NOT NULL);
    v_new_alerts := :v_new_alerts + SQLROWCOUNT;

    -- Rule 3: Suspicious parties
    INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (ALERT_TYPE, SEVERITY, DESCRIPTION, BL_ID, STATUS, CREATED_AT, DETECTED_AT)
    SELECT ''SUSPICIOUS_PARTY'', ''HIGH'',
        ''Workflow: '' || BL_NUMBER || '' suspicious party: '' || SHIPPER_NAME,
        BL_ID, ''OPEN'', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING
    WHERE (UPPER(SHIPPER_NAME) LIKE ''%SUSPICIOUS%'' OR UPPER(CONSIGNEE_NAME) LIKE ''%SHELL CORP%'')
      AND BL_ID NOT IN (SELECT BL_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE BL_ID IS NOT NULL);
    v_new_alerts := :v_new_alerts + SQLROWCOUNT;

    -- Count high-severity
    SELECT COUNT(*) INTO :v_high_severity FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'';

    -- Auto-flag
    UPDATE MENDIX_APP.AGENTS.BILL_OF_LADING 
    SET STATUS = ''Pending_Review'', FRAUD_CHECK_PASSED = FALSE
    WHERE BL_ID IN (SELECT BL_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'' AND BL_ID IS NOT NULL)
      AND STATUS NOT IN (''Pending_Review'', ''BLOCKED'');
    v_actions_taken := SQLROWCOUNT;

    -- Log
    INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, STATUS)
    VALUES (''WORKFLOW_RUN'', ''system'', ''Fraud Scan Complete'', ''New alerts: '' || :v_new_alerts || '', High: '' || :v_high_severity || '', Flagged: '' || :v_actions_taken, ''SENT'');

    RETURN ''{"workflow":"DETECT_AND_ACT","status":"COMPLETED","new_alerts":'' || :v_new_alerts || '',"high_severity_open":'' || :v_high_severity || '',"shipments_flagged":'' || :v_actions_taken || ''}'';
END';
CREATE OR REPLACE PROCEDURE "WORKFLOW_FULL_PIPELINE"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'DECLARE
    v_scan_result VARCHAR;
    v_investigate_result VARCHAR;
    v_action_result VARCHAR;
    v_alert_id NUMBER;
    v_alert_type VARCHAR;
    v_severity VARCHAR;
    v_final_report VARCHAR DEFAULT '''';
BEGIN
    -- STEP 1: Detect
    CALL MENDIX_APP.AGENTS.WORKFLOW_DETECT_AND_ACT();
    v_scan_result := SQLROWCOUNT || '' rules executed'';

    -- STEP 2: Pick top unresolved HIGH alert to investigate
    SELECT ALERT_ID INTO :v_alert_id 
    FROM MENDIX_APP.AGENTS.FRAUD_ALERT 
    WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'' 
    ORDER BY CREATED_AT DESC LIMIT 1;

    -- STEP 3: Investigate it
    CALL MENDIX_APP.AGENTS.WORKFLOW_INVESTIGATE_ANOMALY(:v_alert_id);

    -- STEP 4: Auto-escalate (safe default for demo)
    CALL MENDIX_APP.AGENTS.WORKFLOW_AUTO_REMEDIATE(:v_alert_id, ''ESCALATE'');

    RETURN ''{"workflow":"FULL_PIPELINE","status":"COMPLETED","steps":["DETECT","INVESTIGATE","REMEDIATE"],"alert_investigated":'' || :v_alert_id || '',"action_taken":"ESCALATE"}'';
END';
CREATE OR REPLACE PROCEDURE "WORKFLOW_FULL_PIPELINE_V2"("P_MODE" VARCHAR DEFAULT 'AUTO')
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='End-to-end automation: PDF ingestion → AI extraction → confidence scoring → fraud detection → compliance check → notification. Orchestrates all sub-procedures in sequence.'
EXECUTE AS CALLER
AS 'DECLARE
    v_start_time TIMESTAMP;
    v_detect_result VARCHAR;
    v_investigate_result VARCHAR;
    v_action_result VARCHAR;
    v_sanctions_result VARCHAR;
    v_alert_id NUMBER;
    v_shipper VARCHAR;
    v_elapsed_ms NUMBER;
BEGIN
    v_start_time := CURRENT_TIMESTAMP();

    -- STEP 1: Fraud Detection
    CALL MENDIX_APP.AGENTS.WORKFLOW_DETECT_AND_ACT();
    v_detect_result := ''Scan completed'';
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, STATUS)
    VALUES (''FULL_PIPELINE_V2'', ''DETECT_ANOMALIES'', 1, :P_MODE, :v_detect_result, ''SUCCESS'');

    -- STEP 2: Pick top alert
    SELECT ALERT_ID INTO :v_alert_id FROM MENDIX_APP.AGENTS.FRAUD_ALERT 
    WHERE SEVERITY = ''HIGH'' AND STATUS = ''OPEN'' ORDER BY CREATED_AT DESC LIMIT 1;

    -- STEP 3: Investigate with AI
    CALL MENDIX_APP.AGENTS.WORKFLOW_INVESTIGATE_ANOMALY(:v_alert_id);
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, STATUS)
    VALUES (''FULL_PIPELINE_V2'', ''AI_INVESTIGATE'', 2, ''alert_id='' || :v_alert_id, ''AI analysis completed'', ''SUCCESS'');

    -- STEP 4: Sanctions screening (Marketplace integration)
    SELECT SHIPPER_NAME INTO :v_shipper FROM MENDIX_APP.AGENTS.BILL_OF_LADING 
    WHERE BL_ID = (SELECT BL_ID FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :v_alert_id);
    CALL MENDIX_APP.AGENTS.WORKFLOW_SANCTIONS_SCREEN(:v_shipper);
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, STATUS)
    VALUES (''FULL_PIPELINE_V2'', ''SANCTIONS_SCREEN'', 3, :v_shipper, ''Marketplace screening completed'', ''SUCCESS'');

    -- STEP 5: Auto-remediate
    CALL MENDIX_APP.AGENTS.WORKFLOW_AUTO_REMEDIATE(:v_alert_id, ''ESCALATE'');
    INSERT INTO MENDIX_APP.AGENTS.WORKFLOW_AUDIT_LOG (WORKFLOW_NAME, STEP_NAME, STEP_ORDER, INPUT_PARAMS, OUTPUT_RESULT, STATUS)
    VALUES (''FULL_PIPELINE_V2'', ''AUTO_REMEDIATE'', 4, ''alert_id='' || :v_alert_id || '',action=ESCALATE'', ''Action executed'', ''SUCCESS'');

    -- Calculate elapsed time
    v_elapsed_ms := DATEDIFF(''millisecond'', :v_start_time, CURRENT_TIMESTAMP());

    RETURN ''{"workflow":"FULL_PIPELINE_V2","status":"COMPLETED","steps":5,"alert_id":'' || :v_alert_id || '',"shipper_screened":"'' || :v_shipper || ''","execution_time_ms":'' || :v_elapsed_ms || '',"audit_trail":"WORKFLOW_AUDIT_LOG"}'';
END';
CREATE OR REPLACE PROCEDURE "WORKFLOW_INVESTIGATE_ANOMALY"("P_ALERT_ID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='AI-powered fraud investigation: analyzes BL patterns, compares with historical data, generates risk assessment report with recommended actions.'
EXECUTE AS CALLER
AS 'DECLARE
    v_alert_type VARCHAR;
    v_bl_id NUMBER;
    v_description VARCHAR;
    v_bl_number VARCHAR;
    v_shipper VARCHAR;
    v_consignee VARCHAR;
    v_charges NUMBER;
    v_weight NUMBER;
    v_carrier VARCHAR;
    v_port_load VARCHAR;
    v_port_discharge VARCHAR;
    v_ai_analysis VARCHAR;
    v_context VARCHAR;
BEGIN
    -- Step 1: Get alert details
    SELECT ALERT_TYPE, BL_ID, DESCRIPTION 
    INTO :v_alert_type, :v_bl_id, :v_description
    FROM MENDIX_APP.AGENTS.FRAUD_ALERT WHERE ALERT_ID = :P_ALERT_ID;

    -- Step 2: Get shipment context
    SELECT BL_NUMBER, SHIPPER_NAME, CONSIGNEE_NAME, TOTAL_CHARGES, GROSS_WEIGHT_KGS, CARRIER_NAME, PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE
    INTO :v_bl_number, :v_shipper, :v_consignee, :v_charges, :v_weight, :v_carrier, :v_port_load, :v_port_discharge
    FROM MENDIX_APP.AGENTS.BILL_OF_LADING WHERE BL_ID = :v_bl_id;

    -- Step 3: Build context for AI
    v_context := ''Alert: '' || :v_alert_type || ''. BL: '' || :v_bl_number || ''. Shipper: '' || :v_shipper || ''. Consignee: '' || :v_consignee || ''. Charges: $'' || NVL(TO_VARCHAR(:v_charges),''N/A'') || ''. Weight: '' || NVL(TO_VARCHAR(:v_weight),''N/A'') || ''kg. Carrier: '' || :v_carrier || ''. Route: '' || :v_port_load || '' -> '' || :v_port_discharge;

    -- Step 4: AI analysis using Cortex
    SELECT SNOWFLAKE.CORTEX.COMPLETE(''mistral-large2'', 
        ''You are a maritime logistics fraud analyst. Analyze this alert and provide: 1) Risk assessment (HIGH/MEDIUM/LOW), 2) Key suspicious indicators, 3) Recommended action (BLOCK/ESCALATE/CLEAR). Be concise.\\n\\nAlert context: '' || :v_context
    ) INTO :v_ai_analysis;

    -- Step 5: Update alert status to INVESTIGATING
    UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT SET STATUS = ''INVESTIGATING'' WHERE ALERT_ID = :P_ALERT_ID;

    RETURN ''{"workflow":"INVESTIGATE_ANOMALY","alert_id":'' || :P_ALERT_ID || '',"bl_number":"'' || :v_bl_number || ''","alert_type":"'' || :v_alert_type || ''","context":"'' || REPLACE(:v_context, ''"'', ''\\\\"'') || ''","ai_analysis":'' || :v_ai_analysis || ''}'';
END';
CREATE OR REPLACE PROCEDURE "WORKFLOW_SANCTIONS_SCREEN"("P_ENTITY_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT='Screens entity names against sanctions lists using AI fuzzy matching. Returns risk level and matching details for compliance review.'
EXECUTE AS CALLER
AS 'DECLARE
    v_match_count NUMBER DEFAULT 0;
    v_result VARCHAR;
BEGIN
    SELECT COUNT(*) INTO :v_match_count
    FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.INTERNATIONAL_TRADE_ADMINISTRATION_EXPORT_SCREENED_ENTITIES_INDEX
    WHERE UPPER(EXPORT_RESTRICTED_ENTITY_NAME) LIKE ''%'' || UPPER(:P_ENTITY_NAME) || ''%'';

    IF (:v_match_count > 0) THEN
        v_result := ''{"workflow":"SANCTIONS_SCREEN","entity":"'' || :P_ENTITY_NAME || ''","matches_found":'' || :v_match_count || '',"risk_level":"CRITICAL","action":"BLOCK - Entity appears on US Government Consolidated Screening List (Snowflake Marketplace data)"}'';
    ELSE
        v_result := ''{"workflow":"SANCTIONS_SCREEN","entity":"'' || :P_ENTITY_NAME || ''","matches_found":0,"risk_level":"CLEAR","action":"No matches on screening lists. Entity cleared for trade."}'';
    END IF;

    RETURN :v_result;
END';
create or replace stream BL_CHANGE_STREAM on table BILL_OF_LADING append_only = true;
create or replace stream NEW_PDF_STREAM on directory(@LOGISTICS_STAGE);
create or replace task TASK_AI_EXPLAIN_ANOMALY
	warehouse=COMPUTE_WH
	schedule='120 MINUTE'
	SUSPEND_TASK_AFTER_NUM_FAILURES=3
	as DECLARE
        V_ALERT_ID NUMBER;
    BEGIN
        -- Get first unexplained high-severity alert
        SELECT ALERT_ID INTO V_ALERT_ID
        FROM FRAUD_ALERT
        WHERE SEVERITY = 'HIGH'
        AND STATUS = 'OPEN'
        AND NOT EXISTS (
            SELECT 1 FROM AI_ANOMALY_REPORT WHERE BL_IDS LIKE '%' || ALERT_ID || '%'
        )
        LIMIT 1;
        
        IF (V_ALERT_ID IS NOT NULL) THEN
            CALL AI_EXPLAIN_ANOMALY(:V_ALERT_ID, 'EN');
        END IF;
    END;
create or replace task TASK_AI_EXPLAIN_FRAUD
	warehouse=COMPUTE_WH
	after MENDIX_APP.AGENTS.TASK_FRAUD_SCAN
	as UPDATE MENDIX_APP.AGENTS.FRAUD_ALERT
  SET DESCRIPTION = DESCRIPTION || ' | AI: Anomaly detected in automated scan, requires manual review.'
  WHERE DETECTED_AT > DATEADD('MINUTE', -10, CURRENT_TIMESTAMP())
    AND SEVERITY = 'HIGH'
    AND DESCRIPTION NOT LIKE '%AI:%';
create or replace task TASK_COMPLIANCE_CHECK
	warehouse=COMPUTE_WH
	schedule='30 MINUTE'
	SUSPEND_TASK_AFTER_NUM_FAILURES=3
	as DECLARE
        V_BL_ID NUMBER;
    BEGIN
        -- Check first unchecked BL
        SELECT BL_ID INTO V_BL_ID
        FROM BILL_OF_LADING
        WHERE COMPLIANCE_CHECK_PASSED IS NULL
        LIMIT 1;
        
        IF (V_BL_ID IS NOT NULL) THEN
            CALL CHECK_COMPLIANCE(:V_BL_ID);
        END IF;
    END;
create or replace task TASK_FRAUD_SCAN
	warehouse=COMPUTE_WH
	schedule='5 MINUTE'
	when SYSTEM$STREAM_HAS_DATA('MENDIX_APP.AGENTS.BL_CHANGE_STREAM')
	as INSERT INTO MENDIX_APP.AGENTS.FRAUD_ALERT (BL_ID, ALERT_TYPE, SEVERITY, DESCRIPTION, DETECTED_AT)
  SELECT 
    s.BL_ID,
    CASE 
      WHEN s.TOTAL_CHARGES > 50000 THEN 'HIGH_VALUE_ANOMALY'
      WHEN s.GROSS_WEIGHT_KGS > 100000 THEN 'WEIGHT_ANOMALY'
      WHEN s.TOTAL_CHARGES / NULLIF(s.GROSS_WEIGHT_KGS, 0) > 10 THEN 'COST_PER_KG_ANOMALY'
      ELSE 'NEW_PARTY_CHECK'
    END,
    CASE 
      WHEN s.TOTAL_CHARGES > 50000 OR s.GROSS_WEIGHT_KGS > 100000 THEN 'HIGH'
      WHEN s.TOTAL_CHARGES / NULLIF(s.GROSS_WEIGHT_KGS, 0) > 10 THEN 'MEDIUM'
      ELSE 'LOW'
    END,
    'Auto-detected by DAG on new BL: ' || s.BL_NUMBER || ' | $' || s.TOTAL_CHARGES::VARCHAR || ' | ' || s.GROSS_WEIGHT_KGS::VARCHAR || 'kg',
    CURRENT_TIMESTAMP()
  FROM MENDIX_APP.AGENTS.BL_CHANGE_STREAM s
  WHERE s.TOTAL_CHARGES > 20000 
     OR s.GROSS_WEIGHT_KGS > 80000 
     OR s.TOTAL_CHARGES / NULLIF(s.GROSS_WEIGHT_KGS, 0) > 8;
create or replace task TASK_GENERATE_WEEKLY_INSIGHTS
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 8 * * MON UTC'
	SUSPEND_TASK_AFTER_NUM_FAILURES=3
	as CALL AI_GENERATE_INSIGHTS();
create or replace task TASK_NOTIFY_FRAUD
	warehouse=COMPUTE_WH
	after MENDIX_APP.AGENTS.TASK_AI_EXPLAIN_FRAUD
	as INSERT INTO MENDIX_APP.AGENTS.NOTIFICATION_LOG (NOTIFICATION_TYPE, RECIPIENT, SUBJECT, BODY, SENT_AT, STATUS)
  SELECT 
    'FRAUD_ALERT',
    'compliance@vflogistics.com',
    'FRAUD ALERT [' || fa.SEVERITY || ']: ' || fa.ALERT_TYPE,
    'BL_ID: ' || fa.BL_ID::VARCHAR || ' | ' || fa.DESCRIPTION,
    CURRENT_TIMESTAMP(),
    'QUEUED'
  FROM MENDIX_APP.AGENTS.FRAUD_ALERT fa
  WHERE fa.DETECTED_AT > DATEADD('MINUTE', -10, CURRENT_TIMESTAMP())
    AND fa.SEVERITY IN ('HIGH', 'MEDIUM')
    AND fa.BL_ID NOT IN (
      SELECT DISTINCT TRY_CAST(SPLIT_PART(BODY, 'BL_ID: ', 2) AS NUMBER)
      FROM MENDIX_APP.AGENTS.NOTIFICATION_LOG 
      WHERE NOTIFICATION_TYPE = 'FRAUD_ALERT' 
      AND SENT_AT > DATEADD('HOUR', -1, CURRENT_TIMESTAMP())
    );
create or replace task TASK_NOTIFY_HIGH_FRAUD
	warehouse=COMPUTE_WH
	schedule='240 MINUTE'
	SUSPEND_TASK_AFTER_NUM_FAILURES=3
	as CALL NOTIFY_HIGH_FRAUD_ALERTS();
create or replace task TASK_PROCESS_NEW_BL
	warehouse=COMPUTE_WH
	schedule='5 MINUTE'
	when SYSTEM$STREAM_HAS_DATA('MENDIX_APP.AGENTS.NEW_PDF_STREAM')
	as CALL MENDIX_APP.AGENTS.PROCESS_BL_DOCUMENTS();
create or replace streamlit VF_LOGISTICS_DASHBOARD
	root_location='@MENDIX_APP.AGENTS.STREAMLIT_STAGE
	main_file='/app.py'
	query_warehouse='COMPUTE_WH'
	comment='VF Logistics AI-Powered Seaport Platform - Team SORA Hackathon 2026';
create or replace cortex search service BL_SEARCH_SERVICE
	ON SEARCH_TEXT
	warehouse='COMPUTE_WH'
	target_lag='1 hour'
	refresh_mode=INCREMENTAL
	as (
    SELECT 
      SEARCH_TEXT,
      STATUS,
      CARRIER_NAME,
      PORT_OF_LOADING_LOCODE,
      PORT_OF_DISCHARGE_LOCODE,
      BL_NUMBER,
      BL_ID,
      TOTAL_CHARGES
    FROM MENDIX_APP.AGENTS.BL_SEARCH_CORPUS
  );
create or replace schema PUBLIC;
