// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package vf_logistics_portal.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import java.sql.*;
import java.util.Properties;

public class CallCortexAgent extends UserAction<java.lang.String>
{
	private final java.lang.String UserMessage;

	public CallCortexAgent(
		IContext context,
		java.lang.String _userMessage
	)
	{
		super(context);
		this.UserMessage = _userMessage;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		// === CONFIG ===
		String account = "YGVORDH-IA82097";
		String user = "MENDIX_SERVICE_USER";
		String database = "MENDIX_APP";
		String schema = "AGENTS";
		String warehouse = "COMPUTE_WH";

		// === 1. Connect via JDBC ===
		String jdbcUrl = "jdbc:snowflake://" + account + ".snowflakecomputing.com/";

		String password = System.getenv("SNOWFLAKE_MENDIX_PASSWORD");
		if (password == null || password.isEmpty()) {
			return "Configuration error: SNOWFLAKE_MENDIX_PASSWORD environment variable is not set.";
		}

		Properties props = new Properties();
		props.put("user", user);
		props.put("password", password);
		props.put("db", database);
		props.put("schema", schema);
		props.put("warehouse", warehouse);
		props.put("role", "ACCOUNTADMIN");
		props.put("JDBC_QUERY_RESULT_FORMAT", "JSON");

		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;

		try {
			Class.forName("net.snowflake.client.jdbc.SnowflakeDriver");
			conn = DriverManager.getConnection(jdbcUrl, props);
			stmt = conn.createStatement();

			// Simply call the stored procedure
			String safeMsg = UserMessage.replace("'", "''").replace("\\", "");
			String callSQL = "CALL MENDIX_APP.AGENTS.CHAT_WITH_DATA('" + safeMsg + "')";

			rs = stmt.executeQuery(callSQL);
			rs.next();
			String answer = rs.getString(1);

			return answer != null ? answer.trim() : "No response";

		} catch (Exception e) {
			return "Connection error: " + e.getMessage();
		} finally {
			if (rs != null) try { rs.close(); } catch (Exception e) {}
			if (stmt != null) try { stmt.close(); } catch (Exception e) {}
			if (conn != null) try { conn.close(); } catch (Exception e) {}
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CallCortexAgent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
