// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package vf_logistics_portal.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import java.io.*;
import java.sql.*;
import java.util.Properties;

/**
 * Upload a FileDocument to Snowflake LOGISTICS_STAGE and return the staged filename.
 * 
 * Input: FileDocument (e.g., BillOfLading_Doc)
 * Output: String - staged filename path (e.g., "bill_of_lading/uploaded_1721741234567_invoice.pdf")
 */
public class UploadFileToSnowflake extends CustomJavaAction<java.lang.String>
{
	private final IMendixObject FileDocument;

	public UploadFileToSnowflake(
		IContext context,
		IMendixObject _fileDocument
	)
	{
		super(context);
		this.FileDocument = _fileDocument;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		// === VALIDATION ===
		if (FileDocument == null) {
			return "ERROR: No file provided";
		}

		Boolean hasContents = (Boolean) FileDocument.getValue(getContext(), "HasContents");
		if (hasContents == null || !hasContents) {
			return "ERROR: File has no contents";
		}

		// === GET FILE INFO ===
		String originalName = (String) FileDocument.getValue(getContext(), "Name");
		if (originalName == null || originalName.isEmpty()) {
			originalName = "document.pdf";
		}

		// Generate unique filename: uploaded_<timestamp>_<originalname>
		long timestamp = System.currentTimeMillis();
		String uniqueFilename = "uploaded_" + timestamp + "_" + originalName;
		String stagedPath = "bill_of_lading/" + uniqueFilename;

		// === WRITE FILE TO TEMP ===
		File tempFile = null;
		FileOutputStream fos = null;
		try {
			// Create temp file
			tempFile = File.createTempFile("mendix_upload_", ".pdf");
			tempFile.deleteOnExit();

			// Get file stream from Mendix FileDocument
			InputStream fileStream = Core.getFileDocumentContent(getContext(), FileDocument);
			fos = new FileOutputStream(tempFile);

			// Copy stream to temp file
			byte[] buffer = new byte[8192];
			int bytesRead;
			while ((bytesRead = fileStream.read(buffer)) != -1) {
				fos.write(buffer, 0, bytesRead);
			}
			fos.flush();
			fos.close();
			fileStream.close();

		} catch (Exception e) {
			return "ERROR: Failed to write temp file: " + e.getMessage();
		}

		// === SNOWFLAKE CONFIG ===
		String account = "DPYXIQZ-FN71223";
		String user = "HOACHAU";
		String database = "MENDIX_APP";
		String schema = "AGENTS";
		String warehouse = "COMPUTE_WH";
		String privateKeyPath = "C:/Users/phuochoa/.snowflake/keys/snowflake_key.p8";

		// === JDBC URL WITH JWT AUTH ===
		String jdbcUrl = String.format(
			"jdbc:snowflake://%s.snowflakecomputing.com/?authenticator=SNOWFLAKE_JWT&private_key_file=%s&JDBC_QUERY_RESULT_FORMAT=JSON",
			account,
			privateKeyPath
		);

		Properties props = new Properties();
		props.put("user", user);
		props.put("db", database);
		props.put("schema", schema);
		props.put("warehouse", warehouse);
		props.put("role", "ACCOUNTADMIN");

		Connection conn = null;
		Statement stmt = null;

		try {
			// === CONNECT TO SNOWFLAKE ===
			Class.forName("net.snowflake.client.jdbc.SnowflakeDriver");
			conn = DriverManager.getConnection(jdbcUrl, props);
			stmt = conn.createStatement();

			// === UPLOAD FILE WITH PUT COMMAND ===
			// PUT 'file://C:/path/to/temp.pdf' @MENDIX_APP.AGENTS.LOGISTICS_STAGE/bill_of_lading/uploaded_xxx.pdf AUTO_COMPRESS=FALSE OVERWRITE=TRUE
			String putCommand = String.format(
				"PUT 'file://%s' @MENDIX_APP.AGENTS.LOGISTICS_STAGE/%s AUTO_COMPRESS=FALSE OVERWRITE=TRUE",
				tempFile.getAbsolutePath().replace("\\", "/"),
				stagedPath
			);

			stmt.execute(putCommand);

			// === SUCCESS ===
			return stagedPath;

		} catch (Exception e) {
			return "ERROR: Snowflake upload failed: " + e.getMessage();
		} finally {
			// Cleanup
			if (stmt != null) try { stmt.close(); } catch (Exception e) {}
			if (conn != null) try { conn.close(); } catch (Exception e) {}
			if (tempFile != null && tempFile.exists()) {
				tempFile.delete();
			}
		}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UploadFileToSnowflake";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
