-- Account-level objects NOT covered by schema-level GET_DDL — captured 2026-08-17
-- Run as ACCOUNTADMIN on the new account BEFORE running 01_schema_ddl_fresh.sql.

-- 1. Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- 2. Resource monitor (current production values, verified 2026-08-17)
CREATE OR REPLACE RESOURCE MONITOR VF_LOGISTICS_MONITOR
    WITH CREDIT_QUOTA = 150
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 60 PERCENT DO NOTIFY
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND
        ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = VF_LOGISTICS_MONITOR;

-- 3. Marketplace dependency — MUST re-request before restoring views that reference
--    SNOWFLAKE_PUBLIC_DATA_FREE (V_EXCHANGE_RATES, V_EXPORT_RESTRICTED_ENTITIES,
--    V_AI_DECISION_EVAL, WORKFLOW_SANCTIONS_SCREEN, sanctions screening logic).
CALL SYSTEM$REQUEST_LISTING_AND_WAIT('GZTSZ290BV255', 120);
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_PUBLIC_DATA_FREE FROM LISTING 'GZTSZ290BV255';

-- 4. Notification integration (email, free/built-in) — recreate with the same recipient
CREATE NOTIFICATION INTEGRATION IF NOT EXISTS VF_EMAIL_NOTIFICATION
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ('cuongnguyencntt03@gmail.com')
    COMMENT = 'Email notifications for fraud alerts and pipeline failures';

-- 5. Least-privilege app role (grants replayed selectively — DO NOT blindly copy all
--    484 grants from SHOW GRANTS TO ROLE VF_APP_ROLE on the old account; most are
--    auto-generated per-object SELECT/INSERT grants that will be recreated naturally
--    once the FUTURE grants below are in place and 01_schema_ddl_fresh.sql has run).
CREATE ROLE IF NOT EXISTS VF_APP_ROLE
    COMMENT = 'Least-privilege role for VF Logistics Mendix integration';

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE VF_APP_ROLE;
GRANT USAGE ON DATABASE MENDIX_APP TO ROLE VF_APP_ROLE;
GRANT USAGE ON SCHEMA MENDIX_APP.AGENTS TO ROLE VF_APP_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_PUBLIC_DATA_FREE TO ROLE VF_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA MENDIX_APP.AGENTS TO ROLE VF_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MENDIX_APP.AGENTS TO ROLE VF_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA MENDIX_APP.AGENTS TO ROLE VF_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MENDIX_APP.AGENTS TO ROLE VF_APP_ROLE;
GRANT INSERT, UPDATE ON TABLE MENDIX_APP.AGENTS.BILL_OF_LADING TO ROLE VF_APP_ROLE;
GRANT INSERT, UPDATE ON TABLE MENDIX_APP.AGENTS.BILL_OF_LADING_EXTRACTED TO ROLE VF_APP_ROLE;
GRANT INSERT, UPDATE ON TABLE MENDIX_APP.AGENTS.FRAUD_ALERT TO ROLE VF_APP_ROLE;
GRANT INSERT ON TABLE MENDIX_APP.AGENTS.NOTIFICATION_LOG TO ROLE VF_APP_ROLE;
GRANT INSERT ON TABLE MENDIX_APP.AGENTS.AI_CALL_LOG TO ROLE VF_APP_ROLE;
GRANT INSERT ON TABLE MENDIX_APP.AGENTS.ERROR_LOG TO ROLE VF_APP_ROLE;
GRANT INSERT ON TABLE MENDIX_APP.AGENTS.COMPLIANCE_CHECK_RESULT TO ROLE VF_APP_ROLE;
GRANT INSERT ON TABLE MENDIX_APP.AGENTS.AI_ANOMALY_REPORT TO ROLE VF_APP_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA MENDIX_APP.AGENTS TO ROLE VF_APP_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MENDIX_APP.AGENTS TO ROLE VF_APP_ROLE;
GRANT READ ON STAGE MENDIX_APP.AGENTS.LOGISTICS_STAGE TO ROLE VF_APP_ROLE;
GRANT READ ON STAGE MENDIX_APP.AGENTS.STREAMLIT_STAGE TO ROLE VF_APP_ROLE;
GRANT ROLE VF_APP_ROLE TO ROLE ACCOUNTADMIN;

-- 6. Read-only judge role
CREATE ROLE IF NOT EXISTS HACKATHON_JUDGE_ROLE
    COMMENT = 'Read-only reviewer access — cannot CALL workflow procedures';
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HACKATHON_JUDGE_ROLE;
GRANT USAGE ON DATABASE MENDIX_APP TO ROLE HACKATHON_JUDGE_ROLE;
GRANT USAGE ON SCHEMA MENDIX_APP.AGENTS TO ROLE HACKATHON_JUDGE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA MENDIX_APP.AGENTS TO ROLE HACKATHON_JUDGE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MENDIX_APP.AGENTS TO ROLE HACKATHON_JUDGE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA MENDIX_APP.AGENTS TO ROLE HACKATHON_JUDGE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MENDIX_APP.AGENTS TO ROLE HACKATHON_JUDGE_ROLE;
GRANT ROLE HACKATHON_JUDGE_ROLE TO ROLE ACCOUNTADMIN;

-- 7. Mendix service user — KEY-PAIR (JWT) AUTH, NOT PASSWORD.
--    Current production auth uses SNOWFLAKE_JWT with a private key file
--    (snowflake_key.p8) stored only inside the Mendix Cloud sandbox runtime
--    resources folder — never in git. For the new account:
--      a) generate a NEW RSA key pair locally, e.g.:
--         openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out snowflake_key_new.p8 -nocrypt
--         openssl rsa -in snowflake_key_new.p8 -pubout -out snowflake_key_new.pub
--      b) create the user below, then run:
--         ALTER USER MENDIX_SERVICE_USER SET RSA_PUBLIC_KEY='<contents of snowflake_key_new.pub, no header/footer lines>';
--      c) upload snowflake_key_new.p8 into the Mendix Cloud sandbox resources folder
--         (replacing the old snowflake_key.p8), and update the hardcoded account
--         identifier in javasource/vf_logistics_portal/actions/CallCortexAgent.java
--         before republishing via Mendix Studio Pro.
CREATE USER IF NOT EXISTS MENDIX_SERVICE_USER
    DEFAULT_WAREHOUSE = COMPUTE_WH
    DEFAULT_NAMESPACE = MENDIX_APP.AGENTS
    DEFAULT_ROLE = VF_APP_ROLE
    COMMENT = 'Service account for the Mendix VF Logistics Portal (key-pair authentication)';
-- RSA_PUBLIC_KEY set separately per step (b) above once the new key pair exists.

GRANT ROLE VF_APP_ROLE TO USER MENDIX_SERVICE_USER;

-- 8. Data governance tags + column/table tagging (also present in 01_schema_ddl_fresh.sql
--    via WITH TAG clauses on BILL_OF_LADING_EXTRACTED / FRAUD_ALERT / HS_CODE_REFERENCE;
--    the three below are additional column-level PII tags not captured by table DDL).
ALTER TABLE MENDIX_APP.AGENTS.BILL_OF_LADING ALTER COLUMN SHIPPER_NAME SET TAG MENDIX_APP.AGENTS.PII_FLAG = 'YES';
ALTER TABLE MENDIX_APP.AGENTS.BILL_OF_LADING ALTER COLUMN CONSIGNEE_NAME SET TAG MENDIX_APP.AGENTS.PII_FLAG = 'YES';
ALTER TABLE MENDIX_APP.AGENTS.BILL_OF_LADING ALTER COLUMN NOTIFY_PARTY SET TAG MENDIX_APP.AGENTS.PII_FLAG = 'YES';
ALTER TABLE MENDIX_APP.AGENTS.BILL_OF_LADING SET TAG MENDIX_APP.AGENTS.DATA_DOMAIN='LOGISTICS', MENDIX_APP.AGENTS.DATA_SENSITIVITY='CONFIDENTIAL', MENDIX_APP.AGENTS.DATA_OWNER='Operations Team', MENDIX_APP.AGENTS.PII_FLAG='YES';

-- Verified source counts at backup time (2026-08-17), for restore validation:
--   BILL_OF_LADING=10017, FRAUD_ALERT=445, WORKFLOW_AUDIT_LOG=1553 (max AUDIT_ID ~2412+),
--   AI_CALL_LOG=355, SAP_FI_DOCUMENT=281, HS_CODE_REFERENCE=30, APP_CONFIG=16,
--   PORT_MASTER=23, VESSEL_REGISTRY=21, NOTIFICATION_LOG=179, COMPLIANCE_CHECK_RESULT=4,
--   BILL_OF_LADING_EXTRACTED=15, AI_MODEL_RATE=3
