-- Load data from backup_2026-08-17/data/*.csv into the NEW account.
-- Run AFTER 01_schema_ddl_fresh.sql and 03_account_objects.sql (in that order).
-- Upload the local CSVs first:
--   PUT file://.../backup_2026-08-17/data/*.csv @MENDIX_APP.AGENTS.LOGISTICS_STAGE/restore/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- Then run the loads below.

USE DATABASE MENDIX_APP;
USE SCHEMA AGENTS;

TRUNCATE TABLE IF EXISTS BILL_OF_LADING;
COPY INTO BILL_OF_LADING FROM @LOGISTICS_STAGE/restore/bill_of_lading.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 10017 rows

TRUNCATE TABLE IF EXISTS BILL_OF_LADING_EXTRACTED;
COPY INTO BILL_OF_LADING_EXTRACTED FROM @LOGISTICS_STAGE/restore/bill_of_lading_extracted.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 15 rows

TRUNCATE TABLE IF EXISTS FRAUD_ALERT;
COPY INTO FRAUD_ALERT FROM @LOGISTICS_STAGE/restore/fraud_alert.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 445 rows

TRUNCATE TABLE IF EXISTS HS_CODE_REFERENCE;
COPY INTO HS_CODE_REFERENCE FROM @LOGISTICS_STAGE/restore/hs_code_reference.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 30 rows

TRUNCATE TABLE IF EXISTS APP_CONFIG;
COPY INTO APP_CONFIG FROM @LOGISTICS_STAGE/restore/app_config.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 16 rows

TRUNCATE TABLE IF EXISTS WORKFLOW_AUDIT_LOG;
COPY INTO WORKFLOW_AUDIT_LOG FROM @LOGISTICS_STAGE/restore/workflow_audit_log.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 1553 rows

TRUNCATE TABLE IF EXISTS AI_CALL_LOG;
COPY INTO AI_CALL_LOG FROM @LOGISTICS_STAGE/restore/ai_call_log.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 355 rows

TRUNCATE TABLE IF EXISTS SAP_FI_DOCUMENT;
COPY INTO SAP_FI_DOCUMENT FROM @LOGISTICS_STAGE/restore/sap_fi_document.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 281 rows

TRUNCATE TABLE IF EXISTS AI_MODEL_RATE;
COPY INTO AI_MODEL_RATE FROM @LOGISTICS_STAGE/restore/ai_model_rate.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 3 rows

TRUNCATE TABLE IF EXISTS PORT_MASTER;
COPY INTO PORT_MASTER FROM @LOGISTICS_STAGE/restore/port_master.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 23 rows

TRUNCATE TABLE IF EXISTS VESSEL_REGISTRY;
COPY INTO VESSEL_REGISTRY FROM @LOGISTICS_STAGE/restore/vessel_registry.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 21 rows

TRUNCATE TABLE IF EXISTS NOTIFICATION_LOG;
COPY INTO NOTIFICATION_LOG FROM @LOGISTICS_STAGE/restore/notification_log.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 179 rows

TRUNCATE TABLE IF EXISTS COMPLIANCE_CHECK_RESULT;
COPY INTO COMPLIANCE_CHECK_RESULT FROM @LOGISTICS_STAGE/restore/compliance_check_result.csv
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=0) ON_ERROR='CONTINUE';
-- Expected: 4 rows

-- IMPORTANT: every table above uses an AUTOINCREMENT primary key that was loaded with
-- explicit values from CSV. The autoincrement counter does NOT auto-adjust after a
-- TRUNCATE + COPY INTO with explicit PK values (documented gotcha from the 2026-07-23
-- migration — see memory account-migration.md). Before letting any procedure insert new
-- rows via autoincrement (e.g. WORKFLOW_DETECT_AND_ACT creating new FRAUD_ALERT rows),
-- recreate each of these tables with AUTOINCREMENT START = <current MAX(pk)+1>, e.g.:
--   ALTER TABLE FRAUD_ALERT SET ... -- not supported directly; must recreate the table:
--   CREATE TABLE FRAUD_ALERT_NEW LIKE FRAUD_ALERT; ALTER TABLE FRAUD_ALERT_NEW ...
-- Simpler in practice: run a one-off check right after loading:
--   SELECT ALERT_ID, COUNT(*) FROM FRAUD_ALERT GROUP BY ALERT_ID HAVING COUNT(*) > 1;
-- (should return 0 rows) then verify the FIRST new procedure-driven insert produces an
-- ID greater than the current MAX — if not, recreate the table with a bumped START.

-- Rebuild BL_SEARCH_CORPUS from BILL_OF_LADING (used by Cortex Search) — cheap to
-- regenerate, so it is NOT included in the CSV backups.
TRUNCATE TABLE IF EXISTS BL_SEARCH_CORPUS;
INSERT INTO BL_SEARCH_CORPUS
SELECT
    BL_ID, BL_NUMBER,
    COALESCE(BL_NUMBER,'') || ' ' || COALESCE(CARRIER_NAME,'') || ' ' ||
    COALESCE(SHIPPER_NAME,'') || ' ' || COALESCE(CONSIGNEE_NAME,'') || ' ' ||
    COALESCE(COMMODITY_DESCRIPTION,'') || ' ' || COALESCE(VESSEL_NAME,'') || ' ' ||
    COALESCE(PORT_OF_LOADING_LOCODE,'') || ' ' || COALESCE(PORT_OF_DISCHARGE_LOCODE,'') || ' ' ||
    COALESCE(CONTAINER_NUMBER,'') || ' ' || COALESCE(STATUS,'') AS SEARCH_TEXT,
    STATUS, CARRIER_NAME, TOTAL_CHARGES, PORT_OF_LOADING_LOCODE, PORT_OF_DISCHARGE_LOCODE, CREATED_AT
FROM BILL_OF_LADING;

-- Verify all counts match the "Expected" comments above:
SELECT 'BILL_OF_LADING' T, COUNT(*) N FROM BILL_OF_LADING
UNION ALL SELECT 'FRAUD_ALERT', COUNT(*) FROM FRAUD_ALERT
UNION ALL SELECT 'WORKFLOW_AUDIT_LOG', COUNT(*) FROM WORKFLOW_AUDIT_LOG
UNION ALL SELECT 'AI_CALL_LOG', COUNT(*) FROM AI_CALL_LOG
UNION ALL SELECT 'SAP_FI_DOCUMENT', COUNT(*) FROM SAP_FI_DOCUMENT;
